### ISSUE TITLE
Question for "bamCoverage --filterRNAstrand" option

### ISSUE THREAD

**Issue by dahun73** [deeptools/deepTools#1004]
Hello, 

I'm using deeptools to visualize into UCSC genome browser.
Actually, I have question for RNA-seq read to bigWig file.

If RNA-seq samples, we should separate strand information for plus and minus.
In manual, it said that "–filterRNAstrand=forward keeps minus-strand reads, which originally came from genes on the forward strand using a dUTP-based method".

Does it mean that '--fileterRNAstrand=forward' means to eliminate forward strand? Thus, using '--fileterRNAstrand=forward' option, I understand that minus strand of bigWig file would be made. when checking in UCSC genome browser, it seems to be reversed.
![image](https://user-images.githubusercontent.com/52641420/94098744-42da2a00-fe64-11ea-9400-c8ddbcb682ad.png)

Thank you for reading

Dahun

**Comment by vivekbhr** [comment]
Hi @dahun73 
In dUTP based library prep kits, the dUTP is added during second strand synthesis and second strand (which represents original RNA strand) is degraded. So reverse reads come from forward strand. Thus, –filterRNAstrand=forward keeps the reverse reads. If your library prep kit was different, it's possible you get the opposite behaviour.
