### ISSUE TITLE
bamCoverage cpus and memory

### ISSUE THREAD

**Issue by Smartmandm** [deeptools/deepTools#1008]
Hello,

I have to run bamCoverage on a couple of bam files which are 2 Gb size on average, with 200 bp bin size setting.  How much time can I expect for the running?... I launched the tool with one bam file on HPC  (8 cpus with 8000M memory ). After half an hour it seems to get stuck ... or should I wait longer?... 

PoolWorker-33,  processing 23720 (96184.3 per sec) reads @ chr3:10000000-15000000
PoolWorker-33 countReadsInRegions_worker: processing 25000 (88411.4 per sec) @ chr3:10000000-15000000
PoolWorker-33,  processing 28579 (99040.0 per sec) reads @ chr6:10000000-15000000
PoolWorker-33 countReadsInRegions_worker: processing 25000 (76640.4 per sec) @ chr6:10000000-15000000
.... get stuck, the program does not end but does not continue either.

Thanks!

**Comment by dpryan79** [comment]
Normally I would expect it would finish in approximately that amount of time, but certainly if it's still running 2 days later then some child process got killed for some reason and it's frozen.
