### ISSUE TITLE
plotCoverage --extendReads flag causing duplicated coverage count with PE bam

### ISSUE THREAD

**Issue by benplm** [deeptools/deepTools#1009]
```
# software version
deeptools 3.5.0
Python 3.8.6

# command
plotCoverage -b *.bam -o coverage.pdf  --extendReads -p 8
```
When using the `--extendReads` flag in plotCoverage with paired-end reads, **all mapped in proper pair**, all the sampled nucleotides are covered by an even number of reads, causing the following plot:
![image](https://user-images.githubusercontent.com/34317613/97327177-03449a80-1875-11eb-95ce-7959a3bb4bd4.png)

Launching the same command without the `--extendReads` flag solves it.

I guess that read pairs are counted twice, rather than once, resulting in no nucleotides covered by 1, 3, 5, etc... reads.

I didn't check if this also affects other tools, such as plotFingerprint.

**Comment by dpryan79** [comment]
Yes, this is expected, since it handles cases where you have some improper pairs as well. If that's a problem then just exclude one mate (e.g., `--samFlagExclude 128`).

**Comment by benplm** [comment]
Right, I didn't think about that!
Thank you!
