### ISSUE TITLE
ComputeMatrix not working with subsetted GTF file

### ISSUE THREAD

**Issue by hbandukw** [deeptools/deepTools#1011]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [ ] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

 - [ ] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.
deeptools 3.3.2
Python 3.7.4

 - [ ] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).

I am using the Gencode M25 gtf file, I subsetted this gtf file based on gene identifiers from another list of interest. Please note that I included all exons, transcripts, genes etc associated with the ENSEMBL identifier in my new gtf list. 

- Read files
M25 = pd.read_csv(os.path.join(PathtoFiles, "gencode.vM25.annotation.gtf"), comment='#', sep='\t', header=None)
FileOfInterest = pd.read_excel(os.path.join(PathtoFiles, "File.xlsx"))

- extract Ensembl id from the last column and add it to df as 10th column
M25[9] = M25[8].str.split(";").str[0]
M25[10] = M25[9].str.split().str[1].str.replace('"', '').str.split(".").str[0]

- merge with excel file containing ensemble ids of interest (included duplicates)
df = pd.merge(left=M25, right=FileOfInterest, left_on=10, right_on="ENSEMBL ID", indicator=True)

- Remove unceccessary columns from merged df
Cols = df.columns.tolist()
Cols = [0,1,2,3,4,5,6,7,8]
Subsetted_M25 = df[Cols]

- Save as gtf
Subsetted_M25.to_csv(os.path.join(PathtoFiles, "Subsetted_M25.gtf"), index=None, header=False, sep='\t')
<img width="831" alt="Screen Shot 2020-11-04 at 8 04 56 AM" src="https://user-images.githubusercontent.com/20444993/98115796-633ed080-1e75-11eb-99ea-ebfb125ed6a7.png">

- I then used this new gtf file with ComputeMatrix:

computeMatrix scale-regions -S bigwigfile1.bw bigwigfile2.bw bigwigfile3.bw \
                 --samplesLabel "bw1" "bw2" "bw3" \
                 -R $OUTPUTPATH/Subsetted_M25.gtf  \
                 --beforeRegionStartLength 1000 \
                 --regionBodyLength 5000 \
                 --afterRegionStartLength 1000 \
                 --missingDataAsZero --skipZeros -o $OUTPUTPATH/bigwig.mat.gz -p 8

 - [ ] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).

Traceback (most recent call last):
  File "/home/hbanduk/.local/bin/computeMatrix", line 14, in <module>
    main(args)
  File "/home/hbanduk/.local/lib/python3.7/site-packages/deeptools/computeMatrix.py", line 421, in main
    hm.computeMatrix(scores_file_list, args.regionsFileName, parameters, blackListFileName=args.blackListFileName, verbose=args.verbose, allArgs=args)
  File "/home/hbanduk/.local/lib/python3.7/site-packages/deeptools/heatmapper.py", line 264, in computeMatrix
    verbose=verbose)
  File "/home/hbanduk/.local/lib/python3.7/site-packages/deeptools/mapReduce.py", line 85, in mapReduce
    bed_interval_tree = GTF(bedFile, defaultGroup=defaultGroup, transcriptID=transcriptID, exonID=exonID, transcript_id_designator=transcript_id_designator, keepExons=keepExons)
  File "/home/hbanduk/.local/lib/python3.7/site-packages/deeptoolsintervals/parse.py", line 597, in __init__
    self.parseBED(fp, line, 6, labelColumn)
  File "/home/hbanduk/.local/lib/python3.7/site-packages/deeptoolsintervals/parse.py", line 317, in parseBED
    self.parseBEDcore(line, ncols)
  File "/home/hbanduk/.local/lib/python3.7/site-packages/deeptoolsintervals/parse.py", line 225, in parseBEDcore
    if int(cols[1]) < 0:
ValueError: invalid literal for int() with base 10: 'HAVANA'

ComputeMatrix works just fine with the original Gencode GTF list but not with my subsetted list. I can't spot any obvious reasons. Please let me know what I can do.

**Comment by LeilyR** [comment]
The error shows that it detects your regions as a bed file. The reason is that your saved file format is wrong. In a GTF file you need a space after gene_id which is missing in your file, thus it has been detected as a bed file and it fails because it does not have a coordinate on the second column as a proper bed file too.

**Comment by hbandukw** [comment]
Hello,

Thanks for your response. 

I am confused though because the 8th column was untouched. It contains all the original information (in the original format) from the original gtf file. I have pasted a screen-shot of the original GTF file. 

<img width="762" alt="Screen Shot 2020-11-04 at 9 14 53 AM" src="https://user-images.githubusercontent.com/20444993/98122281-5e324f00-1e7e-11eb-9198-5980af507743.png">

**Comment by LeilyR** [comment]
If so then it should have failed to, because gene_id is what deeptools look for to decide if it is a gif file. My fear is that this is coming from how pandas read your csv not how actually your GTF is. Can you try head in bash ?

**Comment by hbandukw** [comment]
hmm I see. 
Here you go:
<img width="1228" alt="Screen Shot 2020-11-04 at 9 31 02 AM" src="https://user-images.githubusercontent.com/20444993/98123901-7c00b380-1e80-11eb-85bb-8ab73f24c966.png">

**Comment by hbandukw** [comment]
I just noticed the double quotations in the column. I guess that is the problem. Any idea why that is happening?

**Comment by LeilyR** [comment]
and yes I can easily see the space after gene_id, fix this in your output file

**Comment by hbandukw** [comment]
So the space is there after gene_id and it just the double-quotations that after affecting it?

**Comment by LeilyR** [comment]
the first file you have sent its head is not a correct gtf file, there is also a " before gene_id

**Comment by hbandukw** [comment]
Yeah that is the one I made and the second head is the original Gtf from Gencode. I will fix that and try again. Thanks for your help.

**Comment by hbandukw** [comment]
It worked after fixing the problem with the quotes. I will close this issue now.
