### ISSUE TITLE
Plotly causes errors in utilities.py

### ISSUE THREAD

**Issue by BJWiley233** [deeptools/deepTools#1013]
Hi,
When I try to run plotly output with the heatmap I get error in utilities.py `TypeError: 'map' object is not subscriptable` because you are trying to subscript a map which is not allowed in Python 3.  We need to update this if using Python 3 to `C = list(map(np.uint8, np.array(cmap(k * h)[:3]) * 255))`

In addition may want to look at matplotlib deprecation warning at `correlation.py:306`
```

MatplotlibDeprecationWarning:

You are modifying the state of a globally registered colormap. In future versions, you will not be able to modify a registered colormap in-place. To remove this warning, you can make a copy of the colormap first. cmap = copy.copy(mpl.cm.get_cmap("jet"))
```

**Comment by LeilyR** [comment]
it has been taken care of in #1018. already in develop.
