### ISSUE TITLE
OSError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by hemantgujar** [deeptools/deepTools#1016]
Dear Sir

I got some some problem with bamCoverage. Have I used the export command properly ? Can you please help with this error . 

Thanks. 

`deeptools --version`
deeptools 3.5.0
`python --version`
Python 3.7.6

`export TEMPDIR=/scratch/`

ok so later i also tried https://github.com/deeptools/deepTools/issues/890 
`export $TMPDIR=/scratch` but i got this error 
/var/spool/slurm/d/job880629/slurm_script: line 10: export: `/tmp=/scratch/': not a valid identifier

```
bamCoverage -b bam_files/${SAMPLE[i]}.clean_sorted.bam -o coverage/${SAMPLE[i]}.coverage.bw --outFileFormat bigwig \
--effectiveGenomeSize 2701495761 --normalizeUsing RPGC --exactScaling --ignoreDuplicates --minMappingQuality 20
```

normalization: 1x (effective genome size 2701495761)
bamFilesList: ['bam_files/E5EVK36D54.clean_sorted.bam']
binLength: 50
numberOfSamples: None
blackListFileName: None
skipZeroOverZero: False
bed_and_bin: False
genomeChunkSize: None
defaultFragmentLength: read length
numberOfProcessors: 1
verbose: False
region: None
bedFile: None
minMappingQuality: 20
ignoreDuplicates: True
chrsToSkip: []
stepSize: 50
center_read: False
samFlag_include: None
samFlag_exclude: None
minFragmentLength: 0
maxFragmentLength: 0
zerosToNans: False
smoothLength: None
save_data: False
out_file_for_raw_data: None
maxPairedFragmentLength: 1000
Due to filtering, 90.5277447943057% of the aforementioned alignments will be used 257281786.1886005
Traceback (most recent call last):
  File "/software/deepTools/bin/bamCoverage", line 12, in <module>
    main(args)
  File "/software/python_package/deeptools/bamCoverage.py", line 258, in main
    format=args.outFileFormat, smoothLength=args.smoothLength)
  File "/software/python_package/deeptools/writeBedGraph.py", line 152, in run
    numberOfProcessors=self.numberOfProcessors)
  File "/software/python_package/deeptools/mapReduce.py", line 146, in mapReduce
    res = list(map(func, TASKS))
  File "/software/python_package/deeptools/writeBedGraph.py", line 27, in writeBedGraph_wrapper
    return WriteBedGraph.writeBedGraph_worker(*args)
  File "/software/python_package/deeptools/writeBedGraph.py", line 271, in writeBedGraph_worker
    line_string.format(chrom, writeStart, writeEnd, previous_value))
OSError: [Errno 28] No space left on device

**Comment by iichelhadi** [comment]
got the same issue. any solutions or at least the reason?

**Comment by adRn-s** [comment]
what's your path? are you using `TMPDIR` ? have you checked the space left? it might be full.

**Comment by iichelhadi** [comment]
issue seems resolved. no explanation why. my drive wasn't full I checked before posting
