### ISSUE TITLE
how to deal with unstranded paired-end data using bamCoverage

### ISSUE THREAD

**Issue by dahun73** [deeptools/deepTools#1021]
Hello!

I have a question about making bigWig files using bamCoverage.

If our library type is unstranded paired-end, how do I make strand specific bigWig files?
In case of unstranded paired-end, Reads could not be discriminated by directions. Is it possible to make strand specific bigwig files? Because of this library type, mapped reads are devided half of each strand.

Thanks
Dahun

**Comment by dpryan79** [comment]
If your library is unstranded it is impossible with any method to generate stranded information from it given only the reads.
