### ISSUE TITLE
compute matrix : reference point (center)

### ISSUE THREAD

**Issue by Smartmandm** [deeptools/deepTools#1029]
Hello,

I have a bed file with regions around the TSS already defined (+ and - 1000 bp around the TSS). 

I want to obtain a heatmap centred around the TSS (+ and - 1000 bp around the TSS),  so I wanted to confirm
that I should choose ''center'' as reference point and ''1000'' for both -a and -b (--beforeRegionStartLength (-b) and --afterRegionStartLength (-a)).

Thank you!

Marie

**Comment by dpryan79** [comment]
You can either use a reference-point of "center" and flank it by 1kb or just scale-regions with no flank, the only difference will be a few x-axis tick labels.
