### ISSUE TITLE
Where is the Scaling Factor output from bamCoverage when using --normalizeUsing CPM

### ISSUE THREAD

**Issue by monnieb92** [deeptools/deepTools#1031]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - How do you determine the scaling factor used when telling bamCoverage to normalize with CPM?

 - deepTools version (`deeptools 3.4.1`) and your python
 version (`Python 3.7.7`)

``` {bash, anaconda}
 bamCoverage -b ../5568-AE_bam/5568-MB-9.hg19.F4q10.sorted.bam --normalizeUsing CPM  -of 'bigwig' -bs 20 -o 5568-ETOZnf_minusdT_A.normCPM.bw -p 6
  ```
```{bash, anaconda}
#Output:
normalization: CPM
bamFilesList: ['../5568-AE_bam/5568-MB-9.hg19.F4q10.sorted.bam']
binLength: 20
numberOfSamples: None
blackListFileName: None
skipZeroOverZero: False
bed_and_bin: False
genomeChunkSize: None
defaultFragmentLength: read length
numberOfProcessors: 6
verbose: False
region: None
bedFile: None
minMappingQuality: None
ignoreDuplicates: False
chrsToSkip: []
stepSize: 20
center_read: False
samFlag_include: None
samFlag_exclude: None
minFragmentLength: 0
maxFragmentLength: 0
zerosToNans: False
smoothLength: None
save_data: False
out_file_for_raw_data: None
maxPairedFragmentLength: 1000
```

**Comment by dpryan79** [comment]
There's no way currently to print that without modifying the code (there's a global `debug` variable one could change). The value is given by: https://github.com/deeptools/deepTools/blob/7811ae7f642641caddb407971006d7d536091122/deeptools/getScaleFactor.py#L278-L279
Note that the initial value of `scaling_factor` is 1 and `bam_mapped` is an estimate of the total mapped reads in the file after any specified filtering.
