### ISSUE TITLE
alignmentSieve doesn't run (just hangs)

### ISSUE THREAD

**Issue by BJWiley233** [deeptools/deepTools#1032]
Hi,
I am using Python 3.7 on Anaconda and deeptools 3.5.0.  When I run alignmentSieve it just hangs.  Nothing runs.  I ran on my sorted and indexed bam file which only has ~264,000 aligmnets.  Any reason for this.  Example ran was:

`alignmentSieve --ATACshift --bam SRR891268.markdups.bycoord.bam -o SRR891268_shift.tmp.bam`

I know its running because I get error when submitting a bam file that is sorted by name as in:

`alignmentSieve --ATACshift --bam SRR891268.markdups.byname.bam -o SRR891268_shift.tmp.bam`

How long should this script take to run if only ~264,000 alignments on 8GB RAM and CPU MHz: 508.203?

**Comment by BJWiley233** [comment]
I ended up running on a server instead so it ran much faster.  Still doesn't seem like it should take a long time on a regular computer.

**Comment by dpryan79** [comment]
Presumably you have a lot of contigs in your genome and ran with a single thread. This has to process every contig, even if there are no alignments there, since most ATAC experiments will have 100x as many entries spread across the genome.
