### ISSUE TITLE
computeMatrix samplesLabel: number of sample labels does not match number of samples

### ISSUE THREAD

**Issue by mdozmorov** [deeptools/deepTools#1033]
The following command:
```
computeMatrix reference-point --referencePoint center -S $FILETF -R $FILE1 $FILE2 $FILE3 -o $FILEMAT --samplesLabel Label1 Label2 Label3
```
breaks with `AssertionError: number of sample labels does not match number of samples`. Without the `--samplesLabel` argument, it works as expected, putting the file names as labels.  My understanding or the `--samplesLabel` argument from the [documentation](https://deeptools.readthedocs.io/en/develop/content/tools/computeMatrix.html) is that it refers to the BED files after the `-R ` argument, so why is the error? Thanks!

Python 3.7.9
deeptools 3.5.0

```
Traceback (most recent call last):
  File "/Users/mdozmorov/miniconda3/envs/deeptools/bin/computeMatrix", line 14, in <module>
    main(args)
  File "/Users/mdozmorov/miniconda3/envs/deeptools/lib/python3.7/site-packages/deeptools/computeMatrix.py", line 421, in main
    hm.computeMatrix(scores_file_list, args.regionsFileName, parameters, blackListFileName=args.blackListFileName, verbose=args.verbose, allArgs=args)
  File "/Users/mdozmorov/miniconda3/envs/deeptools/lib/python3.7/site-packages/deeptools/heatmapper.py", line 348, in computeMatrix
    sample_labels)
  File "/Users/mdozmorov/miniconda3/envs/deeptools/lib/python3.7/site-packages/deeptools/heatmapper.py", line 1123, in __init__
    "number of sample labels does not match number of samples"
AssertionError: number of sample labels does not match number of samples
```

**Comment by mdozmorov** [comment]
It appears the `--samplesLabel` argument refers to the `-S` bigWig file. Would be good to clarify in the documentation, and make a similar argument for the samples for the `-R` argument. Thanks for deeptools!

**Comment by LeilyR** [comment]
Both `plotHeatmap` and `plotProfile` offer `--regionsLabel` to label your regions from the given bed files, this might be what you are looking for.

**Comment by mdozmorov** [comment]
I overlooked that - exactly what I was looking for. Thanks @LeilyR
