### ISSUE TITLE
Using `computeMatrix scale-regions` and `plotHeatmaps` to visualize PRO-seq data

### ISSUE THREAD

**Issue by monnieb92** [deeptools/deepTools#1034]
Current Versions: 
deeptools 3.4.1
Python 3.7.7

Hi, I am wanting to use scale-regions with computeMatrix to visualize some of my significantly changed genes in my PRO-seq (similar to GRO-seq) dataset as Homer does not provide anything similar to this, but I am not sure this would properly visualize the data as I get strand specific data. What should the input be for the computeMatrix as I would normally have two bigWig(forward and reverse) files from  `bamCoverage`, do I just make a single non-stranded bigWig file with `bamCoverage`? 

Thank you for your help!

**Comment by dpryan79** [comment]
If you have strand-specific data you need to make bigWigs for each strand and either treat them as different samples or use computeMatrixOperations to merge strand-specific matrices.
