### ISSUE TITLE
how to get the message printed on the screen from deeptools tools

### ISSUE THREAD

**Issue by shangguandong1996** [deeptools/deepTools#1035]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [X] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

 - [X] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.

 - [X] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).

 - [ ] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).

Hi, dear developer
I am wondering whether I can get the message on the screen when I run the command of deeptools tools. For example, when I run the 
```
bamCompare -b1 H3K9me3_S8.merge.bam -b2 Input_S8.merge.bam -o log2ratio.bw
```

it will print below message on the screen, but how can I import this message into other log file ? I try to use `2>&1 > log`, but it seems not work, the message still be printed on the screen.
```
bamFilesList: ['H3K9me3_S8.merge.bam', 'Input_S8.merge.bam']
numberOfProcessors: 2
samFlag_exclude: None
save_data: False
stepSize: 10
smoothLength: None
blackListFileName: None
center_read: False
ignoreDuplicates: False
defaultFragmentLength: read length
chrsToSkip: []
region: None
maxPairedFragmentLength: 1000
samFlag_include: None
binLength: 10
maxFragmentLength: 0
minMappingQuality: None
zerosToNans: False
minFragmentLength: 0
verbose: False
out_file_for_raw_data: None
numberOfSamples: 0
bedFile: None

```

```
$ deeptools --version
deeptools 3.1.2
```

Best wishes
Guandong Shang

**Comment by LeilyR** [comment]
try 
`bamCompare -b1 H3K9me3_S8.merge.bam -b2 Input_S8.merge.bam -o log2ratio.bw  &>  log`

**Comment by dpryan79** [comment]
I believe it's printed to stdout, rather than stderr.
