### ISSUE TITLE
first position of chromsome is not included when running bamCoverage with -r chrom

### ISSUE THREAD

**Issue by ghuls** [deeptools/deepTools#1038]
```
❯ deeptools --version
deeptools 3.5.0

❯ python --version
Python 3.7.4
```

```
# Run bamCoverage on the whole BAM.
bamCoverage -v -p 4 -bs 1 -b ${bam} -o ${bam}.test.bw

# Run bamConverage on chr2R only.
bamCoverage -v -p 4 -bs 1 -r chr2R -b ${bam} -o ${bam}.chr2R.test.bw

# Extract all bedGraph line for both bigWig files for chr2R and compare.
diff -u <(bigWigToBedGraph -chrom=chr2R ${bam}.test.bw /dev/stdout) <(bigWigToBedGraph -chrom=chr2R ${bam}.chr2R.test.bw/dev/stdout)
```

When specifying `chr2R` the bigWig does not include the first nucleotide of the chromosome. (In this case the values there are zero, but still weird that bamCoverage does not generate the same).

```
--- /dev/fd/62  2021-01-25 16:45:11.061322341 +0100
+++ /dev/fd/62  2021-01-25 16:45:11.061322341 +0100
@@ -1,4 +1,4 @@
-chr2R  0       1007    0
+chr2R  1       1007    0
 chr2R  1007    1017    1
 chr2R  1017    1055    2
 chr2R  1055    1066    1
```

**Comment by LeilyR** [comment]
Hi @ghuls , I will have a look at it and see if I can regenerate your issue. 
(#1039 is related to this issue)

**Comment by LeilyR** [comment]
I have tested the bamCoverage on a bam file with and without -r argument, I could see that with -r the coordinates start from one and zero is skipped, however I do not get different bg files. One thing I wonder was that why you have not generated the bed graph files directly as an output of bamCoverage and used  bigWigToBedGraph? 
Anyhow, apart from that single base I get the same file, there are places that a region of same values merged in one but not the other but no difference between the bins and assigned values to them. 
Maybe you can try the direct bed graph output and see how they look, also if you still have the problem feel free to share your bam files with us then we cna have a look.

**Comment by LeilyR** [comment]
So at the end your problem was your index file and your issue is already solved, right? I close this issue , but please reopen it if there is anything that can be done on our side.
