### ISSUE TITLE
Choose proper normalization method making bigWig files

### ISSUE THREAD

**Issue by dahun73** [deeptools/deepTools#1040]
Hello!

I have a question about making bigWig files using bamCoverage.
When I make bigWig files, all the samples have different mapped reads. And also, there are many different normalization method in bamCoverage(RPKM, CPM, BPM, RPGC, and so on). If I compare with all the bigWig files(actually it is ChIP-seq), which one is the best normalization method? 

Thank you for in advance!

**Comment by LeilyR** [comment]
Hi, 
I would recommend you to check the [documentation](https://deeptools.readthedocs.io/en/develop/content/tools/bamCoverage.html?highlight=normalization#Read%20coverage%20normalization%20options) for the description of different methods. However, for ChIP data you could use RPGC or RPKM.

**Comment by dahun73** [comment]
Thank you for reply :)

I usually use RPGC option too. But I'm worried about whether I used proper normalization options among different samples. When I watch different samples of bigWig, there are different library read length. I've known that it should be set by organism and library read length. Is it okay just setting by organism?

For example, I have 2 ChIP-seq samples(mouse). For the library read length, one is 75bp and the other is 150bp. I want to compare with these two samples. Then, I decide to use RPGC normalization option. In this case, is it okay using '--effectiveGenomeSize 2652783500'? This value was written in manual(GRCm38).
