### ISSUE TITLE
plotCoverage.py error

### ISSUE THREAD

**Issue by xyz0o** [deeptools/deepTools#1044]
plotcoverage is embeded in the REPET docker container as one of the dependencies. I am trying to run it as a post process analysis but I receive this error:
```
Traceback (most recent call last):
  File "/usr/local/SMART/Java/Python/plotCoverage.py", line 464, in <module>
    pp.setOutput(options.outputFileName if os.path.isabs(options.outputFileName) else os.path.join(options.working_Dirpath, options.outputFileName))
AttributeError: Values instance has no attribute 'working_Dirpath'
Exception AttributeError: "'PlotParser' object has no attribute 'outputFileName'" in <bound method PlotParser.__del__ of <__main__.PlotParser object at 0x7f332506b3d0>> ignored
```
![capture1](https://user-images.githubusercontent.com/77616805/109296502-107c9080-7839-11eb-9145-e237a9c88ad3.jpg)

any body knows how I should fix this?

**Comment by dpryan79** [comment]
@xyz0o Can you let me know what version of matplotlib-base is installed in that container? looks like they changed how an object works.

**Comment by xyz0o** [comment]
> @xyz0o Can you let me know what version of matplotlib-base is installed in that container? Looks like they changed how an object works.

I searched for how I should check the version of matplotlib-base on centos (container is based on centos), I tried a couple of command lines but it doesn't work there. can you tell me how I should check the version please?

**Comment by dpryan79** [comment]
Please run the following: `python -c "import matplotlib; print(matplotlib.__version__)"`

**Comment by xyz0o** [comment]
2.2.3

**Comment by dpryan79** [comment]
Ah, it's been a few years since that version of matplotlib was supported. Please update to matplotlib 3.

**Comment by xyz0o** [comment]
I cannot upgrade because I have python 2.7 installed in the container and I cannot upgrade the python because REPET works with this version

```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
ERROR: Could not find a version that satisfies the requirement matplotlib==3.0.0 (from versions: 0.86, 0.86.1, 0.86.2, 0.91.0, 0.91.1, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1rc1, 1.4.1, 1.4.2, 1.4.3, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.1.0rc1, 2.1.0, 2.1.1, 2.1.2, 2.2.0rc1, 2.2.0, 2.2.2, 2.2.3, 2.2.4, 2.2.5)
ERROR: No matching distribution found for matplotlib==3.0.0
```
would there be any other reason for this error? unfortunately the REPET support team never answer emails and there is no other forum specifically for REPET issues, so I don' really know what to do

**Comment by dpryan79** [comment]
You'll have to install an older version of deepTools then. Try installing the last 2.X release.

**Comment by xyz0o** [comment]
I tried to install it on the host server using these commands:
```
$ git clone https://github.com/deeptools/deepTools
$ cd deepTools
$ python setup.py install
```

now when I test it:
`python plotCoverage.py 
`
it returns:

> Traceback (most recent call last):
>   File "/home/cloud-user/deepTools/deeptools/plotCoverage.py", line 15, in <module>
>     import plotly.offline as py
> ModuleNotFoundError: No module named 'plotly'

**Comment by dpryan79** [comment]
You need to actually install it, for example with `pip`

**Comment by xyz0o** [comment]
> plotcoverage is embeded in the REPET docker container as one of the dependencies. I am trying to run it as a post process analysis but I receive this error:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/SMART/Java/Python/plotCoverage.py", line 464, in <module>
>     pp.setOutput(options.outputFileName if os.path.isabs(options.outputFileName) else os.path.join(options.working_Dirpath, options.outputFileName))
> AttributeError: Values instance has no attribute 'working_Dirpath'
> Exception AttributeError: "'PlotParser' object has no attribute 'outputFileName'" in <bound method PlotParser.__del__ of <__main__.PlotParser object at 0x7f332506b3d0>> ignored
> ```
> 
> ![capture1](https://user-images.githubusercontent.com/77616805/109296502-107c9080-7839-11eb-9145-e237a9c88ad3.jpg)
> 
> any body knows how I should fix this?

solved this issue by adding the absolute path to the working-dir after the -o flag.

**Comment by dpryan79** [comment]
Weird, glad that solved it at least
