### ISSUE TITLE
bamCoverage CPM and BPM are the same

### ISSUE THREAD

**Issue by zqzneptune** [deeptools/deepTools#1048]
Hi, 

After checking the source code in [getScaleFactor.py](https://github.com/deeptools/deepTools/blob/7811ae7f642641caddb407971006d7d536091122/deeptools/getScaleFactor.py#L292),  I found out the computing of scaleFactor for BPM and CPM is the same:

CPM:
scale_factor *= 1.0 / (bam_mapped / 1e6)

BPM:
scale_factor *= 1 / ((bam_mapped / tile_len_in_kb) * tile_len_in_kb/ 1e6)

For BPM, tile_len_in_kb got canceled out eventually.

Am I missing some information here? Will this lead to identical bigWigs for BPM and CPM?

Johnson

**Comment by vivekbhr** [comment]
you're correct they effectively end up being the same. Originally the idea was to use the BPM norm for bigwigcompare in case the provided bin length between the 2 bigwigs are different, but I think we never went there..
