### ISSUE TITLE
How bamCoverage understand the paired-end BAM file

### ISSUE THREAD

**Issue by ZHIDIHUAYUAN** [deeptools/deepTools#1051]
Hi,
Could you please tell me what information the bamCoverage uses in a pair-end bam file?
I aligned the ATAC-seq data to a custom reference sequence, but I want to convert the coordinates of the bam file to the coordinates of hg38, and visualize it in IGV, so I want to know that which values should I modify in the bam file.

**Comment by dpryan79** [comment]
If you only change the coordinates then you should be fine, it needs the flag, MAPQ, read name, and TLEN fields.
