### ISSUE TITLE
How multiBamSummary computes the read coverages?

### ISSUE THREAD

**Issue by worsteggs** [deeptools/deepTools#1052]
Hi, teams,
thanks for your brilliant work.

I have a small question about the multiBamSummary BED-file mode. I wonder how multiBamSummary computes the read coverages. When a read touch a little of the specific region will be as 1 count? Like the below sample:
```
#test.bam
chr1 100 200 
#region.bed
chr1 119 1000
```

Or only when a read fully intersects among the specific region will be as 1 count? Like:
```
#test.bam
chr1 200 300
#region.bed
chr1 119 1000
```

Hope to get your nice help.

sincerely,
Zilch

**Comment by dpryan79** [comment]
A single base overlap is sufficient.
