### ISSUE TITLE
How does plotHeatmap sort multiple samples/columns?

### ISSUE THREAD

**Issue by donalday** [deeptools/deepTools#1053]
plotHeatmap sort multiple samples in a plot amazingly using “sortUsingSample”,
even better than clustering.
However, when I output the matrix and plot by myself, I found that my plot using the same data at the same order is not smooth, even for the first prioritized sample.
I wonder actually the plotHeatmap does not simply perform seauential sort on multiple columns.
Does anyone know how sorting inside plotHeatmap work? Thanks.

**Comment by dpryan79** [comment]
The smoothness is probably from matplotlib. Within plotHeatmap rows are scored by their average value either across all samples (default) or for the sample indicated by sortUsingSample. The sorting algorithm doesn't know that samples exist, it just sees a very large matrix and is giving scores to sort it with.

**Comment by donalday** [comment]
Thanks Ryan for clear and concise explanation.
