### ISSUE TITLE
bamCoverage: normalization of strand-wise bigwig tracks is based on only reads of the respective strand

### ISSUE THREAD

**Issue by ankebusch** [deeptools/deepTools#1055]
Hi everyone,

I came across a potential problem when creating strand-wise normalized tracks with bamCoverage (deepTools version 3.4.1, python version 3.7.0). When e.g. creating a normalized track of the positive strand, only counts on the positive strand are used to normalize instead of using the total counts found on both strands. While this does not cause any problem when reads are more or less equally spread on both strands, it can lead to a skewed picture, when strands are not equally covered. I created two toy samples to demonstrate the problem:

un-normalized track including both strands:

```
bamCoverage --binSize 1 --skipNAs --bam toy1.bam --outFileFormat bedgraph -o toy1.bedgraph
cat toy1.bedgraph
chr1    10      14      1
chr1    14      22      6
```

CPM-normalized track including both strands:

```
bamCoverage --binSize 1 --skipNAs --normalizeUsing CPM --bam toy1.bam --outFileFormat bedgraph -o toy1.CPM.bedgraph
cat toy1.CPM.bedgraph
chr1    10      14      19230.8
chr1    14      22      115385
```

CPM-normalized track of the positive strand:

```
bamCoverage --samFlagExclude 16 --binSize 1 --skipNAs --normalizeUsing CPM --bam toy1.bam --outFileFormat bedgraph -o toy1.CPM.fwd.bedgraph
cat toy1.CPM.fwd.bedgraph
chr1    10      14      250000
```

CPM-normalized track of the negative strand:

```
bamCoverage --samFlagInclude 16 --binSize 1 --skipNAs --normalizeUsing CPM --bam toy1.bam --outFileFormat bedgraph -o toy1.CPM.rev.bedgraph
cat toy1.CPM.rev.bedgraph
chr1    14      22      125000
```

When the normalization is only based on reads on the respective strand, it enhances the coverage on the less covered strand and, thus, strands are no longer comparable. Looking at second toy example (which has the same total number of mapped reads as the first example) demonstrates that also samples are longer comparable:

un-normalized track of both strands:

```
bamCoverage --binSize 1 --skipNAs --bam toy2.bam --outFileFormat bedgraph -o toy2.bedgraph
cat toy2.bedgraph
chr1    10      14      11
chr1    14      22      1
```

CPM-normalized track of both strands:

```
bamCoverage --binSize 1 --skipNAs --normalizeUsing CPM --bam toy2.bam --outFileFormat bedgraph -o toy2.CPM.bedgraph
cat toy2.CPM.bedgraph
chr1    10      14      211538
chr1    14      22      19230.8
```

CPM-normalized track of the positive strand:

```
bamCoverage --samFlagExclude 16 --binSize 1 --skipNAs --normalizeUsing CPM --bam toy2.bam --outFileFormat bedgraph -o toy2.CPM.fwd.bedgraph
cat toy2.CPM.fwd.bedgraph
chr1    10      14      250000
```

CPM-normalized track of the negative strand:

```
bamCoverage --samFlagInclude 16 --binSize 1 --skipNAs --normalizeUsing CPM --bam toy2.bam --outFileFormat bedgraph -o toy2.CPM.rev.bedgraph
cat toy2.CPM.rev.bedgraph
chr1    14      22      125000
```

Both samples (toy1 and toy2) have the same number of mapped reads, thus, they are directly comparable even before normalizing. While in the first example (toy1) positions on the positive strand were less covered than in the second example (toy2) before normalization, they appear to be equally covered in both samples after normalization.

Thus my question: wouldn't it be better to use the total number of mapped reads to normalized strand-wise tracks rather than using mapped reads on the respective strand only? Or is there a special reason to only use reads on the respective strand?

Many thanks in advance!

**Comment by dpryan79** [comment]
This is the intended result. It's more often that use-case that you only want to consider the filtered reads as the true signal and therefore want to normalize according to exclusively it.

**Comment by ankebusch** [comment]
Thanks a lot for the super fast reply!

What would you recommend in case someone wants to have the total normalized coverage, but separated by strand? Would you recommend using `--scaleFactor x`, where `x` needs to be manually calculated by `x = 10^6/total_mapped_reads`? Or is there an option in `bamCoverage` without prior calculation of `x`?

Thank you again in advance!

**Comment by dpryan79** [comment]
I'd recommend manually providing a scaling factor in such cases.
