### ISSUE TITLE
computeMatrix scale-regions: error with bed file

### ISSUE THREAD

**Issue by claramartinezmir** [deeptools/deepTools#1056]
Hello,

I am trying to run computeMatrix to make a heatmap, but I am running into an error when I use this particular bed file (attatchment 1). I did not noticed the error when I was using a subset bed file for only chromosome 10 (attatchment 2). So I am guessing the problem is my bed file which was downloaded from UCSC, but I can't find what is wrong.

Python [3.6.13]
deeptools 3.5.1 

DeepTools command:
computeMatrix scale-regions -R referencebed/genes/mm10_RefSeq.bed \
-S sample_coverage.bw \ 
-o sample.matrix.gz \
-b 3000 -a 3000 --regionBodyLength 5000

Output printed on screen:
computeMatrix scale-regions: error: argument --outFileName/-out/-o: sample.matrix.gz file can't be opened for writing
usage: An example usage is:
  computeMatrix scale-regions -S <biwig file(s)> -R <bed file> -b 1000

Thanks for your help!
Clara

**Comment by claramartinezmir** [comment]
[mm10_RefSeq.bed.gz](https://github.com/deeptools/deepTools/files/6277304/mm10_RefSeq.bed.gz)
[chr10.mm10_RefSeq.bed.gz](https://github.com/deeptools/deepTools/files/6277302/chr10.mm10_RefSeq.bed.gz)

**Comment by dpryan79** [comment]
The error suggests that you don't have write permissions to `sample.matrix.gz`. Check your write permissions there.

**Comment by claramartinezmir** [comment]
the file is created by the computeMatrix, it doesn't exist in my computer. computeMatrix closes without creating this output file.
What I don't understand is that I don't get this issue when I am using the exact code but with the small chr10 bed file.
