### ISSUE TITLE
How to calculate area under curve for profile plot

### ISSUE THREAD

**Issue by smartgamer** [deeptools/deepTools#1057]
Hi,

I created profile plots using deepTools. Now I want to compare samples. How to calculate area under curve for each sample?

Thanks,

**Comment by thomasmanke** [comment]
deepTools does not provide this function, but if you want to compare profiles you might want to have a look here: https://github.com/gtrichard/deepStats

**Comment by dpryan79** [comment]
Xref: https://www.biostars.org/p/9465051/#9465069
