### ISSUE TITLE
Gene ID name changed in the matrix sorted file 

### ISSUE THREAD

**Issue by swetasha** [deeptools/deepTools#1058]
I have gene IDs in my bed file in the fourth column but the sorted file coming as an output of the heatmap in deeptools changes the 4th column to region ids. Is there a way to maintain the names from my initial bed file to the sorted file? 

 
This is my sorted file with new region id for my genes: 
![Screen Shot 2021-04-15 at 4 43 04 PM](https://user-images.githubusercontent.com/76131084/114951642-ad0aea00-9e09-11eb-86ac-d4e72a3a70ce.png)

**Comment by dpryan79** [comment]
Are you sure your BED file has gene names? That's what we would store internally. We wouldn't add some region_XXX value there, since it has no meaning within deepTools.

**Comment by swetasha** [comment]
Yep, here is a screenshot of my BED file for reference. 
<img width="693" alt="Screen Shot 2021-04-18 at 8 47 06 PM" src="https://user-images.githubusercontent.com/76131084/115179098-6cb89f80-a087-11eb-8609-c89dc36d5a1f.png">

**Comment by dpryan79** [comment]
Something up or downstream of deepTools must be changing them then.

**Comment by swetasha** [comment]
Thank you for looking into it. I found what I did wrong. When I uploaded the BED file, it was uploaded as an "interval" file and thats what changed the name.
