### ISSUE TITLE
Compute matrix  --referencePoint usage 

### ISSUE THREAD

**Issue by Hemantcnaik** [deeptools/deepTools#1071]
Hello Thanks for the tool, 

I am using Computematrix --referencePoint TSS, TES, center. I understood center its mentioned as between TES and TSS it means a genebody,

If I wanted to plot for genebody I have to use `--referencePoint center` right 

Thank you.

**Comment by dpryan79** [comment]
I would use scale-region instead of reference-point for the gene body.

**Comment by Hemantcnaik** [comment]
Thanks for the quick replay
