### ISSUE TITLE
Combining spike-in normalization with CPM normalization in bamCoverage

### ISSUE THREAD

**Issue by isosceleswheel** [deeptools/deepTools#1073]
Hello,

[I was not able to post to your googlegroups page so I am posting my question here]

I am wondering if you can comment on best practices for normalization using the `bamCoverage` tool with CUT&RUN data.

I am using `bamCoverage` to construct bedgraph files from CUT&RUN sequencing data. For each CUT&RUN sample, I spike in 1ng E. coli DNA for normalization. I get the % of my total reads that align to E. coli after sequencing and calculate the `--scaleFactor` as 1/(%spike-in), so if 2% of the total reads map to E. coli, the call would be `--scaleFactor 0.5`.

My intuition is that I should only normalize my bedgraph with the `--scaleFactor` call and nothing else. However, I have seen pipelines that include `--normalizeUsing CPM` in conjunction with the spike-in based `--scaleFactor` as I described above. 

It seems to me that these two normalizations will potentially interfere with each other. The CPM normalizes to mapped reads, so if one of my samples has fewer mapped reads because of e.g., lower transcription factor binding activity, the normalization by mapped reads (CPM) would artificially inflate the signal and cancel out some of the effect of normalizing with the spike-in using `--scaleFactor`.

Can you comment on whether there is a best practice for this type of analysis, and whether or not I am correct that the two normalizations have the potential to conflict?

Thanks,

David Murphy
Gaffney Lab
Department of Genes and Human Disease
Oklahoma Medical Research Foundation

deeptools 3.4.3
Python 3.7.0

**Comment by dpryan79** [comment]
@isosceleswheel The procedure for normalizing according to a species spike-in is roughly:

1. Align spiked-in species
2. Compute scaling factor (e.g., `multiBamSummary ... --scalingFactors`). Note, you should have a look at some of the samples to ensure that the spiked-in species has vaguely uniform coverage. If the coverage is very spotty then you may need to use only the covered regions to compute scaling factors.
3. Use the scaling factors from step 2 with bamCoverage.

Whether the data is cut and run or ATAC-seq or standard ChIP-seq doesn't really matter, the basic procedure is the same. For sanity checking, also run bamCoverage with the scaling factors on the spiked-in data and ensure that they appear on the same scale by having a quick look at the data in IGV or another genome browser (always do this at each step, it will save you a lot of headaches).

**Comment by isosceleswheel** [comment]
> Hi, David,
> 
> Computing E.coli spike-in scale factor for CUT&Tag/RUN has been mentioned in this protocol (Step 16):
> 
> https://www.protocols.io/view/cut-amp-tag-data-processing-and-analysis-tutorial-bjk2kkye
> 
> -Johnson

**Comment by isosceleswheel** [comment]
> @isosceleswheel The procedure for normalizing according to a species spike-in is roughly:
> 
>     1. Align to spiked-in species
> 
>     2. Compute scaling factor (e.g., `multiBamSummary ... --scalingFactors`). Note, you should have a look at some of the samples to ensure that the spiked-in species has vaguely uniform coverage. If the coverage is very spotty then you may need to use only the covered regions to compute scaling factors.
> 
>     3. Use the scaling factors from step 2 with bamCoverage with your on-species alignments.
> 
> 
> Whether the data is cut and run or ATAC-seq or standard ChIP-seq doesn't really matter, the basic procedure is the same. For sanity checking, also run bamCoverage with the scaling factors on the spiked-in data and ensure that they appear on the same scale by having a quick look at the data in IGV or another genome browser (always do this at each step, it will save you a lot of headaches).

@dpryan79 So by following your procedure, is this the only scaling/normalization step needed for constructing my bedgraph files to enable quantitative comparisons? Referring back to my original post: would it be inappropriate to combine the spike-in normalization using `--scaleFactor` with a standard normalization routine like `--normalizeUsing CPM` (or any of the other routines like RPKM, etc.)?

**Comment by isosceleswheel** [comment]
> Hi, David,
> 
> Computing E.coli spike-in scale factor for CUT&Tag/RUN has been mentioned in this protocol (Step 16):
> 
> https://www.protocols.io/view/cut-amp-tag-data-processing-and-analysis-tutorial-bjk2kkye
> 
> -Johnson

@zqzneptune Thanks for posting this protocol, it was very helpful. It appears that here they also suggest using spike-in normalization _only_, as @dpryan79 seems to suggest in his post above. The example is for a CUT&Tag, but it seems that the spike-in normalization procedure is the same for CUT&RUN as well.

**Comment by dpryan79** [comment]
@isosceleswheel I personally prefer to not additionally convert to CPM, you're better off working directly on normalized counts so you know any comparisons you make aren't being unduly skewed by additional normalization.

**Comment by LeilyR** [comment]
Just an addition to Devon's comment. You could also consider mapping on a combined genome (host+spike-in) and split your bam files later on after filtering for mapq.

**Comment by isosceleswheel** [comment]
@LeilyR @dpryan79 Thanks for the additional suggestions and feedback!
