### ISSUE TITLE
multiBigwigSummary BED-file mode average scores meaning

### ISSUE THREAD

**Issue by ytang0831** [deeptools/deepTools#1076]
Hi! 
According to the tools introduction, multiBigwigSummary BED-file computes average scores for each gene/region. For example, 20bp region gets score 3, so the region total score should be 20*3=60? I don't know if my understanding is correct.

While I find the answer in #https://github.com/deeptools/deepTools/issues/505#issuecomment-292733819 #
"There's no region size-based normalization done by default. You'll need to post-process your output.
"

So it's confusing to me, what does average score mean here？

**Comment by dpryan79** [comment]
Yes, if the score is 3 and their are 20 bases then the sum of the per-base values for the region is 3*20 = 60.

**Comment by dpryan79** [comment]
My comment in #505 was indeed a bit confusing and best ignored for your question.

**Comment by ytang0831** [comment]
> Yes, if the score is 3 and there are 20 bases then the sum of the per-base values for the region is 3*20 = 60.

Thanks a lot！ I will close the question.
