### ISSUE TITLE
The width of profile plot differs from that of the heatmap for multiple sample matrix 

### ISSUE THREAD

**Issue by juheon** [deeptools/deepTools#1077]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [X] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.
   None
 - [X] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.
   deeptools 3.3.1
 - [X] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).
`plotHeatmap --matrixFile combined.matrix.gz -out test.matrix.heatmap.pdf --plotFileFormat pdf --sortRegions no \
        --interpolationMethod nearest --missingDataColor "#D3D3D3" \
        --averageTypeSummaryPlot mean --legendLocation upper-left \
        --colorNumber 100 \
        --colorList "#FFFFFF,#000099" "#FFFFFF,#ff8c00" \
        --zMin 0 0 \
        --zMax 2000 1 \
        --yMin 0 0 \
        --yMax 2000 1`
 - [X] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).
[test.matrix.heatmap.pdf](https://github.com/deeptools/deepTools/files/6728086/test.matrix.heatmap.pdf)

Hi,

I expect to see the same width of profile plot and heatmap but they are not due to the width of labels. This only occurs when I use a different scale for each sample (H3K4me3, mappability). If I draw the heatmap for each sample, the widths are the same across the profile plot and heatmap but I prefer to draw plots using a combined matrix since I want to put the color bar on the bottom of heatmap. This is because I have 7 samples to show in one figure and having color bars on the left of each heatmap doesn't look good.

Is there any parameter that I can go around this issue?

Best,
Ju Heon Maeng

**Comment by dpryan79** [comment]
There's unfortunately no way to adjust that, you'd need to do that in Illustrator or a similar program.
