### ISSUE TITLE
IndexError: list index out of range similar issues not able figure it out #787 #635

### ISSUE THREAD

**Issue by Hemantcnaik** [deeptools/deepTools#1082]
Hello I found a simililar issue which was stated befor can please help me how can I run the computematrix 
#787 #635 
command which I have run 

deeptools 3.5.1

`
computeMatrix reference-point \
> -p 8 \
> -S *.bw \
> -R Mus_musculus.GRCm38.68.gtf \
> --upstream 5000 \
> --downstream 5000 \
> --skipZeros \
> --nanAfterEnd \
> --outFileName Chip_data.gz
`

 

`Traceback (most recent call last):
  File "/home/.local/bin/computeMatrix", line 14, in <module>
    main(args)
  File "/home/.local/lib/python3.8/site-packages/deeptools/computeMatrix.py", line 421, in main
    hm.computeMatrix(scores_file_list, args.regionsFileName, parameters, blackListFileName=args.blackListFileName, verbose=args.verbose, allArgs=args)
  File "/home/.local/lib/python3.8/site-packages/deeptools/heatmapper.py", line 252, in computeMatrix
    res, labels = mapReduce.mapReduce([score_file_list, parameters],
  File "/home/.local/lib/python3.8/site-packages/deeptools/mapReduce.py", line 85, in mapReduce
    bed_interval_tree = GTF(bedFile, defaultGroup=defaultGroup, transcriptID=transcriptID, exonID=exonID, transcript_id_designator=transcript_id_designator, keepExons=keepExons)
  File "/home/.local/lib/python3.8/site-packages/deeptoolsintervals/parse.py", line 593, in __init__
    self.parseGTF(fp, line)
  File "/home/.local/lib/python3.8/site-packages/deeptoolsintervals/parse.py", line 508, in parseGTF
    self.parseGTFexon(cols)
  File "/home/.local/lib/python3.8/site-packages/deeptoolsintervals/parse.py", line 444, in parseGTFexon
    if name not in self.exons[self.labelIdx]:
IndexError: list index out of range
`

GTF file 

`GL456350.1	protein_coding	exon	993	1059	.	-	.	 gene_id "ENSMUSG00000094121"; transcript_id "ENSMUST00000177695"; exon_number "1"; gene_name "Ccl21c"; gene_biotype "protein_coding"; transcript_name "Ccl21c-201";
GL456350.1	protein_coding	CDS	993	1059	.	-	0	 gene_id "ENSMUSG00000094121"; transcript_id "ENSMUST00000177695"; exon_number "1"; gene_name "Ccl21c"; gene_biotype "protein_coding"; transcript_name "Ccl21c-201"; protein_id "ENSMUSP00000136267";
GL456350.1	protein_coding	start_codon	1057	1059	.	-	0	 gene_id "ENSMUSG00000094121"; transcript_id "ENSMUST00000177695"; exon_number "1"; gene_name "Ccl21c"; gene_biotype "protein_coding"; transcript_name "Ccl21c-201";
GL456350.1	protein_coding	exon	784	904	.	-	.	 gene_id "ENSMUSG00000094121"; transcript_id "ENSMUST00000177695"; exon_number "2"; gene_name "Ccl21c"; gene_biotype "protein_coding"; transcript_name "Ccl21c-201";
GL456350.1	protein_coding	CDS	784	904	.	-	2	 gene_id "ENSMUSG00000094121"; transcript_id "ENSMUST00000177695"; exon_number "2"; gene_name "Ccl21c"; gene_biotype "protein_coding"; transcript_name "Ccl21c-201"; protein_id "ENSMUSP00000136267";
`

Is there any problem with my GTF file

**Comment by dpryan79** [comment]
Your GTF file has no transcript or gene entries, making it an invalid GTF file.
