### ISSUE TITLE
Deeptools plotHeatmap with different scales 

### ISSUE THREAD

**Issue by Lattesnow** [deeptools/deepTools#1083]
Hey,
I am having this issue for several of my ChIP-seq studies. I did RPKM in bamCoverage to get bigwig files and use computeMatrix for the input of plotting. All my input samples should have similar output and heatmap pattern. 
![deeptools q](https://user-images.githubusercontent.com/82230874/128398704-587465bc-e34d-4593-91c9-32ed750645ca.PNG)
However, the column #4 has very different pattern than the first three columns. 

Could you explain why this happened? Is there anyway to correct or further normalize the data?

For my treatment group, I also encountered this problem with different basal level showed in the plot profile map. I think this might related to some sort of normalization issue?
![aaaarrrrr](https://user-images.githubusercontent.com/82230874/128399140-3f51c725-86d9-4d3c-bcb9-781346aa0b3f.PNG)

**Comment by dpryan79** [comment]
You might try 1x normalization instead (a.k.a., RPGC). That will be more likely to be robust between samples.

**Comment by Lattesnow** [comment]
> You might try 1x normalization instead (a.k.a., RPGC). That will be more likely to be robust between samples.

Hey, thanks for the suggestion. I tried RPGC normalization but still get the similar graph. I think the problem is I am having some of the super large peak as the outliers that cause the peak in this heatmap. Is there a good suggestion for setting up an threshold of the max value when process the bigwig file?

**Comment by dpryan79** [comment]
There's no maximum-value option, you'll either need to not include those regions or manually tweak the scaling factor when making the bigWigs.
