### ISSUE TITLE
Confused about visualizing bigwig of IgG samples in IGV

### ISSUE THREAD

**Issue by peaceisking** [deeptools/deepTools#1089]
Hello, I used bamcoverage to generate bigwig format of samples using normalization method of CPM, and then I import them into IGV to visualize.But I found that IgG samples look different from others.Just like below(up: unnormalized IgG 
    down: normalized IgG).
![image](https://user-images.githubusercontent.com/46219838/131864438-4f75ad27-a9b4-42b2-ba6b-2e016302b0c9.png)
But other samples look normal,difference is much fewer,just like below(up: normalized sample         down: unnormalized sample).
![image](https://user-images.githubusercontent.com/46219838/131865131-19c0bddf-23df-4b66-84fa-2ca7da4a8ae9.png)

 I thought it is because IgG has small amount of reads, so after CPM normalization, the height will become higher.
 But I am confused how can I make IgG and other samples together into one figure. 
 Becouse if use the same CPM normalization,IgG seems to look like have a mush stronger signal……
     Thank you very much!

**Comment by dpryan79** [comment]
I recommend subtracting IgG from your ChIP signal, rather than showing it. IgG is generally going to have a very weird and choppy profile where the take-home message is, "it doesn't show any obvious enrichment". This is among the reason input is usually sequenced rather than IgG.
