### ISSUE TITLE
Feature request: region labels for computeMatrix

### ISSUE THREAD

**Issue by niekwit** [deeptools/deepTools#1095]
With `computeMatrix` it is possible to rename the samples with the `--samplesLabel`, which is very handy. Is it possible to do the same or introduce this feature for the regions specified with the  `--regionsFileName` flag?

**Comment by dpryan79** [comment]
Normally you would do this when plotting (e.g., `plotHeatmap --regionsLabel customLabel1 customLabel2 ...`).
