### ISSUE TITLE
computeMatrix error

### ISSUE THREAD

**Issue by ryrl9703** [deeptools/deepTools#1101]
When I use deeptools' computeMatrix, it always report:
ValueError: invalid literal for int() with base 10: 'NM_001159711.1'

and the code i used is: computeMatrix reference-point --referencePoint TSS -b 3000 -a 10000 -R ../../../Genome/Mouse/Bed/mm39.bed -S ../../alignment/bw_files/ZN-24890_merged.bw  --skipZeros -o ./test.gz --outFileSortedRegions test.bed

how sould I to solve the problem?

**Comment by brianpenghe** [comment]
Did you solve your problem? Could you share?

**Comment by ryrl9703** [comment]
> Did you solve your problem? Could you share?
The bed file should be chr,star,end，not the ‘name’ at the begin。Then I download the bed file as follow:
![微信图片_20220425204520](https://user-images.githubusercontent.com/87462884/165092330-b263a766-a0ea-4050-b88c-5443b67b6662.png)
![微信图片_20220425204813](https://user-images.githubusercontent.com/87462884/165092353-67e7e750-a338-45d5-ad3a-d30dec9e54c1.png)

**Comment by francat** [comment]
What did you use as your effective genome size when making your bigWig files? (bamCoverage command)
