### ISSUE TITLE
No signal in regions over 530M on chromosome

### ISSUE THREAD

**Issue by HeChao7021** [deeptools/deepTools#1103]
![image](https://user-images.githubusercontent.com/71759220/139630494-f9caaaad-cfd5-437f-a7a1-65d12f8bfe32.png)
No signal at the end of the chromosome when the length of which higher than 530M. Thank you for your attention.

**Comment by dpryan79** [comment]
That'd odd, what version of deepTools did you use and was the BAM file indexed with a .bai or a .csi file? I think the latter is needed to support longer chromosomes.

**Comment by HeChao7021** [comment]
Thank you for your reply. The deepTools version is 3.3.0 and the BAM file indexed with csi file. I will try the latest version of deeptools. Thank you very much.
















At 2021-11-01 21:51:45, "Devon Ryan" ***@***.***> wrote:

That'd odd, what version of deepTools did you use and was the BAM file indexed with a .bai or a .csi file? I think the latter is needed to support longer chromosomes.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HeChao7021** [comment]
Works well when using the latest version of deepTools
