### ISSUE TITLE
Do not understand the y-axis after bamcoverage

### ISSUE THREAD

**Issue by JihedC** [deeptools/deepTools#1106]
Hi,
Thanks for developing deeptools, I have been using it so much in the past months! I have a question concerning the values I get for coverage after `bamcoverage`.

I am currently mapping ATAC-seq reads to contigs I have generated from a new _de novo_ assembly. I have made a gene annotation.

I have generated bigwig files with this command:

`bamCoverage -b <bam> --binSize 20 --normalizeUsing RPKM --smoothLength 50 -o <bigiwig>

I used the RPKM normalization and I am surprised by how high the value of the y-axis are. The maximum goes to 500 at the gene promoter. But If I look at the bam file on IGV,  the same promoter shows maximum 40 reads piling up. I get the same results when I map the same atac seq data to the reference genome (see image below).

So my question is: Why do I get such a strong value for the y-axis read coverage after `bamcoverage` while the bam file shows that I don't have so many reads at the promoter?

Thanks in advance for your help!

![](file:///home/jchouaref/LUMCNET/HumGen/I/lab-f/Jihed/PACBIO_FVBNJ/docs/Screenshot%20from%202021-11-25%2014-33-48.png)

**Comment by dpryan79** [comment]
It may be that you don't have a lot of mapped reads. Basically this comes down to how the scaling factor is calculated:

```
 million_reads_mapped = float(bam_mapped) / 1e6
 tile_len_in_kb = float(args.binSize) / 1000

scale_factor *= 1.0 / (million_reads_mapped * tile_len_in_kb)
```

That value is then multiplied by the number of reads in each bin. So if you have relatively few mapped reads or your bin size is small then you'll get bigger values. In this case I suspect it's the 20 base bin size that's causing this.

**Comment by JihedC** [comment]
Thanks for the reply.
Shall I enforce a scaling factor or increase the binsize?
