### ISSUE TITLE
PlotHeatmap colour scale producing plots from black:colour instead of white:colour

### ISSUE THREAD

**Issue by cmonger** [deeptools/deepTools#1112]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [ ] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

 - [ ] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.

 - [ ] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).

 - [ ] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).

Unsure why this is happening as the scale bars at the bottom of the plot are correctly going from white:chosen colour but black lines are generated on the heatmaps. I've tried this on two computers, one of which has a fresh install of conda, all the dependancies and deeptools but get the same result. No error messages are produced.

Version:3.5.1
py version: 3.9.5

Command:

plotHeatmap -m mergedAvPlots/data/activeEnhancers -out mergedAvPlots/plots/activeEnhancers_heatmap.pdf --heatmapHeight 7.24679991  --refPointLabel Peak  --plotTitle 'Enhancers'  --plotFileFormat pdf --colorList  "#ffffff","#fa7814" "#ffffff","#fc0000" "#ffffff","#41b400" "#ffffff","#e1a000" "#ffffff","#008f05" "#ffffff","#96dc32" "#ffffff","#e15a00" "#ffffff","grey"

![image](https://user-images.githubusercontent.com/5954982/145802082-04ecdb16-6ba0-4c97-97ad-751ffed18201.png)

**Comment by LeilyR** [comment]
they could be missing data, the default color for them plotheatmap is black, unless you set them to zero in computeMatrix

**Comment by cmonger** [comment]
Brilliant thanks. Fixed by including  --missingDataAsZero in compute matrix. Apologies for submitting user error as an issue.
