### ISSUE TITLE
Strange Y-axis for DNA methylation in plotHeatmap

### ISSUE THREAD

**Issue by kyliuae** [deeptools/deepTools#1113]
Hi everyone and admin for deeptools,

Below are the basic information, question is stated after all these, thank you!

**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [ ] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

**(Maybe) #972**

 - [ ] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.

**deeptools 3.5.1**

 - [ ] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).

1. way of generating bigwig file:

1.1: generating bedGraph from bismark_methylation_extractor
1.2: generating bigwig file using following code:

`awk '{if(NR>1) print }' *.bedGraph | /xxxxx/GNU-coreutils-8.25/bin/sort -k1,1 -k2,2n --parallel=24  > bdg.temp
        time /xxxx/bedGraphToBigWig bdg.temp /xxx_Annotation/hg38.chrom.size $line.CpG.bw`

2. plotting using deeptools

`computeMatrix scale-regions -S /$DIRECTORY/METHYLATION.bw -R /$DIRECTORY/TARGET_REGION.bed -o METHYLATION_matrix.gz -m 224000 --startLabel xxx_s --endLabel xxx_e -b 50000 -a 50000 --missingDataAsZero --skipZeros -p 24 -bs 1000`

`plotHeatmap -m METHYLATION_matrix.gz -out METHYLATION_heatmap.png --colorMap YlGnBu --heatmapHeight 15 --plotTitle 'xxx' --regionsLabel 'xxx'`

 - [ ] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).

![image](https://user-images.githubusercontent.com/89119561/147534956-8896f7de-8fe4-4625-84cd-92b588c450c0.png)
![image](https://user-images.githubusercontent.com/89119561/147532737-a8c98201-5249-475a-9855-b591814adea7.png)
![image](https://user-images.githubusercontent.com/89119561/147533078-6ef9f9d8-0504-48fe-83ac-8f576fc980b9.png)

********************************************************************************************************************************************************************************************************************************************************************

Hi everyone and admin for deeptools,

Recently i have an issue on generating plot from deeptools, i was trying to look at the methylation level for certain regions, since they are of different lengths, i calculated the average length of them and used that number for deeptools using the **_scale-regions_** option. 

However, although the bedgraph file is fine and in UCSC genome browser i can see the y-axis was fine with methylation level from 0-100 for the bigwig file. The y-axis in the deeptools plot generated from it did not show in the same way as the bigwig file (even if interpreted as methylation ratio is not correct as it exceed 1 in y-axis of the plot and tbh i cannot interpret in this way).

I do not know what happen for this issue because it was quite similar from the example in the gallery in the deeptools website as well. Please let me know if you need more information and thank you!

Best Regards,
David

**Comment by dpryan79** [comment]
Are you using the `--missingDataAsZero` option? From the image it seems so but you really don't want that with methlyation data, since it will drastically bias values toward 0 in a biologically incorrect way for this type of data.

**Comment by kyliuae** [comment]
Yea, you are right that's my original code below, i will try to fix it. Thank you.
`computeMatrix scale-regions -S /$DIRECTORY/METHYLATION.bw -R /$DIRECTORY/TARGET_REGION.bed -o METHYLATION_matrix.gz -m 224000 --startLabel xxx_s --endLabel xxx_e -b 50000 -a 50000 --missingDataAsZero --skipZeros -p 24 -bs 1000`
