### ISSUE TITLE
What is the difference between "--transcriptID "  and "--exonID"  in multiBigwigSummary ?

### ISSUE THREAD

**Issue by CTLife** [deeptools/deepTools#1115]
Both of the two parametars are used to filter rows based on the 3rd column, so What is the difference?

**Comment by dpryan79** [comment]
--transcriptID is used to determine which rows give transcript coordinates and --exonID is used to determine which rows give exon coordinates. This is mostly relevant for GFF files, where sometimes people use weird feature names.

**Comment by CTLife** [comment]
thanks.
