### ISSUE TITLE
Multi-threading when saving files

### ISSUE THREAD

**Issue by adRn-s** [deeptools/deepTools#1121]
Every line of code where `numpy.savez_compressed` is used, there might be room for improvement. For example, here: https://github.com/deeptools/deepTools/blob/9308cb7fc910dba348d48fd0dce77a90264b7bdb/deeptools/multiBamSummary.py#L263

Multicore compression is feasible nowadays, and that gives a near linear speedup in respect to number of cores.

I have found that `numpy.savez_compressed` is compatible with python 'threading' module. There is not much info at the official documentation. But, here are some of the library built-in tests: https://github.com/numpy/numpy/blob/main/numpy/lib/tests/test_io.py#L245 that implement this already.

**Comment by dpryan79** [comment]
That appears to be testing writing of multiple files in parallel, not parallel writing of a single file, which is generally not a thing supported because it's IO bound.

**Comment by adRn-s** [comment]
That also explains why I wasn't able to see anything in the documentation! 🙉 Thanks.
