### ISSUE TITLE
Bigwig has peaks but no alignments in the bam?

### ISSUE THREAD

**Issue by hchetia** [deeptools/deepTools#1122]
Why do you think would a bigwig have a coverage peak in the upstream promoter region (before start codon) but the bam wouldn't show any corresponding alignments in the region?
The bigwig was generated from the bam file using deeptools (bamCoverage --effectiveGenomeSize 2913022398 --normalizeUsing RPKM)
Kindly correct me if this is not a relevant issue for deeptools.
![image](https://user-images.githubusercontent.com/64626735/155222858-e001d33c-0adb-4759-944b-15b2dc817daf.png)

**Comment by dpryan79** [comment]
That's due to the bin size you're using. If you want to see exact edges of coverage then use a bin size of 1, or perhaps just a more reasonable value like 10 for your data set.

**Comment by hchetia** [comment]
Resolved. Thanks @dpryan79 .
