### ISSUE TITLE
Negative scientific notations not recognized by plotHeatmap scales

### ISSUE THREAD

**Issue by joncahn** [deeptools/deepTools#1125]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [x] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

 - [x] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.

deeptools 3.5.0
Python 3.8.3

 - [x] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).

plotHeatmap -m combined/matrix/sorted_regions.gz -out combined/plots/test.pdf --sortRegions keep --colorMap 'seismic' --interpolationMethod 'bilinear' --yMin -1.06275e-01 --yMax 1 --zMin 0 --zMax 1

 - [x] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).

plotHeatmap: error: argument --yMin: expected at least one argument

Hi,
It seems that negative numbers in scientific notation are not recognized by plotHeatmap --yMin. Positive numbers are fine since the exact same command with --yMin 1.06275e-01 works, and negative numbers are also fine (-0.10625 works), just not negative scientific numbers. The same error occurs with yMax, zMin and zMax.
Is there a quick way to fix that?

Thank you very much for this beautiful set of tools, they're amazing!

**Comment by dpryan79** [comment]
What happens if you put the value in quotes?

**Comment by joncahn** [comment]
It also does not work

**Comment by dpryan79** [comment]
OK, this is an issue with python rather than deepTools. Apparently you have to add a space so the parser doesn't think -1.06275e-01 is a command line flag: `" -1.06275e-01"`.

**Comment by joncahn** [comment]
Ok, thanks for looking it up. I'm doing something else, converting to decimal before feeding the value
