### ISSUE TITLE
peek called by deeptools is different from MACS2

### ISSUE THREAD

**Issue by hyjforesight** [deeptools/deepTools#1132]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [Y] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

 - [Y] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.
deeptools 3.5.1, Python 3.8.10

 - [Y] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).
```linux
# mm10 paired end ATAC-seq data
bamCoverage -b /mnt/d/HYJ/shifted_postQC_sorted.bam -o /home/hyjforesight/bigWig/after_deeptools.bw -of bigwig -bs 50 -p 16 --effectiveGenomeSize 2494787188 --normalizeUsing RPGC
```
 - [Y] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).

Hello Deeptools,
Thanks for developing this amazing package!
I used the same sorted and shifted bam file to generate bigWig by MACS2 and deeptools.

For MACS2, I called peaks by below code and than convert the bedGraph file to bigWig by bedgraphtobigwig UCSC tools.
```linux
macs2 callpeak -t /mnt/d/HYJ/shifted_postQC_sorted.bam -f BAMPE -g mm --keep-dup all --outdir /home/hyjforesight/MACS2_outputs/ --name after_MACS2 -B --trackline -q 0.05 --cutoff-analysis > /home/hyjforesight/MACS2_outputs/macs2.log
```

For deeptools,  I did
```linux
bamCoverage -b /mnt/d/HYJ/shifted_postQC_sorted.bam -o /home/hyjforesight/bigWig/after_deeptools.bw -of bigwig -bs 50 -p 16 --effectiveGenomeSize 2494787188 --normalizeUsing RPGC
```

I found their peaks are a little bit different and a more significant difference is that peaks from MACS2 has lower value (0-7) than deeptools (0-17). What causes these differences and which bigWig shall I rely on?
![image](https://user-images.githubusercontent.com/75048821/160527995-7fce03ee-7a83-4292-b51e-3149b2a5af3c.png)

Thanks!
Best,
YJ

**Comment by LeilyR** [comment]
I do not think this is a right comparison. What one can expect is to see that peaks match where there are high coverage on the bamCoverage track.
bamCoverage generate coverage track based on the reads falling in each bin, however MACS2 looks for peaks i.e. the regions that not only highly covered but also are significantly different from their surrounding regions.  I am not sure about the value which was in the bedgraph you used to generate the MACS2 but that could be raw count as opposed to RPGC or anything else that explain the difference in the value ranges. 
To me a better practice would be comparing the peaks bed files from MACS2 with the bamCoverage result in case you want to check how the peak calling work.

**Comment by dpryan79** [comment]
The main difference is the bin size. As @LeilyR mentioned, the scaling difference is due to differences in normalization.
