### ISSUE TITLE
use computeMatrix to obtain read count matrix for ChipSeq peaks?

### ISSUE THREAD

**Issue by liuweihanty** [deeptools/deepTools#1134]
Hi, thank you for developing deep tool! My goal is to obtain a count matrix for a chip-seq experiment TF binding peaks. I used bamCompare to calculate the average of my two TF replicate bam files(using RPKM), and I then want to use computeMatrix to calculate the count matrix used for plotting. I'd like to sum all the columns of this matrix and obtain the total number of reads falling onto each peak. Is this the correct way to get the read counts for ChiP seq peaks? and if so, should I use scale region or reference point parameter for computeMatrix? thank you very much!

**Comment by LeilyR** [comment]
you can use `multiBamSummary BED-file` giving your peak file with `--BED`

**Comment by liuweihanty** [comment]
thank you!
