### ISSUE TITLE
plotProfile thingy

### ISSUE THREAD

**Issue by yussufhajjaj** [deeptools/deepTools#1156]
Hello!

I was trying to make a plot like this one
![example](https://user-images.githubusercontent.com/80690849/187937620-6248289f-a6f8-448b-a8c5-c34659ca150e.JPG)

I don't know how to make it look like a TSS and TES, but using a costume interval start and end. I created a gtf look alike file but it didn't work, the only plot that I was successful in making was this, using the center as reference point

![profile-Super-Enhancers-shGFPvsshZEB1](https://user-images.githubusercontent.com/80690849/187938228-e5051063-9d99-4b74-b94b-a44785135450.png)

Don't mind the labelling!

Anyone can help me with that? Thanks in advance.

Best, 

Yussuf

**Comment by yussufhajjaj** [comment]
Other examples

![example11](https://user-images.githubusercontent.com/80690849/187939186-2df9db84-80b0-458a-9b6a-73d7bfc0d1b3.JPG)

**Comment by yussufhajjaj** [comment]
Sorry if I caused any confusion.

That's one thing, I want them in the same plot. But the other thing is, I don't want the signal to be "centered" on the interval "center", but rather to span the start to the end of the interval, similar to "TSS to TES".

**Comment by LeilyR** [comment]
If you make scale region matrices then you can specify start and end label. The other option you may need is perGroup to plot all samples of a group together in one plot.

**Comment by adRn-s** [comment]
Ok, for the first part, you'd need to compute the matrix with the several bed/ gtf files together. Like this `--regionsFileName file1.gtf file2.gtf`

**Comment by yussufhajjaj** [comment]
> If you make scale region matrices then you can specify start and end label (`--startLabel` & `--endLabel`). The other option you may need is `--perGroup` to plot all samples of a group together in one plot.

I get this error message with scale regions: 
raise RuntimeError('{0} does not seem to be a recognized file type!'.format(self.filename)

And this is the head of the file, normal bed3
![bedfilehead](https://user-images.githubusercontent.com/80690849/188096681-dc9b3d5e-f8ae-47e9-ac0a-a7a4ae82291d.JPG)

this is the command: 

computeMatrix scale-regions \
-S x1.bw x2.bw \
-R bed3.bed \
--beforeRegionStartLength 2000 \
--afterRegionStartLength 2000 \
--skipZeros \
-o mx-SE.mat.gz \
--numberOfProcessors max \

**Comment by LeilyR** [comment]
check if you bed file is correctly formated, be sure it is tab separated. 
I assume the new lines in your command line are just for making it easier to read, if not you need to use \ at the end of each line

**Comment by yussufhajjaj** [comment]
> check if you bed file is correctly formated, be sure it is tab separated. I assume the new lines in your command line are just for making it easier to read, if not you need to use \ at the end of each line

It worked! and yes it was a tab separation problem, when I used awk to remove the extra columns it somehow lost the format, thanks alot!!
