### ISSUE TITLE
Tools fail with 'Symbol not found: _llvm.abs.i16'

### ISSUE THREAD

**Issue by MarekGierlinski** [deeptools/deepTools#1157]
I have installed *deepTools* using `pip install deeptools` with no issues on Mac OS 10.15.7. However, a call to any of the tools (e.g. *bamCoverage*), with or without parameters, results in error `Symbol not found: _llvm.abs.i16`. I did check all the requirements (as described in your installation instructions) and they are fine.

If this helps, I first tried to install *deepTools* with Conda and it failed

```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

And that's it, no more information. After that `pip` installed with no problems.

---

 - [x] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

 - [x] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.

```
deeptools 3.5.1
Python 3.8.5
```

 - [x] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).

```
bamCoverage -h
```

 - [x] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).

```
Traceback (most recent call last):
  File "/Users/mgierlinski/opt/miniconda3/bin/bamCoverage", line 5, in <module>
    from deeptools.bamCoverage import main
  File "/Users/mgierlinski/opt/miniconda3/lib/python3.8/site-packages/deeptools/bamCoverage.py", line 8, in <module>
    from deeptools import writeBedGraph  # This should be made directly into a bigWig
  File "/Users/mgierlinski/opt/miniconda3/lib/python3.8/site-packages/deeptools/writeBedGraph.py", line 5, in <module>
    import pyBigWig
ImportError: dlopen(/Users/mgierlinski/opt/miniconda3/lib/python3.8/site-packages/pyBigWig.cpython-38-darwin.so, 2): Symbol not found: _llvm.abs.i16
  Referenced from: /Users/mgierlinski/opt/miniconda3/lib/python3.8/site-packages/pyBigWig.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/mgierlinski/opt/miniconda3/lib/python3.8/site-packages/pyBigWig.cpython-38-darwin.so
```

**Comment by adRn-s** [comment]
I understand this as an issue with installing via conda. After running some test(s), I could reproduce the problem. Now I see that `conda install -c bioconda -c conda-forge deeptools` works. The fix is adding conda-forge channel of packages explicitly, which is in itself a requirement to succesfully using the bioconda channel.

**Comment by MarekGierlinski** [comment]
Thank you for your quick response. Indeed, adding `conda-forge` fixed the problem. It might be worth updating the [installation documentation](https://deeptools.readthedocs.io/en/develop/content/installation.html).
