### ISSUE TITLE
issues related to plotCorrelation

### ISSUE THREAD

**Issue by ccmeth** [deeptools/deepTools#1159]
Hi,
Thanks a lot for providing such a powerful tool for data analysis. However, after multibigwigsummary and plotcorrelation, I noticed that the figures generated was a little strange. The line does not correspond to the sample accurately. Could you please provide any suggestions?
deeptools version: 3.5.1
python version: 3.8.10

![ATAC_heatmap_SpearmanCorr_bw](https://user-images.githubusercontent.com/54224100/190317116-1f6e95fc-cf6d-46a1-ab5a-ae1b34ff11ba.png)

**Comment by adRn-s** [comment]
Please clarify, which line do you mean? The bordeaux 'tree' on the left is a hierarchical clustering based on this Spearman correlation values.

**Comment by ccmeth** [comment]
> Please clarify, which line do you mean? The bordeaux 'tree' on the left is a hierarchical clustering based on this Spearman correlation values.

Sorry, the line means the "tree line", which does not always point to the center.

**Comment by adRn-s** [comment]
Ah, now I see it. Thanks! I believe I have found the source of the problem... we'll let you know as soon as we push a fix.

**Comment by ccmeth** [comment]
> Ah, now I see it. Thanks! I believe I have found the source of the problem... we'll let you know as soon as we push a fix.

Thanks for your timely reply!

**Comment by adRn-s** [comment]
the latest code on develop branch has this update in place.
