### ISSUE TITLE
How can I set `plotheatmap` to different colors for different `.bed` file regions?

### ISSUE THREAD

**Issue by danli349** [deeptools/deepTools#1166]
How can I set `plotheatmap` to different colors for different `.bed` file regions?

I want to set the up panel as `'white,red'` and the lower panel as `'white,blue'`.
![image](https://user-images.githubusercontent.com/33963919/193597877-d14d88a9-d626-44e7-8a93-5427dfeef50e.png)

and how can I change the color of the intensity curve to red and blue?

![image](https://user-images.githubusercontent.com/33963919/193630640-e3b4d5f9-517a-49a6-9925-c255501cf53a.png)

Thanks

**Comment by dpryan79** [comment]
Give multiple values to `--colorList`, such as `--colorList “white,red” “white,blue”`. Note the space between the values for separate heatmaps. The same concept applies to `plotProfile` `--colors` option.

**Comment by danli349** [comment]
@dpryan79 
I tried --colorList “white,red” “white,blue”,
But it will change color of different samples, not different regions.

![image](https://user-images.githubusercontent.com/33963919/193669294-271bb5f9-82ab-40f6-88f3-dd0ac429438a.png)

**Comment by dpryan79** [comment]
Ah, yeah we don't support per-region heat maps. You might want to plot them separately and then merge the images into the same figure.

**Comment by danli349** [comment]
@dpryan79 
How can I change the color of the intensity curve?

![image](https://user-images.githubusercontent.com/33963919/193630640-e3b4d5f9-517a-49a6-9925-c255501cf53a.png)

**Comment by dpryan79** [comment]
`--colors`. That plot has multiple samples merged together I believe.

**Comment by niekwit** [comment]
I have created a PR that allows to set the colours for the profile plot: https://github.com/deeptools/deepTools/pull/1427.
