### ISSUE TITLE
consider migrating to contemporary test framework

### ISSUE THREAD

**Issue by emollier** [deeptools/deepTools#1178]
Greetings,

For information, due to nosetests being unmaintained for a while, the Debian project is in the process to phase out nose.  This has caused the opening of [Debian bug#1018477] affecting the python3-deeptools package.  I'm devising on a [patch to move to pytest], but I think it would be saner that I don't break the test suite by accident and you be aware of the change.  I have not proposed a merge request as I'm not too comfortable with the changes involved in the test infrastructure on your side, but feel free to use the patch as is and make all the adjustments you see fit.

This is not critical yet, mostly a wishlist item.

Have a nice day,  :)
Étienne.

[Debian bug#1018477]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1018477
[patch to move to pytest]: https://salsa.debian.org/med-team/python-deeptools/-/blob/master/debian/patches/pytest.patch

**Comment by WardDeb** [comment]
Hi Étienne,

Thanks for the pointer!
nose has been deprecated from 3.5.3 onwards in favor of pytests.

Kind regards,

WardDeb
