### ISSUE TITLE
Cannot print plotCorrelation due to the wrong value in call function set_rotation from matplotlib

### ISSUE THREAD

**Issue by aletomczak** [deeptools/deepTools#1183]
Hi, I have encountered a problem while executing command:

`plotCorrelation --corData deeptools_analysis/bamSummaryOutput --corMethod pearson --whatToPlot scatterplot --plotFile scatter_limited_pearson.png`

Outliers were detected in the data. Consider using the --removeOutliers parameter to avoid a bias in the pearson correlation.

```
Traceback (most recent call last):
File "/.../bin/plotCorrelation", line 12, in <module>
main(args)
File "/.../python3.10/site-packages/deeptools/plotCorrelation.py", line 239, in main
corr.plot_scatter(args.plotFile,
File "/////python3.10/site-packages/deeptools/correlation.py", line 507, in plot_scatter
tick.label.set_rotation('45')
File "/.../python3.10/site-packages/matplotlib/text.py", line 1196, in set_rotation
raise ValueError("rotation must be 'vertical', 'horizontal' or "
ValueError: rotation must be 'vertical', 'horizontal' or a number, not 45
```
==================================================
Problem can be repaired by changing the value str '45' for int 45 in /.../deeptools/correlation.py

 - deeptools 3.5.1
 - python 3.10.8
 - matplotlib-base 3.6.2 

Best regards, Ola

**Comment by li1311139481** [comment]
I'm sorry, I was installed with conda deeptools, I found the correlation.py.  
i change 
`axmatrix.set_xticklabels(np.array(self.labels).astype('str')[index], rotation=45, ha='left')`
to
`axmatrix.set_xticklabels(np.array(self.labels).astype('int')[index], rotation=45, ha='left')`
or to
`axmatrix.set_xticklabels(np.array(self.labels).astype('int')[index], rotation='45', ha='left')`
They don't work, could you tell me should how to fix it ？
Or should I download the source package and manually install after fix this problem?

**Comment by li1311139481** [comment]
i solved it 
it should change all `tick.label.set_rotation('45')`  for  `tick.label.set_rotation(45)` 
Note there are two ('45'), need replace all
