### ISSUE TITLE
How to customize the Profile values of `plotHeatmap` of `deeptools`?

### ISSUE THREAD

**Issue by danli349** [deeptools/deepTools#1187]
Hi:

How can I customize the Profile values of `plotHeatmap` of `deeptools`?
I want to multiply 1.5 to all of the values.

![image](https://user-images.githubusercontent.com/33963919/213786822-0462aee4-12ec-413b-8d19-ebae6cbdabb7.png)

Thanks a lot.

**Comment by adRn-s** [comment]
You may achieve this by either changing the binSize during computeMatrix, or maybe something like this: https://deeptools.readthedocs.io/en/develop/content/tools/computeMatrix.html#scale-regions
