### ISSUE TITLE
Can I plot multiple plots without sharing y axis in plotProfile?

### ISSUE THREAD

**Issue by MyBiscuit** [deeptools/deepTools#1190]
When I am plotting multiple plots with plotProfile (in this example, same sample across different ranges), the y axis automatically scales so that some profiles look flattened. Example:
<img width="876" alt="image" src="https://user-images.githubusercontent.com/85445902/217408956-e69ccc09-feb8-4a1b-87bf-9d4022fbff9f.png">

This is how these profiles look like when plotted separately:
<img width="974" alt="image" src="https://user-images.githubusercontent.com/85445902/217409025-e871f8c7-b74f-4681-a27a-89fce8b01348.png">

Compare plots for HiCExplorer and HiTAD between the two figures.
Is there a way to plot several profiles while retaining individual y axes?

**Comment by adRn-s** [comment]
Both `--yMax` and `--yMin`  accept **multiple values, separated by spaces** to set for each profile. 

https://deeptools.readthedocs.io/en/develop/content/tools/plotProfile.html

**Comment by Oliverfeudj** [comment]
Hello @adRn-s @dpryan79  is it possible to take advantage of both please? like setting only the yMax and not the yMin (I tried and it did not work maybe there is a workaround) and making them share the same legend since `--legendLocation  none` doesn't not actually work

Thank you for any help
