### ISSUE TITLE
How to make the profile line more smooth?

### ISSUE THREAD

**Issue by danli349** [deeptools/deepTools#1221]
Why the profile line has so many wiggles? 
How to make the profile line more smooth?
I assume there are some peaks in the `.bed` file that are highly repeated, how can I delete those peaks?
Thanks a lot
```
computeMatrix reference-point --referencePoint center -b 1000 -a 1000 \
--missingDataAsZero \
-bl /lila/data/chen/dan/ref/ENCODE_Blacklist/hg19-blacklist.v1_nochr.bed \
-R readcounts/peaks_enhancer/up.bed \
-S bigwigRPGC/*.bw \
-p 12 \
-o plotHeatmap/DMSO.gz \
--outFileNameMatrix plotHeatmap/DMSO.tab


plotHeatmap  -m plotHeatmap/DMSO.gz \
-out plotHeatmap/DMSO.pdf \
--outFileSortedRegions plotHeatmap/DMSO.bed \
--regionsLabel "up" \
--missingDataColor white \
--dpi 300 \
--colorList 'white,magenta' \
--samplesLabel "DMSO1" "DMSO2" \
"100nM-1" "100nM-2" \
"10nM-1" "10nM-2" \
--yMin 0 \
--zMin 0
```

![image](https://github.com/deeptools/deepTools/assets/33963919/5f1d17bd-6a23-42e3-93ec-1078c73970e5)

**Comment by Ruismart** [comment]
I think the simple way is to output the data matrix using for this plot, then replot in R with some regression method in different scales

**Comment by danli349** [comment]
@Ruismart Thanks for the suggestion. I think the wiggles are caused by the several top rows in the heatmap, How can I find these top row peaks in the `bed` file? I can delete them from the `bed` file.
Thanks

![image](https://github.com/deeptools/deepTools/assets/33963919/a46d7f41-a83b-40ce-80be-6792748dfb2c)

**Comment by danli349** [comment]
@Ruismart Yes. Thanks a lot

**Comment by danli349** [comment]
@Ruismart I deleted the top 6 rows from the `bed` file, the heatmap looks much better, thanks

![image](https://github.com/deeptools/deepTools/assets/33963919/72e3d562-2a04-48dd-a51a-cb4048ea646a)
