### ISSUE TITLE
bamCoverage: error: unrecognized arguments: RPKM --effectiveGenomeSize 2913022398

### ISSUE THREAD

**Issue by jiangshan529** [deeptools/deepTools#1236]
Hi, dear all. I am using bamCoverage to process a chip-seq file from bam to bw. However, I encountered such an error message: bamCoverage: error: unrecognized arguments: RPKM --effectiveGenomeSize 2913022398. By checking many times, there's no typo on it. Could you please help me to solve this? Thanks!

**Comment by jiangshan529** [comment]
> Hi, dear all. I am using bamCoverage to process a chip-seq file from bam to bw. However, I encountered such an error message: bamCoverage: error: unrecognized arguments: RPKM --effectiveGenomeSize 2913022398. By checking many times, there's no typo on it. Could you please help me to solve this? Thanks!

it's very surprising to find that ''--normalizeUsingRPKM" instead of adding a blank in between "--normalizeUsing RPKM" works out!

**Comment by WardDeb** [comment]
Hi,

Could you double check that there is no mistake in dashes ('-') prior to the --normalizeUsing argument ? 
This does look like a typo (and I can't reproduce this locally). If the error persists, feel free to re-open and share the full command.

Kind regards,

WardDeb

**Comment by jiangshan529** [comment]
> Hi,
> 
> Could you double check that there is no mistake in dashes ('-') prior to the --normalizeUsing argument ? This does look like a typo (and I can't reproduce this locally). If the error persists, feel free to re-open and share the full command.
> 
> Kind regards,
> 
> WardDeb

Hi, it's very surprising to find that ''--normalizeUsingRPKM" instead of adding a blank in between "--normalizeUsing RPKM" works out! But the --effectiveGenomeSize still does not work.


bamCoverage --bam SRR2562331_sort.bam -o th17_mm10_SMC3.bw --binSize 25 --smoothLength 75 --numberOfProcessors 8 --normalizeUsingRPKM --effectiveGenomeSize 2652783500 --centerReads --extendReads --ignoreForNormalization chrM
usage: An example usage is:$ bamCoverage -b reads.bam -o coverage.bw
bamCoverage: error: unrecognized arguments: --effectiveGenomeSize 2652783500

**Comment by WardDeb** [comment]
Hi,
You need a space between --normalizeUsing and RPKM:
`bamCoverage --bam SRR2562331_sort.bam -o th17_mm10_SMC3.bw --binSize 25 --smoothLength 75 --numberOfProcessors 8 --normalizeUsing RPKM --effectiveGenomeSize 2652783500 --centerReads --extendReads --ignoreForNormalization chrM`
should work

**Comment by jiangshan529** [comment]
> --effectiveGenomeSize 2652783500

No, when I add a space, the code does not work.

bamCoverage --bam SRR2562331_sort.bam -o th17_mm10_SMC3.bw --binSize 25 --smoothLength 75 --numberOfProcessors 8 --normalizeUsing RPKM --effectiveGenomeSize 2652783500 --centerReads --extendReads 50 --ignoreForNormalization chrM
usage: An example usage is:$ bamCoverage -b reads.bam -o coverage.bw
bamCoverage: error: unrecognized arguments: RPKM --effectiveGenomeSize 2652783500

**Comment by WardDeb** [comment]
I cannot reproduce this, even with direct copy paste (and only changing the bamfile name). What version of deeptools are you using ?

**Comment by jiangshan529** [comment]
> I cannot reproduce this, even with direct copy paste (and only changing the bamfile name). What version of deeptools are you using ?

I see, it's a version problem. In 2.5.7 I have the problem. but in 3 there's not.

**Comment by jiangshan529** [comment]
> > I cannot reproduce this, even with direct copy paste (and only changing the bamfile name). What version of deeptools are you using ?
> 
> I see, it's a version problem. In 2.5.7 I have the problem. but in 3 there's not.

Hi, I have another question. After using Normalizing by RPKM with effective genome size, the heatmap scale is very different between two samples(25 fold change). What's actually causing this?(RPKM should normalize the sequencing depth). And how can I scale the second heatmap to the range of 1-10. Thanks!

**Comment by rachadele** [comment]
Does RPKM use `--effectiveGenomeSize` at all ? From the documentation, it seems like a scaling factor is only computed for RPGC normalization.
