### ISSUE TITLE
 plotPCA aligns all samples in one line

### ISSUE THREAD

**Issue by sunta3iouxos** [deeptools/deepTools#1238]
- [ description of the error]
 similar to  #477

 - [ versions]
 deeptools 3.5.1
Python 3.7.12
I used the snakePipes to create the deeptools environment
 - [ the commands used] 
'''
multiBamSummary bins --binSize 1000 --blackListFileName /mnt/c/AP01/mm10-blacklist.v2.bed --ignoreDuplicates -p 8 --bamfiles /mnt/c/AP01/bam/*.bam -out /mnt/c/AP01/bam/deepTools/multiBAM_bin1000.out.npz --outRawCounts /mnt/c/AP01/bam/deepTools/readCounts.tab
'''
'''plotPCA --corData /mnt/c/AP01/bam/deepTools/multiBAM_bin1000.out.npz \
--plotFile /mnt/c/AP01/bam/deepTools/pcaplot2.png \
-T "PCA of read counts" \
--rowCenter \
--outFileNameData /mnt/c/AP01/bam/deepTools/pcaProfile2.tab \
--labels H3K36me3_c1 H3K36me3_c2 H3K36me3_c3 H3K36me3_AA5_1 H3K36me3_AA5_2 H3K36me3_AA5_3 H4K16ac_c1 H4K16ac_c2 H4K16ac_c3 H4K16ac_AA5_1 H4K16ac_AA5_2 H4K16ac_AA5_3
'''

the read counts table produced is:
```
#'chr'	'start'	'end'	'A006200317_201074_S18_L000.bam'	'A006200317_201076_S19_L000.bam'	'A006200317_201078_S20_L000.bam'	'A006200317_201080_S21_L000.bam'	'A006200317_201082_S22_L000.bam'	'A006200317_201084_S23_L000.bam'	'A006200317_201086_S24_L000.bam'	'A006200317_201088_S25_L000.bam'	'A006200317_201090_S26_L000.bam'	'A006200317_201092_S27_L000.bam'	'A006200317_201094_S28_L000.bam'	'A006200317_201096_S29_L000.bam'
chrX	8348200	8349200	0.0	1.0	2.0	0.0	6.0	0.0	11.0	2.0	7.0	11.0	8.0	0.0
chrX	8349200	8350200	0.0	1.0	1.0	0.0	0.0	0.0	4.0	8.0	6.0	4.0	9.0	2.0
chrX	8350200	8351200	0.0	0.0	3.0	1.0	0.0	0.0	10.0	3.0	4.0	1.0	2.0	5.0
```
![pcaplot2](https://github.com/deeptools/deepTools/assets/20404754/f0481b75-47e0-49b5-b9ed-be04d4b80feb)
and just to show that the almost the same is without using the --rowCenter:

![pcaplot](https://github.com/deeptools/deepTools/assets/20404754/cb83adfa-ccd8-4bc3-96ae-d108ed384a29)

**Comment by WardDeb** [comment]
Hi,

Could you try including --transpose to the plotPCA command ?

Kind regards,

WardDeb
