### ISSUE TITLE
How to use bigwigAverage 

### ISSUE THREAD

**Issue by Hemantcnaik** [deeptools/deepTools#1239]
Hi Deeptools community 

I wanted to use bigwigAverage from deeptools which is removed in latest version  why its removed in latest version and any alternative tools?

Thank you

**Comment by WardDeb** [comment]
Hi,

The latest version (and any future ones planned for that matter) have bigwigAverage still included. 
Could you try a 'fresh' install (either through pip / conda) and try again ?

Kind regards,

WardDeb
