### ISSUE TITLE
markers for plotPCA

### ISSUE THREAD

**Issue by maciej-jonczyk** [deeptools/deepTools#1240]
Is there any place where I can find shapes and their alphanumeric (ie. keyboard) representation for markers in `plotPCA` function?

**Comment by WardDeb** [comment]
Hi,
Have a look [here](https://matplotlib.org/stable/api/markers_api.html)
I'll have a look to add this in the docs as well.

Kind regards,

WardDeb

**Comment by maciej-jonczyk** [comment]
Thank you :-)
