### ISSUE TITLE
deepTools issue with deepBlue

### ISSUE THREAD

**Issue by liuweihanty** [deeptools/deepTools#1254]
**Hello, thank you for the amazing deeptool! I'm running a simple ComputeMatrix command on my university HPC:**

computeMatrix reference-point -S $input_path/bigwigs/bamCompare_ENCODE_K562_RUNX1_ChIP.bw \ 
    $input_path/bigwigs/GSM3315718_gfi1b_negwnt3a_k652.bw \ 
				   $input_path/bigwigs/bamCompare_ENCODE_K562_GATA1_ChIP.bw \ 
                                   $input_path/bigwigs/bamCompare_ENCODE_K562_TAL1_ChIP.bw \ 
				   $input_path/bigwigs/bamCompare_ENCODE_K562_LEF1_ChIP.bw \ 
			    -R $input_path/bed/K562_cux1ko_smarca4_shared_MACS_peaks_CUX1_bound.bed $input_path/bed/K562_cux1ko_smarca4_lost_MACS_peaks_CUX1_bound.bed \ 
                            --binSize 50 \ 
                            --beforeRegionStartLength 1500 \ 
 			    --afterRegionStartLength 1500 \ 
				--outFileName hema_TF_CUX1_dep_indep_SMARCA4_sites.mat.gz

**But I got these error msg:**
`
Lmod is automatically replacing "gcc/12.1.0" with "intel/2022.2".

Lmod is automatically replacing "intel/2022.2" with "llvm/14.0.5".

Preloading the following deepBlue files: /gpfs/data/mcnerney-lab/liuweihan/BAF_manuscript/Reviewer_2_comment_2/input/bigwigs/bamCompare_ENCODE_K562_RUNX1_ChIP.bw
Traceback (most recent call last):
  File "/apps/software/llvm-14.0.5/python/3.10.5/bin/computeMatrix", line 14, in <module>
    main(args)
  File "/apps/software/llvm-14.0.5/python/3.10.5/lib/python3.10/site-packages/deeptools/computeMatrix.py", line 412, in main
    res = list(map(db.preloadWrapper, deepBlueFiles))
  File "/apps/software/llvm-14.0.5/python/3.10.5/lib/python3.10/site-packages/deeptools/deepBlue.py", line 114, in preloadWrapper
    res = deepBlue(foo[0], url=args.deepBlueURL, userKey=args.userKey)
  File "/apps/software/llvm-14.0.5/python/3.10.5/lib/python3.10/site-packages/deeptools/deepBlue.py", line 138, in __init__
    experimentID = self.getEID()
  File "/apps/software/llvm-14.0.5/python/3.10.5/lib/python3.10/site-packages/deeptools/deepBlue.py", line 164, in getEID
    (status, resps) = self.server.search(self.sample, "experiments", self.userKey)
  File "/apps/software/llvm-14.0.5/python/3.10.5/lib/python3.10/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/apps/software/llvm-14.0.5/python/3.10.5/lib/python3.10/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/apps/software/llvm-14.0.5/python/3.10.5/lib/python3.10/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/apps/software/llvm-14.0.5/python/3.10.5/lib/python3.10/xmlrpc/client.py", line 1196, in single_request
    raise ProtocolError(
xmlrpc.client.ProtocolError: <ProtocolError for deepblue.mpi-inf.mpg.de/xmlrpc: 503 Service Unavailable>
`

**It seems deepTools is trying to load the file through deepblue and is having trouble with it? But all of my input bigwigs are stored locally on my folder on the HPC, shoudl't computeMatrix just access them directly instead of through deepblue? Thank you veyr much!**

**Comment by WardDeb** [comment]
Hi,

Could you verify that bamCompare_ENCODE_K562_RUNX1_ChIP.bw exists and the path is correctly specified ?

**Comment by yingzhang121** [comment]
I have got the same error message. I suspect the default deepBlue server is done. The DEEP data portal at https://deep.dkfz.de/ is not available.

**Comment by WardDeb** [comment]
the deep portal is indeed down, we'll deprecate the deepBlue functionality in a future release. 
If you encounter these errors when having local files only, though, it implies you have specified the wrong path.

**Comment by zhangfeibird** [comment]
Yes, I have met the same issue.
xmlrpc.client.ProtocolError: <ProtocolError for deepblue.mpi-inf.mpg.de/xmlrpc: 503 Service Unavailable>

**Comment by wenhaochen3** [comment]
> Yes, I have met the same issue.
> 
> Traceback (most recent call last): File "/Users/qhz/anaconda3/bin/computeMatrix", line 8, in sys.exit(main()) ^^^^^^ File "/Users/qhz/anaconda3/lib/python3.11/site-packages/deeptools/computeMatrix.py", line 419, in main res = list(map(db.preloadWrapper, deepBlueFiles)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/qhz/anaconda3/lib/python3.11/site-packages/deeptools/deepBlue.py", line 114, in preloadWrapper res = deepBlue(foo[0], url=args.deepBlueURL, userKey=args.userKey) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/qhz/anaconda3/lib/python3.11/site-packages/deeptools/deepBlue.py", line 138, in **init** experimentID = self.getEID() ^^^^^^^^^^^^^ File "/Users/qhz/anaconda3/lib/python3.11/site-packages/deeptools/deepBlue.py", line 164, in getEID (status, resps) = self.server.search(self.sample, "experiments", self.userKey) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/qhz/anaconda3/lib/python3.11/xmlrpc/client.py", line 1122, in **call** return self.__send(self.__name, args) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/qhz/anaconda3/lib/python3.11/xmlrpc/client.py", line 1464, in __request response = self.__transport.request( ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/qhz/anaconda3/lib/python3.11/xmlrpc/client.py", line 1166, in request return self.single_request(host, handler, request_body, verbose) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/qhz/anaconda3/lib/python3.11/xmlrpc/client.py", line 1196, in single_request raise ProtocolError( xmlrpc.client.ProtocolError: <ProtocolError for deepblue.mpi-inf.mpg.de/xmlrpc: 503 Service Unavailable>

I got a same error,and I have solved it by correcting my input format.

**Comment by confiya** [comment]
I have met the same error，but my input .bw file is Ok, how to solve this question?
thanks!

**Comment by WardDeb** [comment]
Deepblue support is now deprecated in 3.5.5 :)
