### ISSUE TITLE
There is no setup.py file

### ISSUE THREAD

**Issue by bio-Tao** [deeptools/deepTools#1269]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [ ] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

 - [ ] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.

 - [ ] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).

 - [ ] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).
There is no setup.py file

**Comment by myglesia** [comment]
setup.py was removed since it's no longer needed. However the installation instructions in the Readme file weren't updated. 

To install, just run `pip install .` from inside the `deepTools` directory.

**Comment by WardDeb** [comment]
Thanks for the report.
This is updated now in the develop branch, will be taken care of in the main branch soon as well
