### ISSUE TITLE
Current documentation is missing information

### ISSUE THREAD

**Issue by aydemiro** [deeptools/deepTools#1271]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [ ] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

 - [ ] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.

 - [ ] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).

 - [ ] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).

Hi,

The current documentation at https://deeptools.readthedocs.io/en/latest/ is missing much of the documentation that was available before. I can find older documentation [here](https://gensoft.pasteur.fr/docs/deepTools/3.4.1/). Looking at computeMatrix tool documentation, for example, the current documentation is missing every section except Details and Examples sections. I was wondering if this is done on purpose or there is some mistake with the current docs.

Best,
Ozkan

**Comment by WardDeb** [comment]
Thanks for the report !
This should be fixed now with the latest develop version:
[develop docs](https://deeptools.readthedocs.io/en/develop)
In case you spot anything else, please let us know !

Ward
