### ISSUE TITLE
bamCoverage: error: argument --outFileName/-o: xxdir/sss/ddd/bugwig.bw  file can't be opened for writing

### ISSUE THREAD

**Issue by Kiliankleemann** [deeptools/deepTools#1281]
- [x] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.
deeptools 3.5.4
python 3.10.12

 - [x] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).

bamCoverage -b cDNA_ANALYSIS/S1_cDNA/mapping_cDNA_specific/concat_output_ax_splice_cDNA.sorted.bam -o cDNA_ANALYSIS/S1_cDNA/mapping_cDNA_specific/BIGWIG_files/concat_output_ax_splice_cDNA.bw --normalizeUsing RPGC --effectiveGenomeSize 2913022398 --numberOfProcessors 4 --skipNonCoveredRegions --samFlagExclude 16

 - [x] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).
bamCoverage -b cDNA_ANALYSIS/S1_cDNA/mapping_cDNA_specific/concat_output_ax_splice_cDNA.sorted.bam -o cDNA_ANALYSIS/S1_cDNA/mapping_cDNA_specific/BIGWIG_files/concat_output_ax_splice_cDNA.bw --normalizeUsing RPGC --effectiveGenomeSize 2913022398 --numberOfProcessors 4 --skipNonCoveredRegions --samFlagExclude 16

**Comment by WardDeb** [comment]
Your output folder: `cDNA_ANALYSIS/S1_cDNA/mapping_cDNA_specific/BIGWIG_files` doesn't exist would be my first guess. Feel free to re-open if this wasn't the issue.
