### ISSUE TITLE
Effective genome size T2T-CHM13 reference genome

### ISSUE THREAD

**Issue by smsamin** [deeptools/deepTools#1284]
Hi,

I was wondering to ask if its possible to update the effective genome size table (https://deeptools.readthedocs.io/en/develop/content/feature/effectiveGenomeSize.html) for the new human reference genome T2T-CHM13 based on the read length for processed bam files. 
Thanks so much in advance!

**Comment by ecroot** [comment]
I would also find this useful please

**Comment by WardDeb** [comment]
Hi both,

The latest develop version has these tables updated (both for the non-N count as the khmer approximation), main branch will be updated when the other features are ready to implement.
Note that T2T indeed has no N's so for the first method the ESS coincides with the actual genome size.

Feel free to reopen if something is still unclear !

WardDeb
