### ISSUE TITLE
deepTools-3.5.4 :: estimateScaleFactor :: typo

### ISSUE THREAD

**Issue by EricDeveaud** [deeptools/deepTools#1286]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [ ] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.
```
deepTools/3.5.4 > deeptools --version
deeptools 3.5.4
```

```
deepTools/3.5.4 > /opt/gensoft/exe/deepTools/3.5.4/venv/bin/python3 --version
Python 3.8.1
```
 - [ ] Paste the full deepTools command that produces the issue below
```
deepTools/3.5.4 > estimateScaleFactor --bamfiles ../../datas/deepTools/phiX.bam ../../datas/deepTools/phiX.bam --numberOfSamples 1000
Traceback (most recent call last):
  File "/opt/gensoft/exe/deepTools/3.5.4/bin/estimateScaleFactor", line 8, in <module>
    sys.exit(main())
  File "/opt/gensoft/exe/deepTools/3.5.4/venv/lib/python3.8/site-packages/deeptools/estimateScaleFactor.py", line 105, in main
    args = parser.parse_args(args)
NameError: name 'parser' is not defined
```

deepTools 3.5.4 installed from release tag: https://github.com/deeptools/deepTools/archive/3.5.4.tar.gz

seems to me that as  [ParseArguments](https://github.com/deeptools/deepTools/blob/4a4029b5c2e725b7cebc27217b76d23910508412/deeptools/estimateScaleFactor.py#L17) returns the whole arguments already parsed. 
line 105 should be just `args = parseArguments(args)`

regards

Eric

**Comment by WardDeb** [comment]
Thanks for the report ! you're right. Fix has been merged into develop, there's a new release coming soon.

Kind regards,

WardDeb
