### ISSUE TITLE
Can I directly ajdust the height ratio of the subplots when using several bed files? 

### ISSUE THREAD

**Issue by Myrtle-bio** [deeptools/deepTools#1288]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [ ] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

Sorry, I checked the previous issue with words 'subplot' and 'height', I didn't see similar issue. 

 - [ ] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.

deeptools 3.5.1
Python 3.7.6

 - [ ] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).
```
computeMatrix scale-regions -S H3K27ac.cpm.bw  H3K4me1.cpm.bw H3K4me3.cpm.bw -R miRNA_TSS.bed gene_tss_both500bp.bed --beforeRegionStartLength 3000 --regionBodyLength 1000 --afterRegionStartLength 3000 --skipZeros -o matrix.mat.gz --numberOfProcessors 30

plotHeatmap -m matrix.mat.gz  --outFileName Leaf.pdf  --yMax 2.5 1 2.5 --colorMap Oranges_r Blues_r Greens
```

 - [ ] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).

![image](https://github.com/deeptools/deepTools/assets/148927074/4cc7066d-8312-4d6b-ac40-da5c40d94032)

Hello, all!

Because the number of rows in my two BED files differs significantly, the heights of the subplots in my output PDF are very uneven. Is there a parameter that I can use to directly adjust the height ratio of the subplots?

Thanks a lot to the software!

**Comment by WardDeb** [comment]
No, there is not option for changing the height ratios of the subplots. You could either make two heatmaps (one per region), or have a look at --perGroup.
