### ISSUE TITLE
Why does alignmentSieve output bam files with no sequence / base quality?

### ISSUE THREAD

**Issue by chklee30** [deeptools/deepTools#1289]
deepTools version: deeptools/3.5.0
python version: Python 2.7.12

Command: `alignmentSieve --numberOfProcessors max --ATACshift --blackListFileName ${blacklist}/hg38-blacklist.v2.bed --bam ${sample}.blacklist-filtered.bam -o ${sample}-shifted.bam`

head of output bam file:
```
SRR11960172.31746147	163	chr1	3000138	33	48M	=	3000134	-43	*	*
SRR11960172.31746147	83	chr1	3000134	33	47M	=	3000138	-43	*	*
SRR11960172.41342003	163	chr1	3000216	38	71M	=	3000235	90	*	*
SRR11960172.41342003	83	chr1	3000235	38	71M	=	3000216	-90	*	*
SRR11960172.19736722	163	chr1	3000491	35	72M	=	3000582	162	*	*
SRR11960172.6668354	99	chr1	3000528	35	68M	=	3000524	-63	*	*
SRR11960172.6668354	147	chr1	3000524	35	67M	=	3000528	-63	*	*
SRR11960172.19736722	83	chr1	3000582	35	71M	=	3000491	-162	*	*
SRR11960172.2999978	99	chr1	3000677	32	72M	=	3000880	274	*	*
SRR11960172.31499316	99	chr1	3000822	32	72M	=	3000946	195	*	*
```

As you can see, the last two columns where the sequence and quality scores should usually be, are replaced with wildcards. Is this expected behavior? If so, why? Does this not present any problems for downstream analysis?

**Comment by WardDeb** [comment]
These are not included because it is unclear what to report when you are shifting reads (if you drop --ATACshift,  both fields would be retained). In case you have a specific use-case here, feel free to re-open and explain what the expected behavior should be with regards to the new coordinates after shift.
