### ISSUE TITLE
plotHeatmap.py fails because direct matplotlib.tight_layout use was deprecated in matplotlib 3.6.0

### ISSUE THREAD

**Issue by eernst** [deeptools/deepTools#1292]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [x] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

 - [x] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.
deeptools 3.5.4
Python 3.10.13

 - [x] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).
`plotHeatmap -m [matrix_input] -out [out_PDF] --sortRegions descend --sortUsing mean --samplesLabel [sample_label] --regionsLabel [region_label] --colorMap seismic --zMin -0.178126 -0.202732 -0.126409 --zMax 0.063352 0.06986110000000056 0.830194 --yMin -0.09703 -0.101268 0.0350736 --yMax -0.0162055 -0.0278442 0.688624 --interpolationMethod bilinear --outFileSortedRegions [sorted_regions_outfile]`

 - [x] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).
`Traceback (most recent call last):
  File "<truncated>/bin/plotHeatmap", line 10, in <module>
    sys.exit(main())
  File "<truncated>/lib/python3.10/site-packages/deeptools/plotHeatmap.py", line 876, in main
    plotMatrix(hm,
  File "<truncated>/lib/python3.10/site-packages/deeptools/plotHeatmap.py", line 587, in plotMatrix
    import matplotlib.tight_layout as tl
ModuleNotFoundError: No module named 'matplotlib.tight_layout'`

See: https://matplotlib.org/stable/api/tight_layout_api.html and https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.6.0.html#modules

(I manually truncated the paths in the output - they point to a conda environment where deeptools is installed)

**Comment by WardDeb** [comment]
Thanks for reporting !
This is taken care of in the development branch already, a new release will follow soon.
