### ISSUE TITLE
How to control the color range of the image

### ISSUE THREAD

**Issue by Krithika-Bhuvan** [deeptools/deepTools#1298]
Hello, I would like to know if there is a setting to control the color range of the image. For instance in this image the color range is from 0 to 10. Is there a way to set this 0-10 color range for another graph as well ?  I tried using --yMin 0 --yMax 4 but that controls the axis of the line graph above and not this color range. 

<img width="120" alt="Screenshot 2024-03-12 at 11 36 44 AM" src="https://github.com/deeptools/deepTools/assets/1800604/c018d8f2-84f7-46a9-82d7-bdefd149ca5c">

This is the code i used to get this plot. 
```
computeMatrix scale-regions \
		-S $BW \
		-R $BED1 $BED2 $BED3 $BED4 \
 		--beforeRegionStartLength 3000 \
  		--regionBodyLength 5000 \
 		--afterRegionStartLength 3000 \
		--numberOfProcessors 10 \
		--skipZeros -o $OUTM

plotHeatmap -m $OUTM -out $OUTIMAGE --yMin 0 --yMax 4 --missingDataColor "#FFF6EB"
```

**Comment by thomasmanke** [comment]
Try --zMin and --zMax.

**Comment by Krithika-Bhuvan** [comment]
Thank you
