### ISSUE TITLE
Heatmap plotting and interpretation

### ISSUE THREAD

**Issue by Krithika-Bhuvan** [deeptools/deepTools#1299]
Hello, I am a new user of the deeptools package. I have a question related to the Heatmap plotting and interpretation. I have bulk ATAC seq data for a celline with various conditions. Primary analysis was done from which peaks were obtained in the form of bed files. I also have H3Kac bed and bigwig file for the parental cell line. 

Question -  I would like to know what is the best way to plot the heatmap to answer question **"whether the condition causes chromatin to close or not".**
* It would be great to get some feedback based on your experience on what inputs to use as as the "-S" parameter and "-R" parameter, and what the heatmap should look like in order to answer the question of interest.
* So far I converted the sample bed -> bam -> bigwig file. I input the bigwig file as the "-S" parameter. Is this correct ? Or should i input the sample data as a "-R " file ?
* I have tried using H3Kac sample as the "-R" file - would this help in answering the question of interest ?
Thank you

**Comment by WardDeb** [comment]
Hi,

You should first obtain a set of differentially accessible regions depending on your conditions. Deeptools is not suited for this, but you can have a look at [snakePipes](https://github.com/maxplanck-ie/snakepipes), [AOS](https://github.com/maxplanck-ie/ATACofthesnake), or something like [diffBind](https://bioconductor.org/packages/release/bioc/html/DiffBind.html). There are quite a lot of options out there.

Once you have a set of regions in bed format, you can use plot the ATAC/ChIP signal on those by using computeMatrix and plotHeatmap. You are correct that the sample signal (in bw format) should be inputted under -S, the differential regions in bed format go via -R.

Feel free to re-open if you need more information or something is unclear. 

Ward
