### ISSUE TITLE
Could not install deeptools by conda

### ISSUE THREAD

**Issue by Sum-low** [deeptools/deepTools#1320]
Hi! I use conda to install deeptools in my envs, but this error always occurs.

(deeptools) C:\Users\Administrator>conda install -c bioconda deeptools
Channels:
 - bioconda
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides deeptoolsintervals needed by deeptools-3.2.0-py_0

Could not solve for environment specs
The following packages are incompatible
└─ deeptools is not installable because there are no viable options
   ├─ deeptools [3.2.0|3.2.1] would require
   │  └─ deeptoolsintervals, which does not exist (perhaps a missing channel);
   └─ deeptools [3.3.0|3.3.1|...|3.5.5] would require
      └─ deeptoolsintervals >=0.1.8 , which does not exist (perhaps a missing channel).

**Comment by bgruening** [comment]
Are you trying to install deeptools on Windows? This is at least via conda not supported.

**Comment by Sum-low** [comment]
> Are you trying to install deeptools on Windows? This is at least via conda not supported.
You're right! Thank you so much! I forget it.
Now successfully installed deeptools on Ubuntu 18.04, but I could not get v3.5.5 in Python 3.11.7, so I installed v3.5.4 with Python 3.7x.
Here is error.
`Could not solve for environment specs
The following packages are incompatible
├─ deeptools is installable with the potential options
│  ├─ deeptools [1.5.8.2|1.5.9.1|...|3.1.3] would require
│  │  └─ python [2.7* |>=2.7,<2.8.0a0 |>=2.7,<3 ], which can be installed;
│  ├─ deeptools [2.3.1|2.3.2|...|2.5.0] would require
│  │  └─ python 3.4* , which can be installed;
│  ├─ deeptools [2.3.1|2.3.2|...|3.1.3] would require
│  │  └─ python [3.5* |>=3.5,<3.6.0a0 ], which can be installed;
│  ├─ deeptools [2.3.5|2.3.6|...|3.0.2] would require
│  │  └─ python 3.6* , which can be installed;
│  ├─ deeptools [3.1.0|3.1.1|3.1.2|3.1.3] would require
│  │  └─ python >=3.6,<3.7.0a0 , which can be installed;
│  ├─ deeptools 3.1.3 would require
│  │  └─ python >=3.7,<3.8.0a0 , which can be installed;
│  └─ deeptools [3.2.0|3.2.1|...|3.5.5] would require
│     └─ pysam >=0.14.0  with the potential options
│        ├─ pysam [0.14.0|0.14.1|...|0.15.3] would require
│        │  └─ python [2.7* |>=2.7,<2.8.0a0 ], which can be installed;
│        ├─ pysam [0.14.0|0.14.1|...|0.15.2] would require
│        │  └─ python [3.5* |>=3.5,<3.6.0a0 ], which can be installed;
│        ├─ pysam [0.14.0|0.14.1] would require
│        │  └─ python 3.6* , which can be installed;
│        ├─ pysam [0.14.1|0.15.0|...|0.15.3] would require
│        │  └─ python >=3.6,<3.7.0a0 , which can be installed;
│        ├─ pysam [0.15.2|0.16.0.1|0.17.0] would require
│        │  └─ libdeflate >=1.7,<1.22.0a0 , which conflicts with any installable versions previously reported;
│        ├─ pysam [0.15.2|0.16.0|0.16.0.1] would require
│        │  └─ libdeflate >=1.6,<1.22.0a0 , which conflicts with any installable versions previously reported;
│        ├─ pysam [0.15.2|0.15.3] would require
│        │  └─ libdeflate >=1.3,<1.22.0a0 , which conflicts with any installable versions previously reported;
│        ├─ pysam [0.15.2|0.15.4] would require
│        │  └─ libdeflate >=1.5,<1.22.0a0 , which conflicts with any installable versions previously reported;
│        ├─ pysam [0.15.2|0.18.0|0.19.0|0.19.1] would require
│        │  └─ libdeflate >=1.10,<1.22.0a0 , which conflicts with any installable versions previously reported;
│        ├─ pysam [0.15.2|0.15.3] would require
│        │  └─ python >=3.7,<3.8.0a0 , which can be installed;
│        ├─ pysam [0.15.2|0.17.0|0.18.0] would require
│        │  └─ libdeflate >=1.9,<1.22.0a0 , which conflicts with any installable versions previously reported;
│        ├─ pysam [0.15.2|0.19.1|0.20.0|0.21.0] would require
│        │  └─ libdeflate >=1.13,<1.22.0a0 , which conflicts with any installable versions previously reported;
│        ├─ pysam [0.21.0|0.22.0|0.22.1] would require
│        │  └─ libdeflate >=1.18,<1.22.0a0 , which conflicts with any installable versions previously reported;
│        └─ pysam 0.22.1 would require
│           └─ libdeflate >=1.20,<1.22.0a0 , which conflicts with any installable versions previously reported;
└─ pin-1 is not installable because it requires
   └─ python 3.11.* , which conflicts with any installable versions previously reported.`

**Comment by WardDeb** [comment]
Hi,

Python 3.7 isn't supported anymore, you can re-open and post the error you get while trying with 3.11 if this is still an issue.
