### ISSUE TITLE
Typo/Bug in heatmapper.py script

### ISSUE THREAD

**Issue by AIqbal94** [deeptools/deepTools#1322]
Hi,
I recently came across this and thought to open an issue for it, I think in line 379, it should be `np.nan` instead of `np.NAN`

https://github.com/deeptools/deepTools/blob/master/deeptools/heatmapper.py#L379

For me changing it to `np.nan` fixed the error.

**Comment by myliu221** [comment]
Hi,

I encountered similar issue with error "AttributeError: module 'numpy' has no attribute 'NAN'" after installing deeptools , and solved using the above method. Thanks.

**Comment by WardDeb** [comment]
Thanks for the report, this is taken up with #1325, and will be released soon.
