### ISSUE TITLE
Cannot install deepTools with conda

### ISSUE THREAD

**Issue by sarahbowden** [deeptools/deepTools#1327]
Tried to install deeptools on Mac with M1 chip osx-arm64 using conda. I have Python 3.12.2

conda install -c bioconda deeptools

gives the following error:

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides deeptoolsintervals needed by deeptools-3.2.0-py_0

Could not solve for environment specs
The following packages are incompatible
└─ deeptools is not installable because there are no viable options
   ├─ deeptools [3.2.0|3.2.1] would require
   │  └─ deeptoolsintervals, which does not exist (perhaps a missing channel);
   └─ deeptools [3.3.0|3.3.1|...|3.5.5] would require
      └─ py2bit >=0.2.0 , which does not exist (perhaps a missing channel).

**Comment by bgruening** [comment]
Please try the following `conda create --name deeptools -c conda-forge -c bioconda deeptools`

**Comment by sarahbowden** [comment]
Thanks for the suggestion, however this still gives me a similar error:

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides deeptoolsintervals needed by deeptools-3.2.0-py_0

Could not solve for environment specs
The following packages are incompatible
└─ deeptools is not installable because there are no viable options
   ├─ deeptools [3.2.0|3.2.1] would require
   │  └─ deeptoolsintervals, which does not exist (perhaps a missing channel);
   └─ deeptools [3.3.0|3.3.1|...|3.5.5] would require
      └─ deeptoolsintervals >=0.1.8 , which does not exist (perhaps a missing channel).

**Comment by bgruening** [comment]
Which exact command have you used?

**Comment by sarahbowden** [comment]
This time I ran the code you provided above: 
`conda create --name deeptools -c conda-forge -c bioconda deeptools
`

**Comment by bgruening** [comment]
I'm not sure how OSX works these days. Do you have this x86 combat mode enabled? Do you see any indications that ARM packages are downloaded/searched?

**Comment by WardDeb** [comment]
We'd need to see what the actual problem is with deeptoolsintervals, as for a work-around, you should be able to install using the osx-64 env:

`CONDA_SUBDIR=osx-64 conda create -c conda-forge -c bioconda -n deeptools deeptools`

**Comment by sarahbowden** [comment]
Thank you both for your help. 

@bgruening unfortunately my understanding of the computer architecture is not very deep. To the best of my knowledge I am only running on an ARM system, and I don't know how to check what was downloaded (but would be happy to if given a script). I have Miniconda3 for ARM and managed to install Samtools and Bedtools using this.

@WardDeb thanks, this seems to have worked, so I will close this thread.

**Comment by bgruening** [comment]
@WardDeb can you put this maybe in the readme/docs?

**Comment by xiaobaiymq** [comment]
you can install by pip, it's OK
