### ISSUE TITLE
plotHeatmap issues

### ISSUE THREAD

**Issue by vivekbhr** [deeptools/deepTools#606]
I am editing this to include multiple issues with plotHeatmap (instead of opening a series of issues).

- [x] heatmap center label should reflect the --reference-point `argument` (I think this needs changes in computeMatrix code, rather than heatmapper.

- [ ] colorbar center should be centered at zero in case of divergent panel (I am not sure if it's because of tick labels misplacement, or the scale is actually wrong, but this stays wrong even after using a fixed zmin and zMax).

- [ ] options to scale the signal by `sample` or `group` before running the kmeans/hclust should be provided.

**Comment by dpryan79** [comment]
Regarding the 3rd option, I would generally prefer that people handle that themselves. I'm very much against adding more options to plotHeatmap/plotProfile/computeMatrix since they're already unwieldy.

Can you give an example of the colorbar centering issue?

**Comment by dpryan79** [comment]
I've split the first point into its own issue (#683). It's starting to annoy me know, so I'll fix it.

**Comment by dpryan79** [comment]
The first issue you mentioned is now taken care of in `develop` and will work properly in 3.0.2.
