### ISSUE TITLE
Do we really need a config file any more?

### ISSUE THREAD

**Issue by dpryan79** [deeptools/deepTools#613]
At the moment, the config file only has two entries: `default_proc_number` and `tmp_dir`. `tmp_dir` can already be changed with environment variables. I wonder if anyone ever bothers to change `default_proc_number`. I would propose getting rid of this entirely and making the default number of threads 1. I kind of assume that people are already specifying how many threads they want to use already.

As an aside, Galaxy already does away with the config file.

**Comment by endrebak** [comment]
I'd remove it.

**Comment by bgruening** [comment]
Me too :)

**Comment by vivekbhr** [comment]
:+1: for remove..

**Comment by dpryan79** [comment]
This is now gone in `develop`. The default number of threads for all tools is 1, as seems reasonable.
