### ISSUE TITLE
Per-column tick labels in computeMatrix output?

### ISSUE THREAD

**Issue by dpryan79** [deeptools/deepTools#614]
This is only relevant since the advent of `computeMatrixOperations`. Now that one can `cbind` different matrices, it's possible to have things like `scale-regions` and `reference-point` in the same plot. However, the ticks and labels are completely screwed up then. This is due to the whole matrix having a single set of labels/positions. An alternative to this would be to have a list of labels and positions that could repeat per-column. This would allow better mixing and matching of these. Implementing this might be a bit annoying due to backward compatibility, though if we make a new major release I'm not completely sold on having to care about that.

**Comment by vivekbhr** [comment]
good point.. i haven't seen how bad it looks but might be a useful fix

**Comment by dpryan79** [comment]
Tested:
 - [ ] computeMatrix
   - [ ] scale-region
   - [ ] reference-point
 - [ ] computeMatrixOperations cbind
 - [ ] plotHeatmap
    - [ ] old format
    - [ ] new format
    - [ ] Mixed scale-region/reference-point
 - [ ] plotProfile
    - [ ] old format
    - [ ] new format
    - [ ] Mixed scale-region/reference-point

**Comment by dpryan79** [comment]
I'm running into a but introduced in matplotlib-2.1.1 at the moment, it looks like we have to skip that release.

**Comment by dpryan79** [comment]
This is now merged into `develop`.
