### ISSUE TITLE
Add --sortRegions keep in plotHeatmap?

### ISSUE THREAD

**Issue by endrebak** [deeptools/deepTools#621]
If you use `--sortRegions no` in `--plotHeatmap`, is the sort order of the matrix then preserved? Even if this is so, you might want to add a dummy `keep` option to `--sortRegions` or add something about this in the docs.

My commands/what I want:

```
computeMatrix -R sort_order.bed --sortRegions keep
plotHeatmap --sortRegions no # I want to keep the sort order from the last step
```

**Comment by dpryan79** [comment]
—sortRegions no does what you want, though I agree that adding a “keep” option for the same thing would be a good idea.

**Comment by dpryan79** [comment]
This is now implemented in `develop` and will be present in deepTools 3.0
