### ISSUE TITLE
Add a --smartLabels option, to auto strip path and file extension in labels.

### ISSUE THREAD

**Issue by dpryan79** [deeptools/deepTools#627]
This was requested internally and I'd be surprised if others wouldn't like it too. Provided your file names are otherwise meaningful you could use this such that `-b path/foo1.bam path2/foo2.bam` had labels`foo1` and `foo2`, which would be convenient with large numbers of samples where it's annoying to manually set these (yes, one could do this in snakemake, but for one-off stuff this is simpler).

This wouldn't be needed in Galaxy.

**Comment by dpryan79** [comment]
Note that this option won't be exposed in Galaxy, since it wouldn't make sense there.

**Comment by dpryan79** [comment]
The following have been tested

 - [ ] `computeMatrix`, this is only for the bigWig files, since BED/GTF files can already have internal names.
 - [ ] `estimateReadFiltering`
 - [ ] `multiBamSummary`
 - [ ] `multiBigwigSummary`
 - [ ] `plotCoverage`
 - [ ] `plotEnrichment`
 - [ ] `plotFingerprint`

Presumably a warning should be produced if the user specifies labels and also `--smartLabels`.

**Comment by dpryan79** [comment]
As an aside, I see that some of the plot* functions already strip the path if you don't specify a label. It would have been nice if that were documented.

**Comment by kelly-sovacool** [comment]
FYI this option appears to be missing from the docs: https://deeptools.readthedocs.io/en/develop/index.html
