### ISSUE TITLE
bamFilterReads (now alignmentSieve)

### ISSUE THREAD

**Issue by dpryan79** [deeptools/deepTools#628]
This came up when @mirax87 was talking about ATAC-seq and it turned out that one had to convert to BEDPE and do a bunch of filtering before peak calling. It'd make more sense to just allow filtering of BAM/CRAM files based on the normal alignment filtering options in deepTools, which would include fragment size. If MACS produces reasonable output with that then we can skip the whole IO-intensive text file operation stuff in the ATAC-seq pipeline.

@mirax87: Would you be able to test this if I quickly implement it?

**Comment by mirax87** [comment]
Yeah, that would useful! 
for filtering a) based on fragment size b) chromosome blacklist/whitelist

Additionally, the 5' end of ATAC-seq reads are shifted with respect to the actual cut-site of the Transposase. Further analysis at nucleotide resolution e.g. TF footprinting the shifting is critical. 

Maybe this tag shift can be incorporated somehow.

I am happy to test the new functionality.

**Comment by dpryan79** [comment]
@mirax87 Can you test this and see if it works for your needs? You'll be able to access it via `module load deeptools/develop` on the cluster.

**Comment by dpryan79** [comment]
I'd like to make the concatenation step faster still, but otherwise this should now be working.

**Comment by dpryan79** [comment]
I think I'll rename this to `alignmentSieve` and add the option to produce BED/BEDPE files with shifting.

**Comment by dpryan79** [comment]
Talking about things internally a bit, it might be useful to actually output shifted reads in BAM format. This would then need to get sorted, but that's not exactly a problem. Shifting would cause the sequence and qual information to get stripped.

**Comment by vivekbhr** [comment]
isn't `alignmentSieve` a weird name? :expressionless:

**Comment by dpryan79** [comment]
Not really.

**Comment by dpryan79** [comment]
This seems to produce proper BAM files now, the only remaining issue is getting that part working in Galaxy (presumably the BAM files then need to be sorted).

**Comment by dpryan79** [comment]
This can now produce proper BAM/CRAM files and is now included in `develop`.

**Comment by AbeerMM** [comment]
> Talking about things internally a bit, it might be useful to actually output shifted reads in BAM format. This would then need to get sorted, but that's not exactly a problem. Shifting would cause the sequence and qual information to get stripped.

@dpryan79 I'm sorry to comment on this closed issue, but it's my first time using alignmentSieve, and I found your comment about the sequence and qual info getting stripped. Is there any way or workaround to output the full bam file including the sequence info?

**Comment by dpryan79** [comment]
@abermm Not at the moment. Do you need the sequence/qual for something in particular?

**Comment by AbeerMM** [comment]
@dpryan79 I see. 
I'm using ATACseqQC package in R, and this package has a function (_shiftGAlignmentsList()_) reads the bam in GAligmentsList object, shifts, and output a full bam file (including the sequence and qua info). However, this function is very slow, and when I tested alignmentSieve it was really fast. I was hoping I can use it instead of the R function to generate the bam files. 

But to answer your question in particular, I feed the shifted bam files to another function (_splitGAlignmentsByCut()_) that requires the bam file to includes the sequence and qua info. It runs random forest to split the reads based on fragment length, GC content, etc.

**Comment by dpryan79** [comment]
@AbeerMM Can you open a feature request? I need to think about this more and whether it's really possible. In some cases I think the answer will be that it is, but not in all.
