### ISSUE TITLE
bamCompare --normalizeUsing and --ratio/--method

### ISSUE THREAD

**Issue by dpryan79** [deeptools/deepTools#629]
1. `--ratio` no longer makes much sense as an option, either `--method` or something like `--operation` would make more sense.
2. There's still a `--normalizeTo1x` option (is it used though?). Presumably this should also be move to `--normalizeUsing`. Additionally, we have the `--normalizeUsing` methods AND the `--scaleFactorsMethod` methods. This seems a bit duplicated to me and I'd favour just making them all `--normalizeUsing`. I think that'd be much clearer.

**Comment by fidelram** [comment]
Let's change `--ratio` to `--operation`. @vivekbhr can you comment on the `--normalizeTo1x`?

**Comment by vivekbhr** [comment]
I proposed the above change in order to make the options more consistent with what they do..

**Comment by dpryan79** [comment]
Consensus from in office discussion:

1. Just use `--operation`
2. Remove `--normalizeTo1x` in bamCompare and move it into `--normalizeUsing` in bamCoverage. The docs for bamCompare should clarify that "normalization" scales both samples and then does the operation, whereas "scaling" scales one sample (but not both) and then the operation is done. I think I borked this in the documentation update a bit.

**Comment by steffenheyne** [comment]
3. introduce  --effectiveGenomeSize  <INT> option, this is only used in combination with --normalizeUsing RPGC 

or?

**Comment by vivekbhr** [comment]
Yes, since you need it only for the RPGC

**Comment by dpryan79** [comment]
This is now merged into `develop`.
