### ISSUE TITLE
k-means clustering - seed cannot be set

### ISSUE THREAD

**Issue by mlukosev** [deeptools/deepTools#630]
I was using computeMatrix and plotHeatmap tools for my data and realised that seed for k-means clustering is always random and cannot be set, hence each time I run the plotHeatmap line I get slightly different results. Would be really nice if this option would become available.
Thank you!

**Comment by dpryan79** [comment]
Are you using this for automated testing or something like that? It's otherwise somewhat unusual to need exactly the same results each time for something like this.

**Comment by mlukosev** [comment]
I would like to set the seed for the reproducibility, e.g. play around with heatmap colours, labels etc and also plotProfile separately that generates the same clusters as the heatmap without the results changing each time.

**Comment by dpryan79** [comment]
I don't foresee ever making an option for this, instead I suggest you add the seed [here](https://github.com/deeptools/deepTools/blob/b5fc4073c884a2d6a4092ea85150db1971010f28/deeptools/heatmapper.py#L1178) in your local copy. The syntax would be something like:

    from numpy import random
    random.seed(1234)
