### ISSUE TITLE
It's unclear how to specify the order of the --colorMap option in plotHeatmap in Galaxy

### ISSUE THREAD

**Issue by dpryan79** [deeptools/deepTools#633]
In Galaxy, the `--colorMap` option in plotHeatmap is a multi-select from a list. That's all well and good, but it seems as though the order of the colormaps after one selects them is dictated by their order in the list in the wrapper. For example, if one selects `grey` and then `Accent` and then `gist_gray`, then the final order used by Galaxy will be `Accent` then `grey` then `gist_gray`, because that's the order in the list. It's unclear to me if there's some way to change this in Galaxy. If this can't be changed then making this a repeat in the wrapper would be a possible solution. This wouldn't be ideal, since it requires a lot of extra clicking, but if it's the only solution...

@bgruening Do you know of any way for end-users to specify the order in which elements from a `<param ... multiple="true">` list are used?

**Comment by bgruening** [comment]
I'm currently not aware of this, but I think there is was/is an open issue about that. For the time being the only thing that I think is working is a repeat element.

**Comment by dpryan79** [comment]
Darn, I liked the multiselect. A repeat it is then.

**Comment by fidelram** [comment]
I think it is also not possible to add your own color map which is something I use often. The syntax is 'color1,color2,color3,color4' with color number >2

**Comment by dpryan79** [comment]
This is now implemented in `develop`.
