### ISSUE TITLE
Editing plotProfile plots

### ISSUE THREAD

**Issue by Anupriya014** [deeptools/deepTools#636]
Hello all, 

I am using plotProfile for plotting TSS & TTS like this : 
computeMatrix reference-point -S ./WT_sorted.bw -R ./WT_TSS_regions.txt -a 500 -b 500 --referencePoint TSS --outFileName ./WT_matrix 
   
plotProfile -m ./WT_matrix -out ./tss_plots/WT_TSS_plot.png --plotTitle "" --yAxisLabel "Read Counts" --regionsLabel "" --samplesLabel "" --legendLocation upper-center
![wt_tss_plot](https://user-images.githubusercontent.com/24602680/33976265-b4417eda-e0b9-11e7-9139-30a68747b4e5.png)

----------------------
computeMatrix reference-point -S ./WT_sorted.bw -R ./WT_TTS_regions.txt -a 500 -b 500 --referencePoint TES --outFileName ./WT_matrix  

plotProfile -m ./WT_matrix -out ./tts_plots/WT_TTS_plot.png --plotTitle "" --yAxisLabel "Read Counts" --regionsLabel "" --samplesLabel "" --legendLocation upper-center --refPointLabel "TTS"
![wt_tts_plot](https://user-images.githubusercontent.com/24602680/33976261-b05fdd52-e0b9-11e7-823b-ef1e4889469e.png)

And Gene plots like this : 
computeMatrix scale-regions -S ./WT_sorted.bw -R ./genes.bed --outFileName ./WT_matrix --startLabel "" --endLabel "" -b 500 -a 500

plotProfile -m ./WT_matrix -out ./gene_plots/WT_gene_plot.png --plotTitle "" --yAxisLabel "Read Counts" --regionsLabel "" --samplesLabel "" --legendLocation upper-center --refPointLabel ""
![wt_gene_plot](https://user-images.githubusercontent.com/24602680/33976241-7dae6b3a-e0b9-11e7-88ab-a6b833c0cf29.png)

If there any way I can override the 'TSS' & 'TES' marking in gene plot to 'Gene start' & 'Gene end' respectively? "--startLabel" & "--endLabel" are not working in computeMatrix scale-regions command..
Can I mark all 3 plots with minor ticks of 50, 100, 150 etc ? As it's just showing "-0.5" & "0.5" at the extremes of the plot?
Please help me out..

**Comment by dpryan79** [comment]
Yes, you're looking for the `--startLabel` and `--endLabel` options.

**Comment by Anupriya014** [comment]
Hi Devon. Thanks for the reply.
But using --startLabel "Gene_start" --endLabel "Gene_end" is not making any change to the labellings.. 
And can I give custom points on x-axis such as 0.25kb, 0.30kb .. ? I thought there will be some parameter such as xlim but I couldn't find it..

**Comment by dpryan79** [comment]
There's no mechanism for providing custom labels, for that I'd recommend saving the data as a text file (there an option for this) and then plotting it in R. I just tried the two aforementioned options with plotProfile and the labels did indeed change for me.

**Comment by fidelram** [comment]
you can use `--startLabel` to replace TSS and `--endLabel` to replace TES
in the `plotProfile` command. As for the the minor ticks you can either: 1)
download the underlying data and plot using matplotlib or R. 2) dig into
the plotProfile code and modify it to suit your needs 3) make a svg or pdf
version of the figure and edit with InkScape or Illustrator.
