### ISSUE TITLE
Segmentation fault (core dumped) for bamCoverage

### ISSUE THREAD

**Issue by john-lee-johnson** [deeptools/deepTools#638]
Hello,

I've installed deeptools 2.5.4 using bioconda, I am trying to make a bigwig from a bam file, but I keep getting a `Segmentation fault (core dumped)` error.

Any thoughts on how to fix it? Thanks so much!

**Comment by dpryan79** [comment]
Grr, I feared this would happen. Please `conda install -c bioconda pybigwig=0.3.7`. I'll try to track down the exact cause of this today, though, and release version 0.3.8.

**Comment by dpryan79** [comment]
I've just pushed out pyBigWig-0.3.9, which should fix this (it did in a test I ran). This is currently available via pypi and should be available in ~1 hour with `conda install` (the automated system that bioconda uses to push out packages is processing it now).

**Comment by john-lee-johnson** [comment]
Yes that worked! Thank you!
