### ISSUE TITLE
regions.bed: orientation?

### ISSUE THREAD

**Issue by robinweide** [deeptools/deepTools#639]
Hi there,

How does deeptools computeMatrix handle the orientation of entries in a regions.bed file? In which column does it expect to find the orientation (e.g. + or -)?

Thanks,
Robin

**Comment by dpryan79** [comment]
DeepTools does what one would expect, namely, it flips things such that in the resulting matrix regions are always 5' -> 3' (i.e., regions on the + strand are processed as is while those on the - strand have their signals reversed).

BED files store their strand information in the 6th column.

**Comment by Datacond** [comment]
Hi， @dpryan79 
I found an interesting phenomenon. In the regions.bed file, there is a difference between the profile plot when placing the strand information in the fourth column and the sixth column. What's the cause of this?
