### ISSUE TITLE
RuntimeError: The entries you tried to add are out of order, precede already added entries, or otherwise use illegal values.  Please correct this and try again.

### ISSUE THREAD

**Issue by gk7279** [deeptools/deepTools#641]
Hi-

here is my command

```
bamCoverage --filterRNAstrand forward --normalizeUsingRPKM --binSize 1 -b $i'.filtered.sorted.bam' -o $i'.reverse.norm.rpkm.bw'
bamCoverage --filterRNAstrand reverse --normalizeUsingRPKM --binSize 1 -b $i'.filtered.sorted.bam' -o $i'.forward.norm.rpkm.bw'
```

Using python 2.7.12

**Comment by dpryan79** [comment]
Are both of the bigWig files producing this or only one of them? Which version of deepTools and pyBigWig do you have installed?

**Comment by dpryan79** [comment]
My guess is that this was fixed in pyBigWig-0.3.10, which I released this morning. If not, let me know and provide the aforementioned details.

**Comment by andyjslee** [comment]
I'm having this issue, too. I sort my list before I add entries, and I am getting this error.

**Comment by dpryan79** [comment]
@andyjslee Can you provide me with a reproducible example?
