### ISSUE TITLE
confused about bamCompare

### ISSUE THREAD

**Issue by CNSWXR** [deeptools/deepTools#642]
The protocol said "only with –ratio subtract can –normalizeTo1x or –normalizeUsingRPKM be used". However, I read a paper, it said "read coverage was first calculated using the bamCompare tool
(RPKM, Log2(ChIP/IgG) in deepTools version 1.5.11". So i felt confused about the parameter setting. Could you help me solve my problem?

**Comment by fidelram** [comment]
What you read in the manual is correct. Check with the authors of the paper
to find what they did.

**Comment by CNSWXR** [comment]
Thank you for the reply. BTW, the deeptools is very useful
