### ISSUE TITLE
Effective genome sizes

### ISSUE THREAD

**Issue by dpryan79** [deeptools/deepTools#647]
These values should probably be updated. Actual values are read-length dependent, so it'd be nice to construct a table (for the documentation, this wouldn't be in the tools or galaxy wrappers) that had effective genome size as a function of that. GEM-mappability hasn't existed in years, so that probably can't be used. Instead, I expect khmer can provide good measurements MUCH faster.

**Comment by dpryan79** [comment]
Yeah, `unique-kmers.py` is giving similar results to those we've included previously, but (A) it's a package that's well maintained and (B) it's a LOT faster. I'll switch everything to this and make a table.

**Comment by dpryan79** [comment]
The defaults in the wrappers would be for 50 base reads I guess, unless someone else has other preferences.

**Comment by fidelram** [comment]
Depending on the mapping strategy the effective genome should be:
 * if multimapping-reads **are removed** the effective genome size is the size of the genome excluding repetitive regions. I suppose that unique-kmers.py is useful for this.
 * if multimapping-reads **are kept**, the effective genome size is the length of the genome minus all "NNNNN" stretches. This can be easily computed with faCount of UCSC tools

If there are blacklisted regions, their length should also be removed.

**Comment by dpryan79** [comment]
This is now updated in the `develop` branch.
