### ISSUE TITLE
error message while using computeMatrix

### ISSUE THREAD

**Issue by spiya** [deeptools/deepTools#648]
Hello,

I am trying to use computeMatrix and plotHeatmapper to generate heatmaps for my ChIPseq data. I am using following command to generate computeMatrix:

computeMatrix reference-point \
-S ARF11_SP12_treat_pileup.bw \
-R Arabidopsis.bed \
--referencePoint center \
-a 2000 -b 2000 \
-out matrix_ARF11_SP12.gz

However, I received the following error message:
Traceback (most recent call last):
  File "/lustre/haven/gamma/Sarbo_Ivy/packages/anaconda2/bin/computeMatrix", line 11, in <module>
    main(args)
  File "/lustre/haven/gamma/Sarbo_Ivy/packages/anaconda2/lib/python2.7/site-packages/deeptools/computeMatrix.py", line 422, in main
    hm.computeMatrix(scores_file_list, args.regionsFileName, parameters, blackListFileName=args.blackListFileName, verbose=args.verbose, allArgs=args)
  File "/lustre/haven/gamma/Sarbo_Ivy/packages/anaconda2/lib/python2.7/site-packages/deeptools/heatmapper.py", line 254, in computeMatrix
    matrix = np.concatenate([r[0] for r in res], axis=0)
ValueError: need at least one array to concatenate

Any help would be greatly appreciated.

Thanks,
Sarbo

**Comment by dpryan79** [comment]
This will happen if there were no values stored in your bigWig files in the regions specified in your BED file. My presumption is that there's some sort of chromosome name mismatch that deepTools can't account for.

**Comment by spiya** [comment]
Thanks Devon. The error was due to chromosome name mismatch. It worked now.

**Comment by Chipeyown** [comment]
i solved this problem by changing 'Chr' into 'chr' in the first columns.

**Comment by kzxkzx** [comment]
> Thanks Devon. The error was due to chromosome name mismatch. It worked now.

sorry，I want to ask if you are changing the chromosome name in bw file or bed promoter file

**Comment by LeilyR** [comment]
you need to have the matching chromosome name in your bed and bigwig files.
