### ISSUE TITLE
multiBamSummary BED-file reporting regions outside of those specifed

### ISSUE THREAD

**Issue by mistrm82** [deeptools/deepTools#650]
HI, I am running deeptools 2.5.3 and want to quantify read density for a specific set of regions. I have a single merged BED file with all of regions and multiple BAM files as input. Yet when I look at my count matrix I have coordinates that do not correspond to my BED file

`multiBamSummary BED-file --BED macs2/run-bcbio-defaults/GMP/multiIntersect-GMP-merged.bed --bamfiles bams/GMP/*.bam -out deepTools/multiBam.GMPpeaks.npz --outRawCounts deepTools/multiBam.GMPpeaks.tab`

**Comment by dpryan79** [comment]
That's odd, can you post some example files? The BED file and maybe a BAM file would be great.

**Comment by mistrm82** [comment]
The BAM files are quite big, but I have the BED file here (-merged.bed) and the resulting output from multiBamSummary as an example. You can cross-reference the coordinates between the files and you will see that they don't match up. Not sure what's happening, maybe I am using the command incorrectly?

[Archive.zip](https://github.com/deeptools/deepTools/files/1644071/Archive.zip)

**Comment by mistrm82** [comment]
Sorry I just figured out what was going on, and it is prior to the deepTools run!

**Comment by dpryan79** [comment]
OK, well done tracking that down :)
