### ISSUE TITLE
bamCoverage: bug in scaleFactor?

### ISSUE THREAD

**Issue by samuelCollombet** [deeptools/deepTools#655]
Hi, 
using Deeptools 2.5.5 bamCoverage, I give manually the scaling factor and it seems it is not taken into account: 
```
$ bamCoverage --bam input.bam --extendReads --binSize 1 --scaleFactor 0.02                      --numberOfProcessors 15 --outFileName test1.bw --outFileFormat bigwig --region chr1:73934080-73963723"
$ bamCoverage --bam input.bam --extendReads --binSize 1 --scaleFactor 1                         --numberOfProcessors 15 --outFileName test2.bw --outFileFormat bigwig --region chr1:73934080-73963723"
$ bamCoverage --bam input.bam --extendReads --binSize 1 --scaleFactor 4                         --numberOfProcessors 15 --outFileName test3.bw --outFileFormat bigwig --region chr1:73934080-73963723"
$ bamCoverage --bam input.bam --extendReads --binSize 1 --normalizeUsingRPKM                    --numberOfProcessors 15 --outFileName test4.bw --outFileFormat bigwig --region chr1:73934080-73963723"
$ bamCoverage --bam input.bam --extendReads --binSize 1 --normalizeUsingRPKM --scaleFactor 0.02 --numberOfProcessors 15 --outFileName test5.bw --outFileFormat bigwig --region chr1:73934080-73963723"

$md5sum test*
6f1a4de93b11c31e2738f65e9d62e9c6  test1.bw
6f1a4de93b11c31e2738f65e9d62e9c6  test2.bw
6f1a4de93b11c31e2738f65e9d62e9c6  test3.bw
d63e544b9f19a286b1fce04be85a3991  test4.bw
082ba147b8b2f6e433a36c6241833af4  test5.bw
```

for the 3 times I put only a manual scaling factor the output files are exactly the same, but when I put normalizeusingRPKM w/wt a scale factors, the files are different. 

Could there be a bug that make the scale factor not taken into account in this version?

I compared with an older version bamCoverage, and there the files were all different (funny enough, they were al ldifferent than the one from v 2.5.5 :D but I didn't check the signal itself).

**Comment by samuelCollombet** [comment]
My bad, it appeared to be a problem of conflict between libraries installed on our server (somehow not raising any error message). Re-checking the install of DeepTools and the libraries accessibility fixed it. Sorry!

**Comment by dpryan79** [comment]
No worries, you're much quicker at figuring things out than we are at looking at issues. I appreciate that you're decreasing our "time between issue reported and closed" metric :)
