### ISSUE TITLE
computeMatrix   –regionBodyLength

### ISSUE THREAD

**Issue by penglbio** [deeptools/deepTools#660]
About this parameter, I am little confused with it. Because different gene has different gene length. But if we set this parameter=3000, how we compute the value of this matrix. if one gene body length is 5000, the parameter is 3000. Will it random cut 3000 from the gene, then compute the value of the matrix?

**Comment by dpryan79** [comment]
It will shrink or expand the length of the gene to be the desired length. In other words, it scales regions to be the same size (thus the name).
