### ISSUE TITLE
The file 'XXX.bam' does not have BAM or CRAM format when using bamCoverage

### ISSUE THREAD

**Issue by guanzhidao** [deeptools/deepTools#665]
All the requirements for deepTools was installed in miniconda, and using Python3.

**Comment by dpryan79** [comment]
Presumably the file is corrupt. You'll only get this error if pysam throws an error when opening the file.

**Comment by guanzhidao** [comment]
Hi Devon, Thank you so much! The "format_option" is not working in "pysam.Samfile". I deleted it in the code and it's working on my bam files now. 
print (pysam.__version__)
0.12.0.1
Thank you again!

**Comment by dpryan79** [comment]
Hmm, how did you get pysam 0.12.0.1 via conda? The deepTools recipe explicitly lists needing pysam 0.14.0 (where `format_option` was added).

**Comment by guanzhidao** [comment]
Thank you for pointing out. I think my conda envs is a little broken.

**Comment by leleory** [comment]
Hi Devon,
I just reinstalled deeptools as the version I had missed some of the newer parameters I wanted to use. 
Install was done via pip first uninstalling deeptools. The install apparently went OK:

**Comment by dpryan79** [comment]
Ensure that you have the most recent version of pysam installed.

**Comment by leleory** [comment]
I apparently have the latest pysam.

**Comment by dpryan79** [comment]
Try the following in python:

    import pysam
    import sys
    format_options = ["required_fields=0x1FF"]
    if sys.version_info.major >= 3:
        format_options = [b"required_fields=0x1FF"]
    pysam.Samfile('XXX.bam', 'rb', format_options=format_options)

You'll get some sort of error with that, which is triggering this error from bamCoverage.

**Comment by leleory** [comment]
Apologies, my bad. With pip the new libraries were added to ~/.local/lib/python3.5. Once I added that to PYTHONPATH deeptools runs OK.
Thank you,
Lel

**Comment by nbahti** [comment]
Hi Devon,
I have the same problem. I have latest pysam (0.15.2) and my conda environment is for python2.7. Deeptools is also installed with no problem at all. I thought my bam files are broken or something like that, but I can do all the other operations with samtools or can use R packages without any problem. But  I can't use with deeptools commands like multiBamSummary which is always giving "The file 'XXX.bam' does not have BAM or CRAM format" error. Can you advice me what I can do?

**Comment by dpryan79** [comment]
@nbahti Try remaking the bam index, sometimes pysam doesn't like it for various reasons.

**Comment by nbahti** [comment]
@dpryan79   I tried, but still the same error is showing up. I did everything i could with no result. My data is RNA-seq data/bams sorted by index, may it have something to do with that? Because my ATAC-seq/Chip-seq bams are working fine.

**Comment by dpryan79** [comment]
Can you make the broken files available to me privately? I can look into the issue more then.

**Comment by nbahti** [comment]
Yes. How can I do that? by email?

**Comment by dpryan79** [comment]
Yes, send me (ryan@ie-freiburg.mpg.de) a link to drop box or google drive or something like that. Also let me know the exact command that you're using.

**Comment by zeynepkurtw** [comment]
Hi, 

I had the same issue while running plotCoverage which I cloned and set up from Github. However, I got the following error:
`XXX.bam file does not have BAM or CRAM format `

Pysam version 0.9.1 came with the deeptools 3.5.1 However, the issue was solved only when I specifically updated pysam to version 0.19.0. Here is the command I've used:

`mamba install -c bioconda pysam=0.19.0`
