### ISSUE TITLE
Request: plotHeatmap legend colour BuRd

### ISSUE THREAD

**Issue by Ni-Ar** [deeptools/deepTools#666]
Let me start by saying that your tool is great! I really like the plotHeatmap for plotting!
 
I'd be even better if we could have a colour legend palette from high Z-values in Red to low Z-values in Blue.
Basically the same as `--colorMap RdBu` but inverted (i.e. `--colorMap BuRd`).
As I understood you use the  [matplotlib](https://matplotlib.org/users/colormaps.html ) for colour maps, which does not have the "BuRd" map, so I wonder if this could be easily implemented?

I also tried inverting the `--zMin` and `--zMax` values but it returns:
`ValueError: minvalue must be less than or equal to maxvalue`
:)

Thanks!

**Comment by dpryan79** [comment]
You can supply custom colors with the `--colorList` option, give that a go.

**Comment by sagarutturkar** [comment]
Use option `--colorMap coolwarm ` and it should switch the colors as BuRD.

**Comment by LeilyR** [comment]
I would not use `coolwarm` for that purpose, matplotlib offers `_r` option so the above issue can be easily solved using `RdBu_r`.

**Comment by Ni-Ar** [comment]
Btw, if I recall well, 4 years ago I solved this issue as @dpryan79 recommended with `--colorList`. I'm happy to know that now matplot can use `RColorBrewer` names with the `_r` option.
