### ISSUE TITLE
Add pandas to required dependences

### ISSUE THREAD

**Issue by jeff-mandell** [deeptools/deepTools#669]
When I installed deepTools with Pip, pandas was not installed as dependency. However, plotCorrelation threw a ModuleNotFound error for pandas. After installing pandas with pip, plotCorrelation worked fine.

**Comment by dpryan79** [comment]
Can you post the full trace back? We don’t use pandas.

**Comment by jeff-mandell** [comment]
plotCorrelation -in bigwig_summary.ngz --whatToPlot heatmap --corMethod pearson -o bigwig_corr_heatmap_pearson.png

Traceback (most recent call last):
  File "[path]/python-3.6.4/bin/plotCorrelation", line 4, in <module>
    from deeptools.plotCorrelation import main
  File "[path]/Python3.6/site-packages/deeptools/plotCorrelation.py", line 13, in <module>
    from deeptools.correlation import Correlation
  File "[path]/Python3.6/site-packages/deeptools/correlation.py", line 20, in <module>
    import plotly.figure_factory as ff
  File "[path]/Python3.6/site-packages/plotly/figure_factory/__init__.py", line 21, in <module>
    from plotly.figure_factory._county_choropleth import create_choropleth
  File "[path]/Python3.6/site-packages/plotly/figure_factory/_county_choropleth.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

**Comment by dpryan79** [comment]
Interesting, apparently that version of plotly requires pandas. How did you install deepTools? Somehow the dependency of a dependency didn't get installed. deepTools itself doesn't depend on pandas, so whatever you did to install it acted oddly.

**Comment by jeff-mandell** [comment]
Just with pip:
pip3.6 install deepTools

**Comment by dpryan79** [comment]
Interesting, it looks like the plotly package on pypi is missing a dependency, I'll report it to them.

**Comment by vreuter** [comment]
I think it's probably intended that way, that `plotly` maintainers may've decided use of `pandas` is insufficient to warrant a true dependency that requires opt-out to not install, especially since `pandas` is big. There should probably be something like an `extras_requires` section in the `setup` to facilitate opt-in for these bundles of lesser-needed dependencies, but something like that could be introduced here. It sounds like `extras_require` may be [on the way out, though](https://hynek.me/articles/conditional-python-dependencies/)

**Comment by dpryan79** [comment]
I've created a PR on plotly to fix this.

**Comment by dpryan79** [comment]
This will be resolved in plotly 2.5.0 :)

**Comment by bgruening** [comment]
Should be fix the bioconda package for the time being?

https://biostar.usegalaxy.org/p/27084/#27089

**Comment by dpryan79** [comment]
Grudgingly I guess so, since I don't know when the next plotly release will be. I'll make a PR real quick. The plotly in conda-forge hadn't been updated for a while, so folks using conda will only now be running into this.
