### ISSUE TITLE
[Feature Request]: New plotting function: Plot track

### ISSUE THREAD

**Issue by zfrenchee** [deeptools/deepTools#672]
@bgruening (and others) feel free to close this if you believe it is out of scope. 

I'd love to see a function added to this library for plotting tracks. E.g.:

![image](https://user-images.githubusercontent.com/2761597/36646313-12603ca4-1a44-11e8-8067-1e0c6ddc1c7f.png)

I know these can be visualized on a genome browser (e.g. UCSC) but I'd like to just generate images, ideally beautiful ones like the other deepTools visualization tools. 

Thanks,

**Comment by zfrenchee** [comment]
@dpryan79 you're right, that is what I'm looking for! I wish they were a little higher resolution (and took the BAMs as arguments), but this will do nicely.

**Comment by dpryan79** [comment]
Feel free to make an issue request on that repo. We can always take a look at expanding its features.

**Comment by zfrenchee** [comment]
@dpryan79 I'm not finding "pyGenomeTracks" in the Galaxy toolshed. @bgruening any advice?

**Comment by dpryan79** [comment]
Weird, I thought there was a galaxy wrapper written for that.

@fidelram was there a galaxy wrapper somewhere? If not, I'll try to write one this week.

**Comment by fidelram** [comment]
There is not wrapper yet but the wrapper for hicPlotTADs from HiCExplorer
can be use. @Alexander, using galaxy you can use this wrapper, it has some
small differences with pyGenomeTracks (mainly that height is called width)
but otherwise is fully functional.

Best,

-fidel

**Comment by zfrenchee** [comment]
@fidelram This might not be an optimal solution, since I'm not hoping to plot TADs from HiC data. @dpryan79 I would definitely much appreciate if plotting BEDs/bigwigs with pyGenomeTracks were possible on Galaxy, but I wouldn't say it's the most important thing to me.

**Comment by fidelram** [comment]
you can use hicPlotTADs without Hi-C data.. at least for the command line
version. I am not sure if the galaxy wrapper force to have Hi-C data
