### ISSUE TITLE
problem in plotting merged matrix using cbind

### ISSUE THREAD

**Issue by MengjunWu** [deeptools/deepTools#677]
I use cbind to merge several matrix, however when plotting the merged matrix,  I got a big multi column plot in which each sample still plotted individually. 

I initially understood cbind would make all sample plot in one plot and the regions will concatenated? Am I understood wrong or there is some other operations I missed to make it one plot?

Many thanks!

**Comment by dpryan79** [comment]
You're looking for `rbind` rather than `cbind`.

**Comment by MengjunWu** [comment]
I think I did not explain my question clearly. I meant to concatenated genomic regions from left to right

I applied computeMatrix scale-regions of a sample on 4 adjacent genome regions (first exon, first intron, second exon, second intron), and then I want to concatenated the 4 regions from left to right to get one plot of the footprinting on the whole 4 genome regions (from first exon to second intron).  In that way I could see the signal changes over the whole regions while keeping track of where the first exon, first intron or second exon is.

cbind could concatenated the regions from left to right, however while plotting each regions if still separated
<img width="1167" alt="screen shot 2018-03-01 at 9 39 00 pm" src="https://user-images.githubusercontent.com/17689398/36868564-0106164c-1d99-11e8-814b-3f1aa0336542.png">

How can I concatenate the four regions from left to right in one plot without any gaps

**Comment by dpryan79** [comment]
Ah, now I get what you want. There's currently no direct way to do that in deepTools. You have a couple options then:

1. Save as a PDF and use illustrator to move the columns together.
2. Modify the file output from `computeMatrixOperations cbind` such that there's only a single "sample" with ticks at the boundaries between the various regions.

I personally prefer option 2, but it'll take some trial and error to get it to work properly. You'll lose the labels over the top, but those are easy enough to add back in when you go to publish things. If you're interested in option 2, then try to make the output from `computeMatrixOperations cbind` available to me and I'll see if I can whip together a little script that can make the modifications for you.

**Comment by MengjunWu** [comment]
I will also prefer option2. Would be great if this is doable.
I have attached the output file from computeMatrixOperations cbind.
Thank you very much for the help!
[cbind_merged_matices.mat.gz](https://github.com/deeptools/deepTools/files/1772943/cbind_merged_matices.mat.gz)

**Comment by dpryan79** [comment]
This is as close as I can get to producing what you want. I can't get the ticks in, since I'd forgotten that that's not an arbitrary list. You'd then need to manually add in ticks there. If the original matrices are the same size then this isn't a big deal, but it'd be pretty tough to do otherwise.

[mergeComputeMatrixSamples.py.txt](https://github.com/deeptools/deepTools/files/1773102/mergeComputeMatrixSamples.py.txt)

Strip the .txt ending from that, since it's really a python script (github won't let me upload it otherwise). Note that this will only work with deepTools 2. If you end up needing this for deepTools 3 output too then let me know.

**Comment by MengjunWu** [comment]
Thank you a lot! I am using deepTools2 and now it worked well to get one plot. I will keep the original matrices of the same size. 

Would this functionality be considered to be included in future deepTools version?  (BTW, I noticed deepTools 3 has less detailed parameter documentation than deepTools 2, this is designed like this because one can also get the documentation by using --help ? )

Thanks again for your help!

**Comment by dpryan79** [comment]
If a bunch of folks end up wanting to do something like this then we'll implement it, but for the time being I'll leave it at this script.

The parameter documentation for deepTools 3 should be just as detailed as that for deepTools 2. Can you point to an example?

**Comment by MengjunWu** [comment]
I am looking at this, seems the parameter options are no longer there
http://deeptools.readthedocs.io/en/latest/content/tools/computeMatrix.html#details

This is the older version:
http://gensoft.pasteur.fr/docs/deepTools/2.3.1/content/tools/computeMatrix.html

this is similar for other functions like plotProfile

**Comment by dpryan79** [comment]
Oh my, well that's a problem. Looks like the sphinx-argparse module isn't working as expected. I'll open a new issue for that.
