### ISSUE TITLE
Double quoting file names in multiBamSummary wrapper

### ISSUE THREAD

**Issue by dpryan79** [deeptools/deepTools#678]
The wrapper ends up producing commands like this:

```
ln -f -s "/data/galaxy2/files/000/351/dataset_351000.dat" "Larsson MSL2 _wt__0.bw" &&
ln -f -s "/data/galaxy2/files/000/351/dataset_351001.dat" "Larsson MSL2 _roX___1.bw" &&
multiBigwigSummary BED-file  --numberOfProcessors "${GALAXY_SLOTS:-4}"  --outFileName /data/galaxy2/files/000/392/dataset_392033.dat  \
--bwfiles ''Larsson MSL2 _wt__0.bw'' ''Larsson MSL2 _roX___1.bw'' \
--labels 'Larsson MSL2 _wt_' 'Larsson MSL2 _roX__'  \
--outRawCounts '/data/galaxy2/files/000/392/dataset_392034.dat'  --BED /data/galaxy2/files/000/357/dataset_357386.dat     --transcriptID transcript --exonID exon --transcript_id_designator transcript_id
```

There are two 's on either side of the bw file names. That obviously is going to cause an error:

```
Fatal error: Exit code 1 ()
The number of labels does not match the number of bigWig files.
```

I'll take this chance to fix this in 3.0.1, due out tomorrow morning or later tonight.

**Comment by bgruening** [comment]
Also the quotes should all be single quotes and not double quotes, for example in the link command. I thought we fixed this already :(

**Comment by dpryan79** [comment]
I'll change that too real quick. I'm not terribly consistent about ' vs. ", they're essentially equivalent to me when quoting.

**Comment by dpryan79** [comment]
@bgruening Looking through the wrappers it doesn't appear that we've ever tried to standardize to single quotes (we also never did in the python code). Is there any tangible reason to do so? Otherwise I'll just fix the current bug and leave the other quotes as they are.

**Comment by bgruening** [comment]
Its only relevant on bash. `"` are evaluated and `'` not. This measn `"` are a potential security hole in the sense that a use can sneak in shell command via history names or text parameters.

**Comment by dpryan79** [comment]
OK, I'll make a hotfix for that next week.
