### ISSUE TITLE
Possible typo in plotHeatmap.py

### ISSUE THREAD

**Issue by hyweldd** [deeptools/deepTools#684]
In https://github.com/deeptools/deepTools/blob/master/deeptools/plotHeatmap.py (master branch), line 512

It looks like 

if hm.paramters['upstream'] > 0:

should be 

if hm.parameters['upstream'] > 0:

**Comment by dpryan79** [comment]
Yup, I have this fixed in `develop` already for the next bugfix release (due at the end of the month). If you need this fixed beforehand I suggest installing from the `develop` branch.

**Comment by hyweldd** [comment]
Thanks, I'll give that a try.
