### ISSUE TITLE
Passing one of 'on', 'true', 'off', 'false' as a boolean is deprecated; use an actual boolean (True/False) instead.

### ISSUE THREAD

**Issue by werhoog** [deeptools/deepTools#685]
As  said as the title:"Passing one of 'on', 'true', 'off', 'false' as a boolean is deprecated; use an actual boolean (True/False) instead."

What is wrong?
"/usr/local/lib/python2.7/dist-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning:

Passing one of 'on', 'true', 'off', 'false' as a boolean is deprecated; use an actual boolean (True/False) instead.
"

**Comment by dpryan79** [comment]
Can you `pip install --user --upgrade git+https://github.com/deeptools/deepTools@develop` and see if you still get this? I think I've fixed this warning for the next release, but it'd be good to get some independent confirmation.

BTW, there's nothing wrong here, that API for the plotting package (matplotlib) has simply changed.

**Comment by werhoog** [comment]
Yean. It really works!
Thank you !

**Comment by mbk0asis** [comment]
Hi. 
dpryan!
Are you saying it has no effect on plotting?
I'm still getting the massage after the update, and still getting the plot.
Should I just ignore it?

**Comment by dpryan79** [comment]
You can ignore warnings like this.

**Comment by MariamArabi** [comment]
Hey, 
I'am actually getting the same problem.
I receive the message error when I execute this python command :
 **mca.plot_rows_columns()**
Message error 
**Warning (from warnings module):
  File "C:\Users\marabi\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\cbook\deprecation.py", line 107
    warnings.warn(message, mplDeprecation, stacklevel=1)
MatplotlibDeprecationWarning: Passing one of 'on', 'true', 'off', 'false' as a boolean is deprecated; use an actual boolean (True/False) instead.**
I don't obtain graphics..and there is nothing in the link you gave : https://github.com/deeptools/deepTools@develop

**Comment by dpryan79** [comment]
I have no idea where the `plot_rows_columns()` command is from, it's not part of deepTools as far as I can tell.

**Comment by burcakotlu** [comment]
How to understand which line in the code gives this warning?

/home/burcak/anaconda3/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: Passing one of 'on', 'true', 'off', 'false' as a boolean is deprecated; use an actual boolean (True/False) instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
~

Thanks

**Comment by burcakotlu** [comment]
Well, I could not reproduce this warning on my laptop using python3.6.
But using python 3.7 in the cluster,  I can reproduce this warning,

**Comment by burcakotlu** [comment]
Hi, there, I'm back.
I have set up python3.7 also on my laptop to reproduce this warning.

plt.tick_params(
        axis='x',  # changes apply to the x-axis
        which='major',  # both major and minor ticks are affected
        bottom='off',  # ticks along the bottom edge are off
        top='off')  # labels along the bottom edge are off


plt.tick_params(
	axis='x',  # changes apply to the x-axis
	which='both',  # both major and minor ticks are affected
	bottom='off',  # ticks along the bottom edge are off
	top='off',  # ticks along the top edge are off
	labelbottom='off')  # labels along the bottom edge are off

After these statements I get this warning:

C:\Users\burcak\AppData\Local\Programs\Python\Python37\lib\site-packages\matplotlib\cbook\__init__.py:424: MatplotlibDeprecationWarning: 
Passing one of 'on', 'true', 'off', 'false' as a boolean is deprecated; use an actual boolean (True/False) instead.
  warn_deprecated("2.2", "Passing one of 'on', 'true', 'off', 'false' as a "

Does it help to get rid of this warning?

Thanks,
Burcak

**Comment by burcakotlu** [comment]
Well, in fact you have written the reason in the warning message.
Changing 'off' into False resolved this issue.
Thanks,
Burcak
