### ISSUE TITLE
a bug in plotCorrelation?

### ISSUE THREAD

**Issue by htpmod** [deeptools/deepTools#686]
I used plotCorrelation to plot a matrix table generated by "multiBamSummary bins". But it seems that the labels are incorrectly placed beside the heatmap. Could you check and test this? Thanks. 

.

**Comment by dpryan79** [comment]
Can you upload an example of what you're seeing and let me know (1) what version of deepTools and (2) how you installed it?

**Comment by htpmod** [comment]
Here is the command I used 
`multiBamSummary bins --numberOfProcessors 12 --binSize 5000 --bamfiles align/*.filter.bam --minMappingQuality 30 -out H3K27ac.filter.npz --outRawCounts H3K27ac.filter.tab

plotCorrelation -in H3K27ac.filter.npz --corMethod spearman --skipZeros --plotTitle "Spearman Correlation of Read Counts" --whatToPlot heatmap --colorMap coolwarm --plotNumbers -o H3K27ac.heatmap_SpearmanCorr_filter.pdf --outFileCorMatrix H3K27ac.SpearmanCorr_filter.tab --removeOutliers --zMin 0.5 --zMax 1 
`
the output files are attached: 
[H3K27ac.SpearmanCorr_plot.pdf](https://github.com/deeptools/deepTools/files/1851818/H3K27ac.SpearmanCorr_plot.pdf)

I used deeptools 2.4.1 and I think I installed it via pip.

**Comment by htpmod** [comment]
another file is missing, sorry
[Uploading H3K27ac.SpearmanCorr_filter.tab…]()

**Comment by htpmod** [comment]
Github doesn't support non-regular formatted file. Now should work
[H3K27ac.SpearmanCorr_filter.txt](https://github.com/deeptools/deepTools/files/1851845/H3K27ac.SpearmanCorr_filter.txt)

**Comment by htpmod** [comment]
Missing files: 
[H3K27ac.heatmap_SpearmanCorr_filter.pdf](https://github.com/deeptools/deepTools/files/1851850/H3K27ac.heatmap_SpearmanCorr_filter.pdf)
[H3K27ac.SpearmanCorr_filter.txt](https://github.com/deeptools/deepTools/files/1851851/H3K27ac.SpearmanCorr_filter.txt)

**Comment by dpryan79** [comment]
I think you're running into #493, which I fixed in 2.4.3

**Comment by htpmod** [comment]
OK. thanks.
