### ISSUE TITLE
Galaxy wrappers too strict when santizing regions

### ISSUE THREAD

**Issue by lparsons** [deeptools/deepTools#692]
When attempting to specify a region, Galaxy seems to sanitize the input too stringently, turning `KF297339.1` into `KF297339X1`. I frequently have chromosome identifiers with `.` in them (due to NCBI fasta files).

**Comment by dpryan79** [comment]
Can you check if adding the following to the `region_limit_operation` in `deepTools_macros.xml` solves the problem:

    <add value="."/>

You can put it after `<add value=":" />`. If that works then I'll put it in the next release (due whenever this is fixed).

**Comment by dpryan79** [comment]
I've tested the aforementioned solution locally and it resolves the problem. I'll push out version 3.0.2 today then.

**Comment by lparsons** [comment]
Thanks for the quick turnaround @dpryan79! I don't see the update on the toolshed, but perhaps that's a manual process?

**Comment by bgruening** [comment]
That is probably my mistake. Give me a sec.

**Comment by dpryan79** [comment]
@bgruening I was about to ping you :)

**Comment by bgruening** [comment]
Done :)

**Comment by lparsons** [comment]
Fantastic! Thanks guys!
