### ISSUE TITLE
No effect of --centerReads in bamCoverage

### ISSUE THREAD

**Issue by fgeier** [deeptools/deepTools#693]
Hi! 
I was trying to center PE reads to fragment midpoints, taking only the 5' end of the first read pair into account, i.e., counting only the fragment midpoint in the coverage profile . However in all cases I tried with bamCoverage there was no effect of the --centerReads option. Am I missing something?
[test.zip](https://github.com/deeptools/deepTools/files/1876193/test.zip)

**Comment by dpryan79** [comment]
Which version are you using?

**Comment by fgeier** [comment]
Sorry, I forgot to say: 3.0.0

**Comment by dpryan79** [comment]
Indeed, at the moment `--centerReads` and `--Offset` are mutually exclusive, with `--Offset` taking precedence. I guess the desired result would be to center and then take the offset of that, so I'll see if I can get that implemented for the 3.1.0 release.

**Comment by dpryan79** [comment]
This will now be supported in version 3.1.0 (due out in June).
