### ISSUE TITLE
Sense strand vs. Antisense strand

### ISSUE THREAD

**Issue by brianpenghe** [deeptools/deepTools#694]
When I'm using ComputeMatrix and PlotProfile to see coverage maps of transcriptome data, I realize that your software doesn't distinguish sense strand and antisense strand! Can you enable the programs to separate sense and antisense?

**Comment by dpryan79** [comment]
BigWig files themselves aren't stranded. However `computeMatrix` will change the orientation of genes/transcripts/features such that the are 5' -> 3' in the resulting matrix.

If you really need a stranded matrix then it's a bit of an involved process. You end up needing to make two bigWig files per sample, then either make stranded matrices with `computeMatrix` that you then merge with `computeMatrixOperations` or a large single matrix that you then subset and filter (e.g., with `computeMatrixOperations filterStrand`).

**Comment by brianpenghe** [comment]
You could take bam as input to make it stranded, otherwise the plot doesn't make biological sense

**Comment by dpryan79** [comment]
Most signals that we deal with (ChIP-seq in particular) aren't stranded.

**Comment by vivekbhr** [comment]
@brianpenghe we regularly create strand-specific profiles by simply first creating the strand-specific bigwigs (using bamCoverage `--filterRNAstrand` option) followed by computeMatrix + plotProfile on those bigwigs. You can try this option

**Comment by brianpenghe** [comment]
For ChIP-seq yes but I noticed that your program also allowed to use GTF file as input for transcriptome data plotting that's why I assumed you guys put effort in that direction as well. But never mind it's good to know that I need to write my own codes. Thanks

**Comment by brianpenghe** [comment]
Actually this ngsplot can do it. Here is the link to that issue: https://github.com/shenlab-sinai/ngsplot/issues/60#issuecomment-385695043

**Comment by kaushik-tlx** [comment]
Can anyone please describe the cumbersome method to do this? I understand I can generate 2 different bigwig files one for each strand and have different computeMatrix files and plot them separately. But is there anyway to combine the both strand data in the same plot? Just merging the computeMatrix files does not accomplish this correct?

**Comment by dpryan79** [comment]
Merging the matrix does do that. I recommend putting them side by side.

**Comment by kaushik-tlx** [comment]
I have a signal that should peak around promoter region and I am able to see that if I just plot forward strand annotations, but when I separately plot just the reverse strand annotations, there is no signal near the TSS. I thought for the minus strand annotation the coverage will be reversed, so that the signal would still peak around the TSS. Am I assuming wrong?

**Comment by dpryan79** [comment]
I would have assumed the same thing, what is the nature of the signal? That is, what sort of technic where you using to generate the data?

**Comment by kaushik-tlx** [comment]
I am looking at both RNA-seq reads and sRNA-seq reads that we know are dependent on mRNAs. When I said I promoter I meant more like the transcriptional start sites. 
I am using a bed file in the computeMatrix with the 6th column denoting strand of the annotation. 
I have so far not tried merging the matrix files, just dealing with them separately. 
The annotation file used in both computeMatrix file is the same, only the bigwig file changes (separate for forward and reverse).

**Comment by dpryan79** [comment]
That's quite odd, since you'd expect each bigWig file to be appropriate for about half of the genes (assuming they're evenly split between strands) and therefore similar signal profiles from both. If you make a strand-unspecific bigWig do you see enrichment? If you make a heatmap of your + strand bigWig, is it just a couple regions driving the signal or a more generalized enrichment across regions?

**Comment by kaushik-tlx** [comment]
I must have had some errors during the sRNA analysis and I plan to look into it. But I did a fresh re-do of the RNA-seq analysis and it works as expected!! Really appreciate your time and help. Thanks a bunch.

**Comment by reddeery** [comment]
Hi，I also some question about this problem. When I use reverse strand file, should I exchange the 2th and 3th column in the reverse strand bed file?
like this ?
>`chr1    1051736 1017198 54991   *       -`

**Comment by dpryan79** [comment]
No, you don't need to swap the columns, the BED file would then be invalid. deepTools handles this internally appropriately.

**Comment by Rseq** [comment]
Sorry to bring up this here again, but I haven't been able to reproduce metagene plots in a strand-specific manner.
Can someone please help me?

First, I used bowtie2 to map and selected forward and reverse reads with samtools:

```
samtools view  -b -h -F 4 -f 16 -o file_rev_strands.bam $file_both_strands.bam
  samtools view  -b -h -F 4 -F 16 -o file_for_strands.bam $file_both_strands.bam

```
I sorted and indexed later with samtools and the bedgraph looks fine.

Then I tried to plot the metagene with the following command:

```
/anaconda3/bin/computeMatrix reference-point --upstream 1500 -S file_for.bam file_rev.bam file+RNA_for.bam file+RNA_rev.bam -p max -R /Genomes_ref/annotation/genes_files/Refseq_genes_strand_orientation.bed -o matrix_strands_Refseq_genes_hg19

/anaconda3/bin/plotProfile --perGroup -m matrix_strands_Refseq_genes_hg19 --plotType se  --samplesLabel sense anti-sense sense+RNAH anti-sense+RNAH --legendLocation upper-right  -out matrix_strands_Refseq_genes_hg19.png
```
-R = all Refseq NM_* genes with strand info at 6th column

![matrix_strands_Refseq_genes_hg19_plot](https://user-images.githubusercontent.com/32098560/87654998-f2559a80-c757-11ea-9e3d-866b748c8697.png)

Running computeMatrix for each file and later combining the matrix did not work either.

the correct metagene plot would be something like this:
<img width="202" alt="Screen Shot 2020-07-16 at 11 39 46" src="https://user-images.githubusercontent.com/32098560/87655953-267d8b00-c759-11ea-9b40-5197f07914cb.png">

Any ideas what could be wrong here?

**Comment by amwa** [comment]
Also sorry to bring this up again, but could someone clarify what is meant by "ComputeMatrix will change the orientation of genes/transcripts/features such that the are 5' -> 3' in the resulting matrix"? 

I made two heatmaps using computematrix, with input bigwigs = plus and minus strand RNA-Seq signal, and input features = a set of transcribed genes. I saw an elevation in signal in the "plus" direction (right side of the heatmap) across all genes-- regardless of whether I was looking at plus or minus strand transcriptional signal, and regardless of the direction in which the genes were transcribed. Is this expected? I would imagine that even if computematrix changes the orientation of features to be 5'-3', minus strand RNA-Seq signal for minus strand genes would show an elevation in the signal on the left side of the heatmap, not the right.

**Comment by dpryan79** [comment]
@amwa This is expected. If a gene is on the - strand the signal is reversed such that signal arising from all genes (regardless of strand!) are comparable. There is **_absolutely no need_** to separate genes on different strands. If you saw an increase in signal in the 3' (TSS) end of genes on the plus strand then you should expect to see the same on those on the minus strand.

**Comment by amwa** [comment]
I see, thanks!

**Comment by robertfisher002** [comment]
I am using deeptools to plot PROseq data centered at dominant TSS's. I notice when I make the plot with plotProfile, I get a peak just upstream of the TSS. I believe these are antisense reads and I was wondering if there is a way with deeptools to plot antisense reads as negative values within the same plot? Thank you! All of the documentation has been super helpful. 

![github](https://github.com/deeptools/deepTools/assets/90728516/5fc3246d-1dcb-4ded-965c-f9e447f3bf5d)

**Comment by snardeli** [comment]
Hej @robertfisher002, did you find an approach for sense and antisense. RNA metaplots?

**Comment by robertfisher002** [comment]
Not with deeptools. You could try HOMER's heatmap option or https://github.com/AdelmanLab/NIH_scripts/tree/main/make_heatmap

**Comment by pwh124** [comment]
Hi all,

Sorry to jump on this thread, but it was the only place I saw an answer.

Is the fact that "ComputeMatrix will change the orientation of genes/transcripts/features such that the are 5' -> 3' in the resulting matrix" documented somewhere in the deeptools manual?

I was unaware (and probably others are too) that this happens. It caused a signal to be masked when I was looking at stranded CTCF motifs.

Did I just miss this in the documentation? Could this be made more explicit somewhere in the documentation, if not?

Paul
