### ISSUE TITLE
alignmentSieve to shift ATAC-seq

### ISSUE THREAD

**Issue by kevin199011** [deeptools/deepTools#696]
Hi, I'm using alignmentSieve to shift ATAC-seq. I have two questions.
1. Does the bam file need to be sorted by name or chromosome? Or either is OK?
2. I run a example data and noticed that the the -strand is not subtracted by 5bp. Below is the example. Could you please let me know why?
Before shifting:
SRR5839478.4902655	99	chr1	13052	30	50M	=	13085	79
SRR5839478.4902655	147	chr1	13085	30	46M	=	13052	-79

After shifting:
SRR5839478.4902655	99	chr1	13056	30	46M	=	13085	70	*	*
SRR5839478.4902655	147	chr1	13085	30	41M	=	13056	-70	*	*

Thank you a lot!

Kevin

**Comment by dpryan79** [comment]
1. deepTools only accepts coordinate sorted BAM files (you'll need it to be indexed too).
2. It was decreased by 5 bases, the CIGAR string went from `46M` to `41M`. Th
