### ISSUE TITLE
read coverage for CPM

### ISSUE THREAD

**Issue by sklasfeld** [deeptools/deepTools#706]
I normalize my reads using --normalizeUsing CPM. However, I noticed that the read coverage counts are slightly different then what I expected. For example, I have 31,460,918 counts so deeptools should be normalizing by 31,460,919 reads per million. However it is instead normalizing by 31,785,500 reads per million. Where does this different number come from? I used `samtools view -c -F 0x904 input.bam` to get the number of mapped read counts.

**Comment by dpryan79** [comment]
Were you doing any filtering with `bamCoverage` or `bamCompare`? Both estimate the number of reads that will end up being used, and that won't be exact by default. In the upcoming 3.1.0 I've added the `--exactScaling` option to the aforementioned commands in case you need exactly computed scaling factors. In most cases such a small error (~1% in your case) isn't enough to matter.

**Comment by sklasfeld** [comment]
No I didn't so any filtering and either way it came out with more reads than expected. Thanks for the quick feedback!

**Comment by dpryan79** [comment]
Interesting, can you make the BAM file available (you can do so privately, in case it's sensitive data) and post the exact command used and the version of deepTools? It sounds like something odd is going on with the code.

**Comment by vivekbhr** [comment]
The different counts could come from the sampling of the genome used to estimate depth. IDK if the difference is supposed to be this large

**Comment by dpryan79** [comment]
If there's no filtering there's no sampling (or at least there isn't supposed to be).

**Comment by sklasfeld** [comment]
version: deeptools 3.0.1-37-7c60c9e

My command:
bamCoverage --bam arabidopsisInput.bam -o arabidopsisInput.bg --binSize 1 -of bedgraph -e 138

**Comment by dpryan79** [comment]
Closing for the time being. Let me know if you can make the BAM file available, at which point we can try to reproduce the issue.
