### ISSUE TITLE
bamCoverage slow on highly fragmented genome assemblies

### ISSUE THREAD

**Issue by MikeAxtell** [deeptools/deepTools#711]
First of all, thanks for deepTools, it's great!

I noticed that bamCoverage (3.0.2) is terribly slow when processing a BAM file from a highly fragmented genome assembly (wheat: over 700,000 scaffolds). In my specific use-case (aligned small RNA data), many of the scaffolds had zero alignments. From looking at the verbose output, it looks like the slowness is because bamCoverage goes one scaffold at a time, and is particularly slow for empty scaffolds. 

I got around it by pre-modifying my BAM file headers to remove @SQ lines corresponding to "empty" scaffolds (e.g. those with no aligned reads anyway).

This might be more of a comment than a bug fix or enhancement. 

Thanks!

**Comment by dpryan79** [comment]
Hi Mike,

This is a known issue without any great resolution. The deepTools code base is oriented toward making analysis of mammalian genomes relatively efficient, which produces this sort of behavior. I've seen some discussion on the SAM/BAM format list recently about making a split index format that would allow us to process BAM files like yours more efficiently, but we'll see if that new format ever comes to pass.

**Comment by shouldsee** [comment]
@MikeAxtell seems to have made a viable solution. @dpryan79 It should be simple to add a --bam-index argument for bamCoverage to skip the unmapped reads, and this would save a lot of time for people trying to reimplement @MikeAxtell 's solution with bam file

**Comment by dpryan79** [comment]
I'll reopen this and see what I can do when I have some time.

**Comment by shouldsee** [comment]
@dpryan79 In my case, I actually found a simpler solution: use RPKM instead of RPGC. It's the get_scale_factor that took most of the runtime.

**Comment by dpryan79** [comment]
I'll close this since it's covered in #729
