### ISSUE TITLE
deepTools computeMatrix for single nt reads distribution at a region around TSS

### ISSUE THREAD

**Issue by zhaotingtingdafa** [deeptools/deepTools#712]
Dear deepTools developers,

I'm currently using deepTools to compute a matrix of 5' end RNA reads distribution around TSS region, my goal is to only look at transcription start site (TSS) distribution at 401nt window around annotated TSS in different strain background. What I did is that I mapped the RNA-seq data (reads trimmed to 35nt long) from different strain background to the genome file and got the information of 5' end position for each reads representing a TSS, this information is stored in two separate bedgraph/bigwig files: position information on either forward strand or reverse strand, as follows, 4 columns are: chr start end reads_count:
chrI	5701	5702	1
chrI	5706	5707	3
chrI	6547	6548	2
chrI	6555	6556	2
chrI	6558	6559	6

I have another genomic reference file in bed format as follows, each row represent a promoter and the start and the end of the annotated TSS is shown, strand information is shown in 6th column (please ignore column 4 and 5). 
chrI	6125	6126	1	60	-
chrI	29594	29595	2	60	-
chrI	29953	29954	3	60	+
chrI	30694	30695	4	60	-

I want to use deepTools computeMatrix to extract all the reads from bigwig file and arrange them into a 401nt window that is ranging from 250 downstream and 150 upstream of annotated TSS (401nt window: 250nt-TSS-150nt). My questions are (1) do I have to computeMatrix twice by using forward or reverse strand separately because the strand information is not in my input bigwig file, if so, how should I modify the genomic bed file to get correct location information on reverse strand? (2) Instead of using computeMatrixOprations to merge two matrix files, is there any other way that I can do both strands at once? (3) I also want to normalize reads at each nt position out of 401nt sites by rowsum, how can I achieve this other than modifying deepTools scripts? 

Any suggestions will be appreciated!

Bests,

Ting

**Comment by dpryan79** [comment]
1. It's probably easiest to run `computeMatrix` twice and either subset the BED file as appropriate beforehand or use `computeMatrixOperations filterStrand` on the resulting matrix (to filter after the fact). 
2. No
3. We don't provide any facility to do this, you'll need to write a bit of python code (or use whatever other language you prefer). The matrix is just a gzipped text file with a 1 line header and 6 initial columns of region information. You can load that as you like and modify the values however you want before saving in the same gzipped text format.

**Comment by dpryan79** [comment]
It looks like this is a difference in numpy, since we end up calling `np.ma.__getattribute__(avgType)(valuesArray)` on the values in a bin (valuesArray) to get this. That does seem odd though. I'll reopen this to remind myself to have a look once I'm back in the office.

**Comment by zhaotingtingdafa** [comment]
Super quick response! Thanks!!!

**Comment by dpryan79** [comment]
I've had a look and I always get floats. This actually makes sense given that that's what's stored in the bigWig files.
