### ISSUE TITLE
Question: computeMatrix error 2018.05.26

### ISSUE THREAD

**Issue by AIBio** [deeptools/deepTools#713]
## help! Recently, when I use the conputeMatrix in deepTools, I have met some errors:

**packages information:**
deeptools                 3.0.2                    py27_0    bioconda

**Command:** 
genome_file=/home/hanwen/database/aaa-refgenomes/ref_ucsc/hg19_genome.gtf
scoreFileName_1=/home/hanwen/database/projects-chipseq/gse102460/results_deeptools/input_sorted.bw
scoreFileName_2=/home/hanwen/database/projects-chipseq/gse102460/results_deeptools/normal_sorted.bw
scoreFileName_3=/home/hanwen/database/projects-chipseq/gse102460/results_deeptools/sirna_sorted.bw
outfilename=/home/hanwen/database/projects-chipseq/gse102460/results_deeptools/allsample.mat.gz
outfilenamematrix=/home/hanwen/database/projects-chipseq/gse102460/results_deeptools/allsample_mat.tab
outfilesortedregions=/home/hanwen/database/projects-chipseq/gse102460/results_deeptools/allsample_gene.bed
computeMatrix scale-regions -R ${genome_file} -S ${scoreFileName_1} \
                            --beforeRegionStartLength 3000 --afterRegionStartLength 3000 \
                            --regionBodyLength 5000 --skipZeros \
                            --outFileName ${outfilename} --outFileNameMatrix ${outfilenamematrix} --outFileSortedRegions ${outfilesortedregions}

**Error information:**
(bioinfo2.7) [root@localhost gse102460]# bash 05.5deeptools.sh
Traceback (most recent call last):
  File "/root/anaconda2/envs/bioinfo2.7/bin/computeMatrix", line 13, in <module>
    main(args)
  File "/root/anaconda2/envs/bioinfo2.7/lib/python2.7/site-packages/deeptools/computeMatrix.py", line 421, in main
    hm.computeMatrix(scores_file_list, args.regionsFileName, parameters, blackListFileName=args.blackListFileName, verbose=args.verbose, allArgs=args)
  File "/root/anaconda2/envs/bioinfo2.7/lib/python2.7/site-packages/deeptools/heatmapper.py", line 264, in computeMatrix
    verbose=verbose)
  File "/root/anaconda2/envs/bioinfo2.7/lib/python2.7/site-packages/deeptools/mapReduce.py", line 85, in mapReduce
    bed_interval_tree = GTF(bedFile, defaultGroup=defaultGroup, transcriptID=transcriptID, exonID=exonID, transcript_id_designator=transcript_id_designator, keepExons=keepExons)
  File "/root/anaconda2/envs/bioinfo2.7/lib/python2.7/site-packages/deeptoolsintervals/parse.py", line 593, in __init__
    self.parseGTF(fp, line)
  File "/root/anaconda2/envs/bioinfo2.7/lib/python2.7/site-packages/deeptoolsintervals/parse.py", line 508, in parseGTF
    self.parseGTFexon(cols)
  File "/root/anaconda2/envs/bioinfo2.7/lib/python2.7/site-packages/deeptoolsintervals/parse.py", line 444, in parseGTFexon
    if name not in self.exons[self.labelIdx]:

That problem puzzles me for a long time, Who can help me? Thanks~~~

**Comment by AIBio** [comment]
@dpryan79 thank you for your reply. The GTF file is come from the tools table browser in the ucsc. the parameters I set in ucsc are in picture and i want to ask you a question. i use the ucsc genome annotation file in the process of mapping reads to genome, can i take advantage of other version genome annotation file in the process of deeptools analysis ??? looking forward your reply
![screenshot from 2018-05-29 08-23-41](https://user-images.githubusercontent.com/37030861/40632431-b3e22f4c-6319-11e8-9491-318f5ffe3410.png)

**Comment by dpryan79** [comment]
@AIBio I'll have a look at that GTF file and see why it's causing problems.

Yes, you can use GTF files from Ensembl or Gencode instead. Those are generally better and deepTools will try its best to handle the different chromosome names automatically.

**Comment by dpryan79** [comment]
I've found the cause, UCSC produces incorrectly formatted GTF files. They're missing `transcript` and `gene` entries, which are needed by deepTools. Ensembl and Gencode both provide correctly formatted files, I encourage you to use them instead.

**Comment by AIBio** [comment]
@dpryan79 as your advices, i try again. it works!!!! thank you for your help, sincerely.
