### ISSUE TITLE
bamCoverage using 78G of memory for a 10G bam file?

### ISSUE THREAD

**Issue by nvteja** [deeptools/deepTools#715]
Hello,

I am trying to use bamCoverage to generate a bigwig file from a BAM file that is approximately 10G in size. I noticed that my analysis keeps getting booted from the cluster queue because of memory requirements and noticed that bamCoverage is using ~78G of memory !! Here is the actual command I used.

bamCoverage --bam S76_41-1-F.bam --normalizeUsingRPKM -o S76_41-F.bigwig -of bigwig

Is this expected? Is there a way to reduce the memory consumption for bamCoverage ?

The bam file is from RNA-Seq and I am using the latest version of deeptools with python 3.5.2

Thank you,
Teja.

**Comment by vivekbhr** [comment]
@nvteja how many chromosomes you have in the bam?

**Comment by dpryan79** [comment]
What version and how many threads do you end up using? 78GB is pretty excessive.

**Comment by nvteja** [comment]
@vivekbhr 24(1.22,X,Y)
@dpryan79 Looks like the sysadmin installed an older version. upgraded to 3.0.2 but still get memory error wen I try to tun deep tools on the entire bam file. I am using 8 threads.

**Comment by dpryan79** [comment]
Can you privately make the file available? Then I can try and track down why bamCoverage is misbehaving.

**Comment by dpryan79** [comment]
I suspect I know the culprit for this and the other memory issues that are occasionally reported. It's possible that I've fixed this in https://github.com/deeptools/deepTools/commit/f374af76d451854b22061c007c209d3df51ed60e#diff-20f6026ed2b021576cf931406b741d4aR144

**Comment by murphycj** [comment]
I am encountering this memory issue too. I am using deepTools v3.1.3 with the following command:

    bamCoverage -p 2 -binSize 5      --normalizeUsing RPKM --scaleFactor 0.005      --outFileFormat bedgraph -b 4t_RNA.GRCh38.bam -o 4t_RNA.GRCh38.norm-RPM.bigwig.bg

The analysis is running on an AWS c3.8xlarge instance (36 cores and 60GB RAM). After running ~10 minutes or so it starts to use up all the memory and the server gets very slow.

The BAM file is about 5.4GB. I can give you my BAM file if you wish.

Is there anyway to control how much memory it needs? Thanks!

**Comment by dpryan79** [comment]
Can you make the file available? I can have a look at why it's using so much memory then.

**Comment by murphycj** [comment]
Thanks much appreciated! Here is the file:
https://www.dropbox.com/sh/22s2umldtbogkoy/AACS7iUJF6qTg2EOMzchER0ca?dl=0

**Comment by dpryan79** [comment]
Great, I'll have a look when I'm back in the office tomorrow.

**Comment by murphycj** [comment]
OK thanks! I'll give this a shot and let you know if I still have the memory issue
