### ISSUE TITLE
possibility to merge several bigwig (i.e. compute mean of more than 2 files)

### ISSUE THREAD

**Issue by lelouar** [deeptools/deepTools#723]
Hi deeptools team,

I have a new feature request for you. I want to merge several bigwig files into one (using mean). I know that I can use bigwigCompare but I have to re-run it for all files.

What I have done so far is to convert bw to wig, then compute mean and then reconvert file to big wig. The deeptools suite with this feature will save a lot of time and useless step.

Thanks again

**Comment by dpryan79** [comment]
I think you can do this already with wiggletools.

**Comment by lelouar** [comment]
yes, I have yet done this with wiggletools. But I have to convert to wig and reconvert to bigwig that is not an efficient way.

It's not an important feature but can save time.

**Comment by dpryan79** [comment]
wiggletools should be able to directly process the bigWig files, it uses libBigWig for this (the same as deepTools, more or less).

**Comment by lelouar** [comment]
Ok, I will try it. Sorry.

**Comment by lelouar** [comment]
for those interested to this issue:

wiggletools mean file1.bw file2.bw [fileN.bw] | wigToBigWig stdin chrom.size output.bw
