### ISSUE TITLE
convert chromosom name from ucsc to ensembl format

### ISSUE THREAD

**Issue by lelouar** [deeptools/deepTools#724]
Hi,

I'm not sure that is important, but it's something that can be needed by people. Depending on the genome browser, some people use different genome assembly repository. Unlike UCSC, ENSEMBL has prefixed the chromosome name by chr (and mitochondrial chr change from chrM to MT). So depending on the genome used for downstream analysis or when you use a genome browser, it can be needed to convert chromosome name. 

So what we have to do is to convert bigwig to wig (or bedgraph), then modify the chromosome names and reconvert to bigwig. 

So a chromosome name converter can be useful to save time and step. 

thanks

**Comment by dpryan79** [comment]
You've swapped UCSC and Ensembl, which doesn't use `chr` prefixes, but anyway I have a different repository that facilitates things like this: https://github.com/dpryan79/ChromosomeMappings

I can just post a little python script to gist if people need to convert chromosome names in bigWig files (alternatively, see the Galaxy tool). That's too simple to be an actual tool.

**Comment by lelouar** [comment]
Thank to point it out.

Indeed, it's not a big deal :). I am interested in the python script.

**Comment by dpryan79** [comment]
Here's an example script in a gist: https://gist.github.com/dpryan79/39c70b4429dd4559d88fb079b8669721

The `conversion.txt` file can be taken from https://github.com/dpryan79/ChromosomeMappings . I didn't write that script to handle chromosomes missing in the input file but present in the output, so be aware of that.
