### ISSUE TITLE
Cannot use alignmentSieve

### ISSUE THREAD

**Issue by imk1** [deeptools/deepTools#725]
I installed deepTools using anaconda, and I am unable to run alignmentSieve.  I seem to have installed version 2.5.7, which I think has this tool.  I have looked through the directories where deepTools was installed, and I could not find alignmentSieve anywhere.  It would be great if someone could help me out.  Thanks so much!

**Comment by bgruening** [comment]
Hi @imk1!

alignmentSieve is only available from deeptools3.0 onwards.

**Comment by imk1** [comment]
Thanks!
