### ISSUE TITLE
Dependencies for deepTools 3.1

### ISSUE THREAD

**Issue by imk1** [deeptools/deepTools#726]
When I install deepTools using anaconda, I automatically get version 2.5.7.  When I install deeptools=3.1, I get a list of conflicts, and changing the version of the packages that conflicted gives me more conflicts.  I have installed all of the dependencies listed in the installation section of the documentation.  Are there other dependencies that I should install?  Are there other packages that conflict with deepTools?

Thanks so much!

**Comment by dpryan79** [comment]
How are you installing deepTools?

**Comment by imk1** [comment]
I ran conda install -c bioconda deeptools=3.1

**Comment by dpryan79** [comment]
I get 3.1.0 with `conda install -c bioconda deeptools`.

**Comment by imk1** [comment]
I still get version 2.5.7.

**Comment by dpryan79** [comment]
What is the output of `python -c "import deeptools; print(deeptools.__file__)"`?

**Comment by imk1** [comment]
/home/ikaplow/anaconda2/lib/python2.7/site-packages/deeptools/__init__.pyc

**Comment by dpryan79** [comment]
Perhaps this is due to you using python 2.7, it's possible that a dependency of one of the dependencies isn't available on python 3. Try anaconda3, it'll be better for you long term anyway, since most major packages will be dropping python 2 support in January.

**Comment by imk1** [comment]
Thanks!  It would be great if you could include python 3 on your list of dependencies so that others do not experience the confusion that I experienced.

**Comment by dpryan79** [comment]
I'd rather track down why it doesn't install for you. DeepTools itself has no python 3 dependency.

**Comment by dpryan79** [comment]
I'll have a look at this tomorrow.

**Comment by imk1** [comment]
Here is the error message that I got when I ran conda install -c bioconda deeptools=3.1:
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - bioconductor-genomicranges
  - deeptools=3.1
  - r-forcats

I have bioconductor-genomicranges version 1.26.4 and r-forcats version 0.1.1.  I did not get anything when I ran conda info bioconductor-genomicranges and conda info deeptools=3.1.  Running conda info r-forcats suggested that I need r version 3.4 (I have 3.3.2) in order to upgrade r-forcats.  Is r 3.4 a dependency?  If so, it would be great if you could add it to the list.

Thanks for helping me figure this out!

**Comment by bgruening** [comment]
@imk1 part of the problem seems to be, that you are installing packages in your root environment.
Please try this: `conda create -n deeptools -c bioconda deeptools` and then change into this env with `source activate deeptools`

**Comment by dpryan79** [comment]
As @bgruening pointed out, whenever you get an error like that you can simply install the packages in a new environment with `conda create`. It's common for various things to have conflicting requirements and this conveniently solves that. Note that deepTools is not dependent on R in any way, they apparently require a different version of some dependency of a dependency in conda.

**Comment by imk1** [comment]
Thanks!  I was guessing that was the issue.

I do have the correct versions of all of the dependencies listed in the documentation.  If there are any dependencies that are not listed in the documentation, it would be great if you could add them.
