### ISSUE TITLE
TypeError in plotProfile

### ISSUE THREAD

**Issue by jma1991** [deeptools/deepTools#727]
**Software:**
deepTools 3.1.0
Python 3.6.3

**Command:**
```
$ computeMatrix reference-point --regionsFileName input.bed --scoreFileName input.bigWig --outFileName matrix.npz --referencePoint center --beforeRegionStartLength 5000 --afterRegionStartLength 5000
$ plotProfile --matrixFile matrix.npz --outFileName profile.png --outFileNameData profile.tsv --perGroup
```

**Error**
```
Traceback (most recent call last):
  File "/home/s1437643/conda/bin/plotProfile", line 12, in <module>
    main(args)
  File "/home/s1437643/conda/lib/python3.6/site-packages/deeptools/plotProfile.py", line 936, in main
    averagetype=args.averageType)
  File "/home/s1437643/conda/lib/python3.6/site-packages/deeptools/heatmapper.py", line 952, in save_tabulated_values
    fh.write("bin labels\t\t{}\n".format("\t".join(labs)))
TypeError: sequence item 499: expected str instance, NoneType found
```

**Comment by dpryan79** [comment]
Weird, can you send the matrix to me?

**Comment by jma1991** [comment]
Sure, here is a Dropbox link to the file:

https://www.dropbox.com/s/byyo9cufsjmm1ut/matrix.npz?dl=0

**Comment by dpryan79** [comment]
Yup, that's a bug. Presuming you don't want to wait a few weeks until I release version 3.1.1, you can fix this bug in the deepTools source code as follows:

1. Change line 945 in `/home/s1437643/conda/lib/python3.6/site-packages/deeptools/heatmapper.py` to:

                if x_value in xticks and xtickslabel[xticks.index(x_value)]:

2. Delete `/home/s1437643/conda/lib/python3.6/site-packages/deeptools/__pycache__/heatmapper.pyc`

That will fix the problem.

BTW, congrats on being the quickest person to ever submit a but report after a new release!

**Comment by jma1991** [comment]
I don’t have this file:

/home/s1437643/conda/lib/python3.6/site-packages/deeptools/__pycache__/heatmapper.pyc

but I do have one with a similar name:

/home/s1437643/conda/lib/python3.6/site-packages/deeptools/__pycache__/heatmapper.cpython-36.pyc

Should I delete that?

Also, congratulations on the quickest bug fix I’ve ever reported!

**Comment by dpryan79** [comment]
Oops, yes, remove `/home/s1437643/conda/lib/python3.6/site-packages/deeptools/__pycache__/heatmapper.cpython-36.pyc`.

**Comment by jma1991** [comment]
Fixed, you can go ahead and close the issue. Many thanks Devon!
