### ISSUE TITLE
Incorrectly assigned 'missing data' in plotHeatmap

### ISSUE THREAD

**Issue by meekrob** [deeptools/deepTools#728]
Hello, I think I've found a bug in the plotHeatmap program when not using the missingDataAsZero in 
the preceding call to computeMatrix. The result shows much more missing data than is actually present, and [I've verified this by](https://www.biostars.org/p/322414/)

- inspecting both the input files (bigWig), and the matrix output by plotHeatmap --oufileNameMatrix, 
- by creating a similar plot manually in R, 
- and by comparing the output of missingDataAsZero versus not using it. 

-----------
deeptools 3.0.2

Python 3.6.2rc1

`computeMatrix reference-point --referencePoint center -S file1.bw file2.bw file3.bw file4.bw -R peaks.bed -a 500 -b 500 -o matrix.gz
`

`plotHeatmap -m $infile -o $ofile --outFileSortedRegions ${ofile/.$outformat/.bed} --sortUsing mean --outFileNameMatrix ${ofile/.$outformat/.mat} --zMin 0
`
_Where: infile=matrix.gz (output from first command); ofile=matrix.$outformat; outformat typically equals "png"_

-----------

I have several screenshots illustrating the symptoms [at my post on biostars.org](https://www.biostars.org/p/322414/), but I'm satisfied with the output from using missingDataAsZero. 

I just thought I should report my experience here, in case there is a larger issue.

**Comment by dpryan79** [comment]
Sorry I missed your post on biostars, I've replied there now.
