### ISSUE TITLE
multiBigWigSummary

### ISSUE THREAD

**Issue by thomasmanke** [deeptools/deepTools#730]
Could we have an option to summarise a bigwig files over bins or bed-files by sum, rather than the mean?

Use case: I have a bed-file of regions and would like to know the sum of restriction sites, motif occurrences, or other binary values (encoded as bigwig file).

Currently I am using multiple rounds of bigWigAverageOverBed (UCSCtools) and subsequent merging. A deepTools solution was proposed here #450, but care needs to be taken for regions that do not have any values defined in the bigwig. Currently those return Nan.

**Comment by dpryan79** [comment]
Why not use bedtools and skip making bigWigs?
