### ISSUE TITLE
Using deepTools computeMatrix output to boxplot ChIP-seq signal?

### ISSUE THREAD

**Issue by hoggdog** [deeptools/deepTools#737]
I have successfully visualised ChIP-Seq signal (from untreated vs. drug treated conditions) across particular genomic regions using 'computeMatrix scale-regions' followed by plotProfile & plotHeatmap. Would it be appropriate to also use the resulting matrix to quantify the ChIP-Seq signal in those genomic regions for the purposes of performing statistical analyses? For example, theoretically using the command:

computeMatrix scale-regions -S /untreated.bw /treated.bw -R regions.bed -b 0 -a 0 -m 1000 --binSize 200 -o /matrix.gz

This would scale all regions in 'regions.bed' to 1000bp and computes 5 bins worth of values for each region, in both the untreated and treated conditions. Accordingly, could one use the values from the matrix and compute the sum of these 5 bins to derive a total 'signal' value for each region and then perform a paired statistical test to examine differences in untreated vs. treated? If so, is it advisable to use default binSize of 10bp?

Thanks in advance

**Comment by dpryan79** [comment]
If you're going to average within a region in a sample anyway then the bin
size doesn't really matter. But anyway, sure you can use these values for
T-tests and other such things.

Devon

--
Devon Ryan, Ph.D.
Email: dpryan@dpryan.com
Data Manager/Bioinformatician
Max Planck Institute of Immunobiology and Epigenetics
Stübeweg 51
79108 Freiburg
Germany
<devon.ryan@dzne.de>
