### ISSUE TITLE
computeMatrixOperations rbind does not update "group_labels"

### ISSUE THREAD

**Issue by msbnts** [deeptools/deepTools#742]
Hi,

I have several .bed and .bigwig-files, from which I extract the values using computeMatrix. I do this separately for each combination of .bed and .bigwig, because I like to create different combinations of these matrices using computeMatrixOperations cbind/rbind and then plot with plotHeatmap or plotProfile (so I save time by not running computeMatrix more than I have to).

As a dummy-example, I have two matrices, which contain group-info in the header:
[somegenes.txt](https://github.com/deeptools/deepTools/files/2256609/somegenes.txt) > @{"group_labels": ["somegenes"], "group_boundaries":[0,3] 
[othergenes.txt](https://github.com/deeptools/deepTools/files/2256610/othergenes.txt) > @{"group_labels": ["othergenes"], "group_boundaries":[0,4]

However, when using computeMatrixOperations rbind, only the "group_boundaries" update:
`computeMatrixOperations rbind -m somegenes.txt.gz othergenes.txt.gz -o allgenes.txt.gz`
[allgenes.txt](https://github.com/deeptools/deepTools/files/2256621/allgenes.txt) >@{"group_labels":["somegenes"], "group_boundaries":[0,3,7]

When trying to plot this new matrix using plotHeatmap, this creates the error:
`AssertionError: number of group labels does not match number of groups `

Is this a bug or do I not understand the application of rbind correctly? Maybe this can be solved with a "--collapse" option or similar, to control whether to merge/collapse groups or keep them separated. I already saw this functionality mentioned for cbind in #677 to merge samples together.

Hope we can find a solution and thanks for a great tool!

Best Mette

**Comment by dpryan79** [comment]
Yup, that's a bug. Thanks for pointing that out. I'll get this fixed in a 3.1.2 bugfix release.

**Comment by msbnts** [comment]
Great, thanks for taking care of it!

**Comment by dpryan79** [comment]
This is now fixed in the develop branch and will appear in the 3.1.2 release, which should be out within the next week.
