### ISSUE TITLE
How to remove plotly warning from Galaxy wrapper?

### ISSUE THREAD

**Issue by mblue9** [deeptools/deepTools#745]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [ ] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

 - [ ] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.

 - [ ] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).

 - [ ] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).

Hello, I'm not sure if this is a deepTools issue or a Galaxy one, but in both usegalaxy.eu and our local instance I'm getting this warning below output in many datasets in the history (e.g. computematrix, heatmap). Was wondering what would be the best way to remove it?

<img width="702" alt="screen shot 2018-08-05 at 10 05 01 pm" src="https://user-images.githubusercontent.com/5591821/43685749-0b17f144-98fc-11e8-9ffa-a5d9e591140b.png">

**Comment by dpryan79** [comment]
I get that on my instance too. Basically, the galaxy user needs to have write access to it's home directory on your worker nodes. If that's the case, then the warning is no longer printed.

**Comment by mblue9** [comment]
Ok great, thanks for the info!

**Comment by datakid** [comment]
Out of interest, is there anything else that may cause this issue? 

I've had this issue reported to me, but the galaxy user "galaxy" already has write access to /home/galaxy (mode 0755).

**Comment by dpryan79** [comment]
That's the only cause I'm aware of. I really wish this warning could be suppressed, but I haven't found a way in the API to do so.

**Comment by bgruening** [comment]
@datakid do you also have /home/galaxy on your nodes where the job is running?
@dpryan79 we could make use of https://github.com/galaxyproject/galaxy/pull/5193 or set HOME=/tmp/ as a hacky way.

**Comment by dpryan79** [comment]
Hacky works for me :) The `HOME=/tmp` idea is probably the simplest, since it's just a wrapper tweak that doesn't require any changes by admins.

**Comment by bgruening** [comment]
The above PR means we just need to add the profile tag. But it also means we only support Galaxy >18.01.

**Comment by datakid** [comment]
@bgruening yes /home/galaxy is on both nodes. The only problem we can imagine is that because the /home dir is NFS mounted and quite large, it can sometimes take time to respond to requests. But once those requests have been responded to it's response rate is per normal.

**Comment by dpryan79** [comment]
Can someone experiencing this test #749 and ensure it actually resolves the issue?

**Comment by mblue9** [comment]
I can test that when we upgrade in the next few weeks (at the moment we're still in 17.09)

**Comment by datakid** [comment]
Yes, sorry, my priorities were reconfigured and galaxy got bumped.

**Comment by mblue9** [comment]
I've just tested this now in our 18.05 dev and the warning is gone 👍

**Comment by dpryan79** [comment]
Thanks @mblue9 !
