### ISSUE TITLE
Per genome/chromosome GC bias

### ISSUE THREAD

**Issue by bwlang** [deeptools/deepTools#746]
Feature request:
I’m working on a mixed genome and would like to assess the GC content of each “genome” independently since they are not expected to have the same copy number.

Would it be reasonable to add a switch to export GC bias on a per chr basis?

**Comment by dpryan79** [comment]
That's such an obscure thing to need and we aren't actively developing the GC bias tools (bug fixes only) that I don't foresee implementing this. You can, however, use the `--blackListFileName` option to have the same effect.
