### ISSUE TITLE
plotProfile title and legendLocation problems

### ISSUE THREAD

**Issue by lucacozzuto** [deeptools/deepTools#748]
Dear developers,
Using plotProfile with the option --plotTitle is still keeping the word "genes". I tried also changing the legendLocation to none but I got an error: 
```
.pyenv/versions/2.7.13/lib/python2.7/site-packages/matplotlib/legend.py:641: UserWarning:

Unrecognized location "none". Falling back on "best"; valid locations are
	right
	center left
	upper right
	lower right
	best
	center
	lower left
	center right
	upper left
	upper center
	lower center
```
I'm using the version 3.1.0.

Thanks

**Comment by dpryan79** [comment]
Yeah, matplotlib doesn't allow removing the labels like that and we don't want to make it easy for people to create plots without them anyway (you can create a PDF and then remove them from that in Illustrator). `genes` is the default group label, which you can essentially remove with `--regionsLabel " "`.
