### ISSUE TITLE
estimateScaleFactor uses Python 2.x style print

### ISSUE THREAD

**Issue by ebirn** [deeptools/deepTools#754]
Hi,
There are some print statements left, that will not allow 'estimateScaleFactor' to run in Python 3.

deepTools version: 3.1.2
Python version: 3.6.4

to reproduce, run with Python 3: estimateScaleFactor --version

output of error:
  File "/net/gmi.oeaw.ac.at/software/mendel/intel-x86_64-sandybridge-avx/software/deepTools/3.1.2-foss-2018a-Python-3.6.4/bin/estimateScaleFactor", line 19
    print detail
               ^

see code: https://github.com/deeptools/deepTools/blob/master/bin/estimateScaleFactor#L19
also saw this in lines 106 and 118

Best,
Erich

**Comment by dpryan79** [comment]
D'oh, not sure how we missed that!

**Comment by dpryan79** [comment]
This is now fixed in the `develop` branch and will be present in the next release.
