### ISSUE TITLE
Galaxy server issue

### ISSUE THREAD

**Issue by juulluu21** [deeptools/deepTools#756]
Hi,

I am having some difficulties using deepTools in the Galaxy server. I have used it many times before, however, it is now giving me error. I just wanted to run the computeMatrix followed by plotHeatmap. 
In the first step when I select the bed and bigwig file to run computeMatrix, I get this error:

_The previously selected dataset has been deleted._

I thought my bed or bw file had problem. However, I install deepTools (3.1.2) and the files seem ok as I can run computeMatrix and plotHeatmap in my local machine.

Is there a bug in Galaxy?

Thanks.

**Comment by dpryan79** [comment]
You'll need to share your history with me (ryan@ie-freiburg.mpg.de) and let me know which history item this is.

**Comment by juulluu21** [comment]
Thank you. I have sent an email to you.

**Comment by dpryan79** [comment]
This was due to Galaxy being confused by a BED file.
