### ISSUE TITLE
computeMatrix has problem with multi processors

### ISSUE THREAD

**Issue by solo7773** [deeptools/deepTools#760]
I use this tool via pbs in our cluster. Last night it did work as expected, but this morning it does not.

computeMatrix 3.1.2

Python 3.6.4 :: Anaconda, Inc.

**#PBS -l nodes=fat01:ppn=80**

R sentence that invokes the command

**system(paste0('computeMatrix scale-regions -S ', inbw, ' -R ', inbed, ' -o ', outmat, ' --regionBodyLength 400 --startLabel up200 --endLabel down200 --samplesLabel " " --binSize 1 -p max'))**

The tool works without error or warnings, but it seems not using multi processes which is assumed to be 80 in my case. I say this because when I use **qstat** to check the job status, the 'Time Use' did not soar but increased by second.

**Comment by solo7773** [comment]
I find out the reason.

If the input bed file is 3 columns format and looks like this:

chr\tstart\tend

It will use multi processes without problem.

However, if the bed file is 6 columns format and looks like this:

chr\tstart\tend\tname\t0\t+
Please be aware, **\tname\t0\t+** keeps the same throughout the bed file.

It will get troubles.

**Comment by dpryan79** [comment]
It uses multiple processors in all cases, but if you input a BED 6 file then it has to ensure the entry names are unique. If they aren't, they need to be modified as the file is read...which is a single threaded step innately.
