### ISSUE TITLE
Doubt about computeMatrix and plotHeatmap

### ISSUE THREAD

**Issue by ritamonteiro** [deeptools/deepTools#763]
Hello,

I have a doubt regarding making the matrix and plotting the heatmap. I am using one bed file and three bigwigs to compute the matrix, all using default parameters. I then use plotHeatmap using the generated matrix and the, again, default parameters. My question is whether the three heatmaps that I generated all have the same order of coordinates. Meaning, are the 'rows' are all the same positions for all the heatmaps?

I hope the question was clear. Many thanks for your help.

**Comment by dpryan79** [comment]
@ritamonteiro As long as you're giving computeMatrix all three bigWig files at the same time (e.g., `-S sample1.bw sample2.bw sample3.bw`) the heatmaps will be identically sorted. So you can rest assured that if you see a bunch of rows with high signal in one sample and low signal in another that these represent exactly the same reasons.

**Comment by ritamonteiro** [comment]
Thank you! That is definitely reassuring.
