### ISSUE TITLE
Suggestion: test paths of output files before major computations

### ISSUE THREAD

**Issue by adomingues** [deeptools/deepTools#764]
This is a bit of a silly suggestion since it is born out of my own incompetence and it has happened multiple times. Situation:

`multiBamSummary` runs for a long period of time, and when it goes on to [save the output file](https://github.com/deeptools/deepTools/blob/38cfe39e3b3c82bbc0c2013e3068bd71adc3a9cb/deeptools/multiBamSummary.py#L244) throws and error that the directory does not exist. User (me) is to blame because it should have created it before hand. However, `multiBamSummary`, and `deepTools` toolbox in general, already checks for silly users' [mistakes](https://github.com/deeptools/deepTools/blob/38cfe39e3b3c82bbc0c2013e3068bd71adc3a9cb/deeptools/multiBamSummary.py#L206) just in case. 

My suggestion is to add a test to see if the output path is writeable before proceeding with the time consuming steps, in this case `CountReadsPerBin`instead of letting run and then stop.

Cheers.

**Comment by dpryan79** [comment]
Good suggestion, some sort of `testWritable()` function early on would probably save a bunch of headaches. I'll make sure this is on the to do list.

**Comment by dpryan79** [comment]
I'll try to push out a new release with more checks for this tonight.
