### ISSUE TITLE
How can I interpret the deeptools matrix?

### ISSUE THREAD

**Issue by endrebak** [deeptools/deepTools#770]
I have created a matrix with computeMatrix.

The header is 

```
@{"upstream":[500,500],"downstream":[500,500],"body":[5000,5000],"bin size":[10,10],"ref point":[null,null],"verbose":false,"bin avg type":"mean","missing data as zero":false,"min threshold":null,"max threshold":null,"scale":1,"skip zeros":false,"nan after end":false,"proc number":48,"sort regions":"descend","sort using":"median","unscaled 5 prime":[0,0],"unscaled 3 prime":[0,0],"sample_labels":["sample_Exp1_Unsynchronized_H3K27me3_vs_merged_input","sample_Exp2_Unsynchronized_H3K27me3_vs_merged_input"],"group_labels":["0","25","50","75","100"],"sample_boundaries":[0,600,1200],"group_boundaries":[0,25785,33745,41726,49718,57721]}
```

As you see, I want 500 bases upstream/downstream and a body of size 5000.
If the bin size is 10, I'd expect 500/10 + 5000/10 + 500/10 columns, or 600. However, the matrix contains 1200 (+6 with metadata).  Is this because it includes both + and - strand?

```
zcat H3K27me3_Unsynchronized.mat.gz | head -2 | tail -n +2 | tr "\t" "\n" | wc -l
   1206   11006
```

How can I interpret each column in the matrix? Are the 50 first columns the 500 bp upstream, the next 500 columns the 5000 bp body and the last 50 columns the 500 bp the downstream for the + strand? 

The reason I am asking this is that I want to use it to do other analysis, since I think it is non-optimal practice to use one file for creating the graphs and another for doing other kinds of analyses.

**Comment by dpryan79** [comment]
You have 1200 (+6) columns due to having two samples, so 600 for each sample. The first 600 columns are for the first sample (50 upstream bins, 500 body bins, 50 downstream bin) and the next 600 columns for the second sample.

**Comment by endrebak** [comment]
Derp, thanks XD
