### ISSUE TITLE
About making heatmap using bigWig and bigBed files

### ISSUE THREAD

**Issue by bhuwankhatri11** [deeptools/deepTools#771]
Hi,
I want to draw heatmap for a histone epimark using multiple bigWig and bigBed files from Blueprint Epigenome across 62 different cell types. I am new to this tool. How can I do this?

**Comment by dpryan79** [comment]
We don't support bigBed files, so you'll have to convert that to a standard BED file. Otherwise, download the bigWig files and use `computeMatrix` and then `plotHeatmap`.

**Comment by bhuwankhatri11** [comment]
Thank you for quick response. So, you mean we need only bigWig files for plotting heatmap and I do not have to worry about bigBed or bed files? Is that right?

**Comment by dpryan79** [comment]
No, you need the bigWig files and a BED file.

**Comment by steffenheyne** [comment]
FYI: Blueprint data is also hosted on deepblue and deepTools supports data retrival from that directly 

see here 
https://deeptools.readthedocs.io/en/develop/content/feature/deepBlue.html
https://deepblue.mpi-inf.mpg.de

you might check the performance for 62 samples, but in principal it is possible

**Comment by bhuwankhatri11** [comment]
I m understanding that we can extract signal from a bigWig file for a specific region of a chromosome in bedGraph and convert back it to bigWig file. And also extract data for the corresponding region from bigBed file and convert it to bed file to use in `computeMatrix` and subsequently in `plotHeatmap` functions of deepTools. Is that right?

**Comment by steffenheyne** [comment]
I'm not sure if I get your question right, but computeMatrix needs bigwig files for the signal and bed/gtf files for the regions you want to plot

see here: https://deeptools.readthedocs.io/en/develop/content/tools/computeMatrix.html

if you have only bigbed files for the regions you want to plot, convert them to bed to use them with deepTools

If you have only bedGraph files with the signal you want to plot, convert them to bigwig before you can use them with deepTools

the region bed file will tell computeMatrix which parts to extract from the bigwig files for plotting
