### ISSUE TITLE
normalize for multiBamSummary and multiBigwigSummary

### ISSUE THREAD

**Issue by rysterzhu** [deeptools/deepTools#773]
why not multiBamSummary and multiBigwigSummary have normalize arg using RPKM; 
especially the BED-file use, how the multiBigwigSummary deal if the BED regions are unequal length?
tks

**Comment by dpryan79** [comment]
BigWigs in particular will tend to already be normalized, so we do nothing to them. `multiBamSummary` could in theory perform normalization, but in practice it's sometimes handy to see correlations/PCAs of raw signal, for which it can be used.

**Comment by rysterzhu** [comment]
Is `multiBigwigSummary BED-file` calculate the mean value of all bigwig scores which overlapped with the bed? If the bigwig scores is the ratio of treatment and input(from bamCompare), the mean score would be error, right? 
I want to calculate the rpkm of my bed, and the ratio of two rpkm, but it seems that multiBigwig & multiBamSummary not very easy to use for this.

**Comment by dpryan79** [comment]
Yes, it calculates the average score by default. The average of log2 ratios isn't error, it's essentially the geometric mean of the ratios. If you want RPKM values then get counts from multiBamSummary or featureCounts and convert those to RPKMs.

**Comment by rysterzhu** [comment]
oh, I see, log2 ratio is OK.
I firstly calculate the rpkm of treatment and input by bamCoverage, and then use multiBigwigSummary BED-file calculate the mean rpkm of treatment and input in regions, and then calculate the ratio of two rpkm in regions. Is this right? Thank you very much.

**Comment by dpryan79** [comment]
That’s correct
