### ISSUE TITLE
Using computeMatrix to calculate traveling ratio

### ISSUE THREAD

**Issue by danyajane** [deeptools/deepTools#774]
Hi, 

I am wondering if I can use computeMatrix to get the info I need to calculate traveling ratio: PolII promoter proximal density (-30bp/+300bp around TSS) divided by the PolII gene body density (+400bp (downstream from the TSS) to TES)? I can get the information around the TSS using the following:
computeMatrix reference-point -S DJM_D06.bw -R Homo_sapiens.GRCh38.94.gtf -o TSS_test.gz --outFileNameMatrix TSS_test_D06.tab --referencePoint TSS -b 30 -a 300

Is there a way for me to get the gene body information? if I use TES as the reference point I don't know how to denote the upstream as +400 downstream from the TSS. 

Also, if this is the wrong place to post this I apologize

Thank you, 
Danya

**Comment by dpryan79** [comment]
The trick is to use `scale-regions` with `--unscaled5prime 1000`. Then the gene body can be divided into two chunks with the second the portion you want. Then you have the second value for the proximal pausing metric.

**Comment by danyajane** [comment]
Thank you!

**Comment by danyajane** [comment]
Quick follow-up just to be clear, the `--unscaled5prime 1000` would exclude the region from the TSS to 1000bp downstream of the TSS from scaling and the region from 1kb to the TES would be scaled? What if I want the region from 1kb to the TES to not be scaled (like if I wanted to perform the scaling separately)?

Thank you!
