### ISSUE TITLE
what kind of normalization does plotEnrichment employ?

### ISSUE THREAD

**Issue by solo7773** [deeptools/deepTools#775]
Just reading the document, this question arose in my mind.

I carefully read its documentation page but did not find the normalization method it will used when doing enrichment calculation. In my opinion, the result could not be right if this sort of things is not considered in between sample comparison. Other tools, eg bamCompare and bigwigCompare, provide scaling options. Can anybody give more details about this tool?

**Comment by dpryan79** [comment]
Since `plotEnrichment` produces fractions, they're innately normalized.
