### ISSUE TITLE
[Enhancement?] bamCoverage output negative coverage values

### ISSUE THREAD

**Issue by goodez** [deeptools/deepTools#776]
I would like to output bigwigs for negative strand tracks which have negative values. I don't see an options for this. Is it possible to achieve this with `--samFlagInclude 16 --scaleFactor -1`?

Sorry If I answered my own question, but can someone confirm that those options would be an appropriate track for negative strand?

**Comment by dpryan79** [comment]
Give that a try, I don't think we've ever tried using a negative scale factor.

**Comment by goodez** [comment]
Seems to work just fine. Thanks!
