### ISSUE TITLE
Warning in lieu of fail for multiBamSummary for empty files

### ISSUE THREAD

**Issue by robertamezquita** [deeptools/deepTools#778]
With certain single cell datasets, when there are thousands of cells, it might be good to throw a warning rather than outright fail  when encountering an empty sam file. For example, for multiBamSummary, I would rather just have a column with all zeroes in it that failing the run. Its simple to exclude empty files, but this might be nice to avoid this extra step. Thanks!

**Comment by dpryan79** [comment]
The next release should now just print a warning for these. Note that if you use something that actually requires reads in a file (e.g., it uses them for normalization) then that will fail with a likely cryptic error message, but suspect that's not an issue for your needs.
