### ISSUE TITLE
bamCompare: pseudocount in numerator too?

### ISSUE THREAD

**Issue by endrebak** [deeptools/deepTools#784]
Would it be possible to add a pseudocount in the numerator too? Now one cannot tell the difference between 0/1 and 0/10000 when using the operation `log2`. This actually leads to some results being impossible to interpret as both are the same, namely `-inf` :)

**Comment by endrebak** [comment]
Any thoughts on this or https://github.com/deeptools/deepTools/issues/785 ? :) Happy new years, btw.

**Comment by endrebak** [comment]
Also, could you please ensure that log((chip=0)/(input!=0)) is nan or -inf?  (Point 2 in #785 785)

**Comment by endrebak** [comment]
Is there anything I can do to help? The biologists I'm working for are asking about this XD

**Comment by endrebak** [comment]
Thanks. One of the biologists in my group is experiencing a bottleneck
because of this. Not your problem though :)

**Comment by dpryan79** [comment]
This is now implemented in the `develop` branch.

**Comment by endrebak** [comment]
Thank you! :)

**Comment by endrebak** [comment]
(Note to self and others) This was the easiest way to install the develop branch:

```
pip install https://github.com/deeptools/deepTools/archive/develop.zip
```

**Comment by dpryan79** [comment]
You can also `pip install git+https://github.com/deeptools/deepTools@develop` :)

**Comment by dpryan79** [comment]
Alternatively, this is in the 3.2.0 release.
