### ISSUE TITLE
Suggestions for handling of 0-values differently in deeptools bamcompare

### ISSUE THREAD

**Issue by endrebak** [deeptools/deepTools#785]
There are several examples of 0-values in deeptools bamcompare I wish were different. (In the below examples I use ChIP for the numerator and Input to mean the denominator.)

1) Region where both ChIP = 0 and Input = 0:

ChIP / Input and log (ChIP / Input) are both (mathematically) undefined, but deeptools seems to give them the value = 0?

2) Region where ChIP = 0 and Input > 0:

ChIP / Input = 0 and log (ChIP / Input) = -Inf. It seems like deeptools gives these regions a value of 0. Is that correct?

3) Region where ChIP > 0 and Input >> 0:
 
ChIP / Input < 1 and log (ChIP / Input) << 0. This is correct, but one problem happens. We want these two examples to give comparable values (see example 2) above):

 * Region 1, with ChIP = 1 and Input = 1000
 * Region 2, with ChIP = 0 and Input = 1000

----

One immediate suggestion I have for 1) is to have a flag to remove regions in bamcompare where ChIP and Input are both 0. Or make these nan.

For 2 and 3 adding a pseudocount to the numerator would help.

**Comment by dpryan79** [comment]
After adding pseudocounts, it seems python does the following:

1. `log2(n/0) = inf`, where `n > 0`
2. `log2(0/n) = -inf`, where `n > 0`
3. `log2(0/0) = -inf`

1 makes sense, I guess 2 and 3 are arbitrary and I wouldn't expect it to be constant over time.

**Comment by dpryan79** [comment]
There will be a `--skipZeroOverZero` option in the next release. That combined with the pseudocounts should hopefully suffice for this.
