### ISSUE TITLE
plotHeatmap plots a black graph 

### ISSUE THREAD

**Issue by marencc** [deeptools/deepTools#793]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [X] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

I've calculated the matrixes for several files that I have, and then, plotHeatmapped each, but for some reason I get a "black" graph... I've tried several computeMatrix combinations from scaled-region to referencepoints, and nothing seems to be producing a correct heatmap.... 

```
for i in `ls *.bw`;
do echo $i;
computeMatrix reference-point \
--referencePoint TSS \
-b 3000 -a 2000  \
-R ./gencode.v29.annotation.gtf \
--metagene       -S ./$i          --skipZeros        -p 3 \
-o ./deeptools_Matrix/$i.gz --outFileNameMatrix ./deeptools_Matrix/$i.tab \
--outFileSortedRegions ./deeptools_Matrix/$i.bed;
done
```

 - [x] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.
[mXX@edited]$ deeptools --version
deeptools 3.1.3
[mXX@edited]$ python --version
Python 2.7.15

 - [x] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).
```
echo $sample;
plotHeatmap -m ./deeptools_Matrix/$sample \
 --colorMap RdBu \
 --heatmapHeight 100 --heatmapWidth 25 \
 -out ./deeptools_Matrix/$sample.png --sortUsing max;
done
```

 - [ ] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).
I make the .bw or .gz files available, and the .png's as well...

**Comment by dpryan79** [comment]
Please make a couple bigWig files available and the BED file you're using for your regions. My only guess is that your data is very sparse.

**Comment by marencc** [comment]
Ok. 
The bed file is the first .GTF of the https://www.gencodegenes.org/human/ I've tried to use the UCSC grh38 file, but it gave me several errors.
The bigWig files can be found at: https://www.dropbox.com/sh/sy9te2upadh91c2/AAD8MwyRCanxCrcO56D5dbIBa?dl=0

**Comment by dpryan79** [comment]
Yeah, your matrix is mostly NaN because your bigwig files are very sparse (you have signal in ~5% of the genome). My guess is that you want `--missingDataAsZero` in `computeMatrix`. Alternatively, you can tweak the `--interpolationMethod` option that `plotHeatmap` uses. Using "nearest" produces some values in your case, though I strongly suspect changing your computeMatrix command will be what you really want.

**Comment by marencc** [comment]
Many thanks, that was the correct answer. --missingDataAsZero solved the problem. Many thanks
