### ISSUE TITLE
not seeing the expected values for log2 ratio for bamCompare

### ISSUE THREAD

**Issue by mistrm82** [deeptools/deepTools#795]
Hi,

I am not sure that bamCompare is doing exactly what I think it is doing so I wanted to check to see what I might be missing.

I have attached two profile plots that I have generated with deepTools and looks as expected to me. What I want to do is get the log2 ratio of blue line (2nd image divided by the first image) and the same for the green line. And then plot the two as profile plots.

![mi-3_and_mi-7_hg19_scaled_profile](https://user-images.githubusercontent.com/6545708/51861897-635a8580-230b-11e9-81f8-51fe35c33894.png)
![mi-4_and_mi-8_hg19_scaled_profile](https://user-images.githubusercontent.com/6545708/51861898-635a8580-230b-11e9-9690-e4429c0cad0d.png)

When I do this I get the following plot which doesn't really make sense to me. So the values at the TSS make sense - bigger difference for the green line, therefore smaller ratio and more negative value (dips lower than the green).

But what about across the gene body? The difference is still larger with the green line but yet the blue line dips lower on the plot. Am I misunderstanding how the command works?

![log2ratio_hg19_noscaling_profile](https://user-images.githubusercontent.com/6545708/51863149-44a9be00-230e-11e9-9895-bd9f1686fff9.png)

Code and version info included below. Any help would be great, thanks!

Meeta

**Version Info:**
deeptools 3.1.3
Python 2.7.15 :: Anaconda, Inc.

```
# Correct order but removing scaling  
bamCompare -b1  bams/MI-4_hg19/MI-4_hg19.sorted.bam -b2 bams/MI-3_hg19/MI-3_hg19.sorted.bam -p 6  --scaleFactorsMethod None -bs 20 -o MI-4_log2ratio_MI-3_noscaling.bw

bamCompare -b1  bams/MI-8_hg19/MI-8_hg19.sorted.bam -b2 bams/MI-7_hg19/MI-7_hg19.sorted.bam -p 6 --scaleFactorsMethod None -bs 20 -o MI-8_log2ratio_MI-7_noscaling.bw

# Compute matrix 
computeMatrix scale-regions -S MI-4_log2ratio_MI-3_noscaling.bw MI-8_log2ratio_MI-7_noscaling.bw -R hg19.bed  -b 2000 -a 2000 --skipZeros -p 6 -o deeptools/log2ratio_hg19_noscaling_mat.gz --smartLabels --regionBodyLength 7000 -bs 50

plotProfile -m deeptools/log2ratio_hg19_noscaling_mat.gz -out deeptools/log2ratio_hg19_noscaling_profile.png --perGroup --plotTitle "" --samplesLabel "CDK3 mutant" "EGFP" --regionsLabel "" --colors blue green

```

**Comment by dpryan79** [comment]
I think I addressed this via email, so I'll close it.

**Comment by mistrm82** [comment]
Hi @dpryan79 I don't think I got an email for this. Do you mind resending or elaborating here? Thanks!

**Comment by dpryan79** [comment]
Oh, sorry, I was corresponding with someone via email about something similar when this issue was posted and I presumed they were related. Please have a look at the output of `plotHeatmap` with all of the samples (and the ratio between them) side by side. Usually this clarifies things. Most commonly, not getting what you expected is due to assuming the average of the ratio will be the same as the ratio of the average, which isn't the case.
