### ISSUE TITLE
plotHeatmap getting the y-axis -min and max wrong

### ISSUE THREAD

**Issue by vivekbhr** [deeptools/deepTools#797]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [x] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

 - [x] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.
**3.1.0 onwards**

 - [x] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).
**plotHeatmap** (with default options)

 - [x] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).

The min and max of Y-axis in the summary plot is not properly calculated it seems. So the summary plot looks weird.

**Comment by dpryan79** [comment]
This should now be fixed. At some point the axis sharing resulted in the limits from the first panel being applied to the others.
