### ISSUE TITLE
bamCompare blacklist computing time

### ISSUE THREAD

**Issue by jdekanter** [deeptools/deepTools#798]
Hello,

First of all, thank you for working on this great package!

I have more of a comment, than a issue. 

I was running bamCompare on CHIP-seq data with matched WGS as a background. 
We use this as we did not have CHIP-input generated for these datasets (and previous colleagues run bamCompare similarly without any issues). 
As the CHIP was mapped on hg19 without decoys (quite a couple of years back), and we did not have access to the raw data, we wanted to run bamCompare while blacklisting repeat regions, to ignore the mapping biases at among others the centrosomes. A bit of a crude method, but we did not have better options. 

The problem was that the test run burned through more than 400 CPU hours, before I killed it.
I found out that every very small regions (using the --region .... option), took very long to complete. Even comparison of 2 normal CHIP-files (5GB, just ran as a test) on a small region took quite some time. Eventually, I turned out that the whole issue was solved by deleting the --blackListFileName option. 
We used a blacklist BED of ~10000 regions. 

And, yes I know I should have tested first with a small --region and a small file, that was my mistake. 

My comment: Including the --blackListFileName option is great, I saw the original issue in which it was requested. However, I might be usefull to add a small comment in the documentation to not add too many regions/ be aware of highly increased computing time using this option. Just a suggestion! 

DeepTools version 3.1.1
Python version 2.7.12

**Comment by dpryan79** [comment]
Usually specifying a blacklist speeds things up rather than slowing them down. Can you privately make an example of this available? I'd like to avoid this sort of thing from happening.

**Comment by jdekanter** [comment]
I've sent you an email!

**Comment by dpryan79** [comment]
Thanks, I'll have a look.

**Comment by dpryan79** [comment]
The issue is mostly that your blacklist makes little sense. You should simply merge neighboring regions together, which will result in more biologically reasonable number of sites and an increase in deepTool's performance. Performance is decreased by creating a large number of very small genomic bins with few if any reads, as deepTools performance scales primarily with the number of chromosomes and their length and to a lesser extent with the actual size of the BAM files.

**Comment by jdekanter** [comment]
Ok, that is clear! I generated the file based on regions with large mapping biases in multiple WGS samples automatically. Good to know. Thanks for the quick answer and sorry for my late one.
