### ISSUE TITLE
bamCoverage throws a TypeError when effectiveGenomeSize is None

### ISSUE THREAD

**Issue by flekschas** [deeptools/deepTools#815]
This is not a critical issues, just an uncaught exception.

I am running `bamCoverage` with:

- Python 3.6.7
- deeptools 3.2.0

as follows and notice that a `TypeError` is thrown when `args.effectiveGenomeSize` is `None`:

```bash
bamCoverage -b my-fancy-chip-reads.sorted.bam -o my-fancy-chip-reads.bigWig --binSize 25 --normalizeUsing RPGC
```

It's easy to get around this error by providing an effective genome size via `--effectiveGenomeSize` but I thought it'd be nice to catch the error and tell the user that they have to provide the genome size.

The error trace:

```
Traceback (most recent call last):
  File "/Users/Fritz/miniconda3/envs/px/bin/bamCoverage", line 12, in <module>
    main(args)
  File "/Users/Fritz/miniconda3/envs/px/lib/python3.6/site-packages/deeptools/bamCoverage.py", line 160, in main
    scale_factor = get_scale_factor(args, stats)
  File "/Users/Fritz/miniconda3/envs/px/lib/python3.6/site-packages/deeptools/getScaleFactor.py", line 247, in get_scale_factor
    float(bam_mapped * fragment_length) / args.effectiveGenomeSize
TypeError: unsupported operand type(s) for /: 'float' and 'NoneType'
```

PS: Awesome tool! Keep up the good work :)

**Comment by dpryan79** [comment]
Yeah, we should probably check for that.

**Comment by dpryan79** [comment]
This is now implemented for the next release, thanks!
