### ISSUE TITLE
Is it possible to add pseudocounts and handle 0-values differently in bigwigCompare too?

### ISSUE THREAD

**Issue by endrebak** [deeptools/deepTools#816]
Thanks for implementing #784 and #785. Sometimes we also want to compare bigwigs (ie. input normalized chip1 vs input normalized chip2). Therefore, we cannot use bamcompare. Is it possible to add pseudocounts and skipZeroOverZero in bigwigCompare too?

Endre

**Comment by dpryan79** [comment]
Yeah, that seems like a logical extension.

**Comment by endrebak** [comment]
Thanks. These options really aid in understanding our data :)

**Comment by dpryan79** [comment]
This is now implemented for the next release (due out once I close one more bug).
