### ISSUE TITLE
deeptools as defined order to computeMatrix and plotHeatmap

### ISSUE THREAD

**Issue by skytguuu** [deeptools/deepTools#819]
Hi,

Recently, I tried to use deeptools to draw chip-seq heatmap. I want to used a reference bed file which is sorted as my purpose, but when I use the command:
######
computeMatrix reference-point --referencePoint center -R gene_cluster_input.bed -b 5000 -a 5000 -S H3K4me3_norm.bw -o test_compute --outFileSortedRegions test.bed
#####
I found the order of outputfile (test.bed) is not the same with "gene_cluster_input.bed". Could you give me some idea to solve this problem?

Thanks!

**Comment by dpryan79** [comment]
You'll want `--sortRegions keep`. Use the same option in `plotHeatmap`.
