### ISSUE TITLE
[featRequest] bamCoverage: convert (Err: does not have any mapped reads) to a warning 

### ISSUE THREAD

**Issue by shouldsee** [deeptools/deepTools#820]
Dear devs,

When I was testing my mapping pipeline with an arbitrary set of reads, bamCoverage returned an error 

```
## bamCoverage 3.0.2
'ALIGNMENT.sorted.bam' does not have any mapped reads. Please check that the file is properly indexed and that it contains mapped reads
```
I feel a warning may be more suitable here, since the output is mathematically well defined (all zero or all 1 depending on the normalisation). Happy for discussion.

**Comment by dpryan79** [comment]
An empty bigWig file will break the vaste majority of non-deepTools tools. Note that the most recent release will allow creating these anyway, but be warned that overwhelming majority of tools out there will not handle this (parts of deepTools won't even work).
