### ISSUE TITLE
Unable to run alignmentSieve

### ISSUE THREAD

**Issue by CB017** [deeptools/deepTools#821]
I'd be grateful for your help running alignmentSieve in deeptools.  

I'm using deeptools 3.2.0 with python 2.7.15.  

No problems with other packages within deeptools but when I try to run alignmentSieve I get the following: 

alignmentSieve.py: command not found

I installed using conda install deeptools. 

Have tried uninstalling and installing with pip and same problem.  

Many thanks!

**Comment by dpryan79** [comment]
What does `which deeptools` show?

**Comment by CB017** [comment]
Many thanks for your reply: 

/pathway/conda/conda_install/bin/deeptools

**Comment by dpryan79** [comment]
What does `python -c "import deeptools; print(deeptools.__file__)"` return?

**Comment by CB017** [comment]
/pathway/conda/conda_install/lib/python2.7/site-packages/deeptools/__init__.pyc

**Comment by dpryan79** [comment]
What about `ls /pathway/conda/conda_install/lib/python2.7/site-packages/deeptools/`

**Comment by CB017** [comment]
bamCompare.py          computeGCBias.py        correlation_heatmap.pyc     getScorePerBigWigBin.pyc  multiBamSummary.pyc     plotFingerprint.pyc  SES_scaleFactor.pyc
bamCompare.pyc         computeGCBias.pyc       correlation.py              heatmapper.py             multiBigwigSummary.py   plotHeatmap.py       test
bamCoverage.py         computeMatrix.py        correlation.pyc             heatmapper.pyc            multiBigwigSummary.pyc  plotHeatmap.pyc      utilities.py
bamCoverage.pyc        computeMatrix.pyc       countReadsPerBin.py         heatmapper_utilities.py   parserCommon.py         plotPCA.py           utilities.pyc
bamHandler.py          config                  countReadsPerBin.pyc        heatmapper_utilities.pyc  parserCommon.pyc        plotPCA.pyc          _version.py
bamHandler.pyc         correctGCBias.py        getFragmentAndReadSize.py   __init__.py               plotCorrelation.py      plotProfile.py       _version.pyc
bamPEFragmentSize.py   correctGCBias.pyc       getFragmentAndReadSize.pyc  __init__.pyc              plotCorrelation.pyc     plotProfile.pyc      writeBedGraph_bam_and_bw.py
bamPEFragmentSize.pyc  correctReadCounts.py    getRatio.py                 mapReduce.py              plotCoverage.py         readBed.py           writeBedGraph_bam_and_bw.pyc
bigwigCompare.py       correctReadCounts.pyc   getRatio.pyc                mapReduce.pyc             plotCoverage.pyc        readBed.pyc          writeBedGraph.py
bigwigCompare.pyc      correlation_heatmap.py  getScorePerBigWigBin.py     multiBamSummary.py        plotFingerprint.py      SES_scaleFactor.py   writeBedGraph.pyc

**Comment by dpryan79** [comment]
Somehow you seem to have deleted the alignmentSieve module. Deinstall deepTools and reinstall it.

**Comment by CB017** [comment]
Thank you.  I've run the following but still can't seem to access it.  

conda remove deeptools

conda install deeptools

$ which deeptools
/pathway/conda/conda_install/bin/deeptools

$ python -c "import deeptools; print(deeptools.__file__)"
/package/deeptools/2.2.2/lib/python2.7/site-packages/deeptools/__init__.pyc

$ ls /package/deeptools/2.2.2/lib/python2.7/site-packages/deeptools
bamCompare.py          computeGCBias.py        correlation_heatmap.pyc     getScorePerBigWigBin.pyc  multiBamSummary.pyc     plotFingerprint.pyc  SES_scaleFactor.pyc
bamCompare.pyc         computeGCBias.pyc       correlation.py              heatmapper.py             multiBigwigSummary.py   plotHeatmap.py       test
bamCoverage.py         computeMatrix.py        correlation.pyc             heatmapper.pyc            multiBigwigSummary.pyc  plotHeatmap.pyc      utilities.py
bamCoverage.pyc        computeMatrix.pyc       countReadsPerBin.py         heatmapper_utilities.py   parserCommon.py         plotPCA.py           utilities.pyc
bamHandler.py          config                  countReadsPerBin.pyc        heatmapper_utilities.pyc  parserCommon.pyc        plotPCA.pyc          _version.py
bamHandler.pyc         correctGCBias.py        getFragmentAndReadSize.py   __init__.py               plotCorrelation.py      plotProfile.py       _version.pyc
bamPEFragmentSize.py   correctGCBias.pyc       getFragmentAndReadSize.pyc  __init__.pyc              plotCorrelation.pyc     plotProfile.pyc      writeBedGraph_bam_and_bw.py
bamPEFragmentSize.pyc  correctReadCounts.py    getRatio.py                 mapReduce.py              plotCoverage.py         readBed.py           writeBedGraph_bam_and_bw.pyc
bigwigCompare.py       correctReadCounts.pyc   getRatio.pyc                mapReduce.pyc             plotCoverage.pyc        readBed.pyc          writeBedGraph.py
bigwigCompare.pyc      correlation_heatmap.py  getScorePerBigWigBin.py     multiBamSummary.py        plotFingerprint.py      SES_scaleFactor.py   writeBedGraph.pyc

$ alignmentSieve --h
Traceback (most recent call last):
  File "/pathway/conda/conda_install/bin/alignmentSieve", line 4, in <module>
    import deeptools.misc
ImportError: No module named misc

**Comment by dpryan79** [comment]
> /package/deeptools/2.2.2/lib/python2.7/site-packages/deeptools/init.pyc

Well there's the problem, you have a very old version of deepTools in your PATH. If you're using an environment module on a cluster then unload that deepTools version. Otherwise `rm -rf  /package/deeptools/2.2.2/lib/python2.7/site-packages/deeptools`

**Comment by CB017** [comment]
Thank you!
