### ISSUE TITLE
plotProfile doesn't apply multiple yMax/yMin when plotting --perGroup

### ISSUE THREAD

**Issue by benplm** [deeptools/deepTools#822]
When the flag --perGroup is activated, only the first of the space-separated yMin or yMax values is used for all the plots (the first value in either yMin or yMax is recycled for all plots, and each plot show the same y scale).

So when using the command `plotProfile -m matrix.gz -o profile.pdf --perGroup --yMax 2 1 1 1 2`, all 5 plots will have yMax = 2. Same for the following commands:
```
plotProfile -m matrix.gz -o profile.pdf --perGroup --yMin 1 0 0 0 1
plotProfile -m matrix.gz -o profile.pdf --perGroup --yMax 2 1 1 1 2 --yMin 1 0 0 0 1
```

It behaves as expected when omitting the `--perGroup` flag.

I'm using the following version of deeptools distributed by bioconda:
```
deeptools 3.1.3
Python 3.6.8 :: Anaconda, Inc.
```

**Comment by dpryan79** [comment]
This is no implemented for the next release, which will come out tomorrow.
