### ISSUE TITLE
Can not use plotCorrelation: Segmentation fault

### ISSUE THREAD

**Issue by dcheng1** [deeptools/deepTools#823]
deeptools 3.2.0
Python 2.7.16 :: Anaconda, Inc.

[dcheng1@brlogin1 rep10]$ plotCorrelation -h
Segmentation fault

I can use other tools but not plotCorrelation, and got error "Segmentation fault". This problem came up after I updated some packages using conda.

**Comment by dpryan79** [comment]
I'll need the input files and full command. Note that this is some issue with a dependency, rather than deepTools itself.

**Comment by dcheng1** [comment]
"plotCorrelation -h" is the full command. I got the same error no matter using an input file or not. I guess I will try uninstall and reinstall deepTools.

**Comment by dpryan79** [comment]
Yeah, make a new conda environment.
