### ISSUE TITLE
Normalization of plotHeatmap

### ISSUE THREAD

**Issue by skytguuu** [deeptools/deepTools#824]
Hi,

Recently, I tried used plotHeatmap to visulize multiple chip-seq downloaded from published papers. However, when I used plotHeatmap to visulize these data. It seemed those figures have different enrichment in TSS regions. For example, I made followed command:
##
plotHeatmap -m matrix_compute -out test.png -min 0 --keans 4
##
But the figure shows the enrichment color of left sample isn't the same with other three samples. 
![22](https://user-images.githubusercontent.com/25957174/54866606-f9ada380-4db0-11e9-85e7-1a9b0e8ae7dc.png)

I am confused about this problem，could you give me some advise? Is it need normalization?

I am looking forward your help.
Thanks,
Best,
Garen

**Comment by dpryan79** [comment]
The different amount of enrichment is presumably real, what's most obvious is that the baseline signal is a bit different across samples. That's likely due to the normalization being a bit off. You can likely tweak things a bit if that's causing problems.

**Comment by skytguuu** [comment]
Thanks for your help. Because my input was finished normalization using followed command:
 #########
bamCoverage -b k4me3.bam -bs 1000 --normalizeUsing RPGC -o k4me3_normalize.bw
bigwigCompare -b1 k4me3_treat.bw -b2 k4me3_input --operation log2 -o k4me3_ratio.bw
#########
However, the result is seems also different  background with different enrichment.
![2019-03-28 15-34-25](https://user-images.githubusercontent.com/25957174/55138714-1827ec00-516f-11e9-887a-dfef9f0098ce.png)

Could you give me help?
Thanks,
Best,
Garen

**Comment by dpryan79** [comment]
There are a few things worth testing:

1. Download a blacklist for the organism you're using. They're available for some organisms [here](https://sites.google.com/site/anshulkundaje/projects/blacklists).
2. Try `bamCompare` with SES normalization. This looks for background regions and tries to scale the signals such that they're the same there.

**Comment by skytguuu** [comment]
I am appreciated for your help. I have another question about the kmeans cluster. If I used eight group of chip-seq data, including four group k4me3 data and another four group of k27ac data, to do the computeMatrix. I was wondering the result is the same with only four group (k4me3 data) kmeans clustering? If not the same, is it better to do kmeans cluster respectively?

Thanks!
Best,
Garen

**Comment by dpryan79** [comment]
k-means clustering will use all of the samples to determine the clustering, so adding/removing groups will tend to change the results. We typically find it useful to include multiple histones in the plots and clustering.
