### ISSUE TITLE
plotCoverage over regions

### ISSUE THREAD

**Issue by dpryan79** [deeptools/deepTools#829]
This was requested via email, but it'd be nice to allow specifying regions with a BED file given to `plotCoverage`. The change should be relatively simple.

**Comment by steffenheyne** [comment]
this could serve also as base for #828 ...and integrate the missing features in plotCoverage as well!?

**Comment by dpryan79** [comment]
@steffenheyne Yeah, probably

**Comment by dpryan79** [comment]
This is now implemented for the 3.3.0 release.
