### ISSUE TITLE
Computematrix with multiple bed and bigwig files 

### ISSUE THREAD

**Issue by re2srm** [deeptools/deepTools#831]
I am new to deeptools and bioinformatics so this maybe a very basic question, but I have searched a lot and couldn’t find an answer. 

I am trying to make a profile plot for two regions and two signal files on the same plot. Lets say I have two sets of files: 1) a bed file of promoter regions and bigwig file for protein A binding signal, 2) a bed file of enhancer regions and bigwig for protein B binding signal. I run computematrix  followed by plotprofile like this:

computeMatrix reference-point -S ProteinA.bw  -R promoters.bed --referencePoint center  -a 1000000 -b 1000000  -out test.tab.gz 

computeMatrix reference-point -S Proteinb.bw  -R enhancers.bed --referencePoint center  -a 1000000 -b 1000000  -out test.tab.gz 

This gives me two separate line plots with one line showing protein A signal in the 1mb regions around promoters and the other showing protein B signal in 1mb regions around enhancers

What I want is to merge these into a single plot.  However, if I run the computeMatrix command with all four files followed by plotProfile it gives me two separate plots  each with two lines instead of one plot with two lines.

computeMatrix reference-point  -S ProteinA.bw  ProteinB.bw -R promoters.bed enhancers.bed --referencePoint center  -a 1000000 -b 1000000  -out test.tab.gz 

Would appreciate any tips on how I should go about this.

Thanks

**Comment by dpryan79** [comment]
You're looking for `computeMatrixOperations rbind`, which will allow you to combine the matrices before running `plotProfile`.

**Comment by re2srm** [comment]
Thanks a lot for the quick reply. I will try that.

**Comment by re2srm** [comment]
I think I didn't explain my question correctly. rbind followed by plotprofile is giving me a plot with a single line which seems like the average of the two original plots. What I am looking for is not averaging the values of the matrices but just displaying two lines (one from each of the original plots) in a single box.

**Comment by dpryan79** [comment]
Ah, sorry, you'll need `computeMatrixOperations relabel` on one of the matrices too

  computeMatrixOperations relabel -m enhancers.mat.gz -o enhancers2.mat.gz --groupLabels enhancers

Once the groups have different labels (`computeMatrix` produces `gene` for both) you can `rbind` them and they won't be collapsed into the same line.

**Comment by re2srm** [comment]
Great. Thanks!
