### ISSUE TITLE
plotEnrichment by gene biotype

### ISSUE THREAD

**Issue by vivekbhr** [deeptools/deepTools#832]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [x] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

I think it would be great to have a new option `--bioType` in plotEnrichment, which would produce enrichments of reads by gene biotype (available from GTF) instead of by region. Would be great to check what fraction of reads go to snRNAs/rRNAs etc.

**Comment by dpryan79** [comment]
`deeptoolsintervals` now can accept an `attributeKey` option to use arbitrary attributes. That will enable implementing this.

**Comment by dpryan79** [comment]
This is now implemented for the 3.3.0 release. Note that the option is `--attributeKey` and it can use any attribute in the GTF file.
