### ISSUE TITLE
.BED file not recognized for computeMatrix

### ISSUE THREAD

**Issue by nbruss** [deeptools/deepTools#839]
Hi

A bit new to command line and this world in general, but I'm having issues utilizing my .bed files for computeMatrix

Deep tools version: 3.2.1
Python version 3.7.3

Input command:
computeMatrix reference-point --referencePoint TSS -b 3000 -a 3000 -R LT2_4me3_0.bed -S LT2_4me3_0_full.bw --skipZeros -o matrix1_LT2_4me3_0.gz

command line output:
Traceback (most recent call last):
  File "/Users/nur/anaconda3/bin/computeMatrix", line 14, in <module>
    main(args)
  File "/Users/nur/anaconda3/lib/python3.7/site-packages/deeptools/computeMatrix.py", line 436, in main
    cmo.sortMatrix(hm, args.regionsFileName, args.transcriptID, args.transcript_id_designator, verbose=not args.quiet)
  File "/Users/nur/anaconda3/lib/python3.7/site-packages/deeptools/computeMatrixOperations.py", line 691, in sortMatrix
    raise RuntimeError('{0} does not seem to be a recognized file type!'.format(fname))
RuntimeError: LT2_4me3_0.bed does not seem to be a recognized file type!

My bed files are peaks identified using MACS2, heres the head of what the file looks like, let me know if you want me to attach it as a TXT file:

track name=LT2_4me3_0.mapq30_sorted-peaks-UCSC.bed   color=0,100,100
--
chr1 | 777619 | 780175 | peak_1
chr1 | 826241 | 828688 | peak_2
chr1 | 865367 | 866369 | peak_3
chr1 | 869576 | 870088 | peak_4
chr1 | 903800 | 905543 | peak_5
chr1 | 923601 | 924153 | peak_6
chr1 | 957781 | 961755 | peak_7
chr1 | 984029 | 984579 | peak_8
chr1 | 1012801 | 1014553 | peak_9

So I guess I'm not sure why its not recognizing my bed file? Is it formatted properly, or am I supposed to be using something entirely differently? Sorry if it's a stupid question, kind of just going through all this for the first time and learning along the way. Thanks for any help you can provide, I really appreciate it!

**Comment by nbruss** [comment]
Ah I guess to maybe answer my own question, the bed file that I'm using isn't what I need at all is it?

I'm essentially, just trying to look at enrichment centered around TSS's accumulated in a meta plot, similar to what plotHeatmap would put out centered on TSS's. So I'm thinking I need a bed file of TSS's, not the peaks that I have here, for hg38. Could you let me know if my reasoning/thought process is correct? 

And if so, how could I find a bed file like that? 

Thanks again for the help, sorry if these are stupid questions.

**Comment by dpryan79** [comment]
Your original BED file had a header line that you'd need to delete as well as all of the `|` characters that were in there. It should look like:

```
chr1    777619  780175 
chr1    826241  828688 
chr1    865367  866369 
chr1    869576  870088 
chr1    903800  905543 
chr1    923601  924153 
chr1    957781  961755 
chr1    984029  984579 
chr1    1012801 1014553
```

Regarding making a profile around the TSS, just download a GTF file from Ensembl or Gencode (deepTools supports both BED and GTF formats).

**Comment by nbruss** [comment]
Thanks for the info! I'll try that with the bed file, just to see if it works, aside from that it looks like ensembl has 4 gtf files that I can grab. 

1. abinitio.gtf.gz
2. chr.gtf.gz
3. chr_patch_hapl_scaff.gtf.gz
4. .gtf.gz

I'm assuming I just want the last one that doesn't have anything extra with it, is this correct? Thanks again man.

**Comment by dpryan79** [comment]
Options 2 or 4 are appropriate, the other two you don't want.

**Comment by nbruss** [comment]
Thank you!! Sorry if they were stupid questions. the program seems to be running now with the GTF, we'll see what it spits out.

**Comment by Sogand65** [comment]
Hi all,

I am new to these kind of analysis and appreciate any guidance on my issue here:
I have annotated .txt files that are ready for plotting and visualization and I want to use deeptools for meta-profile heatmaps and other possible tools here, since my files are all .txt and  contain all peak information with 19 columns as below:

PeakID (cmd=annotatePeaks.pl CHA-1_peaks.narrowPeak hg38) | Chr | Start | End | Strand | Peak Score | Focus Ratio/Region Size | Annotation | Detailed Annotation | Distance to TSS | Nearest PromoterID | Entrez ID | Nearest Unigene | Nearest Refseq | Nearest Ensembl | Gene Name | Gene Alias | Gene Description | Gene Type

can somebody help me with the common steps and workflow to convert .txt file to bed and bigwig files to use for further analysis like DE analysis and visualization using the deeptools?

I really appreciate any guidance.

Best
Sogand

**Comment by WardDeb** [comment]
Your bed file should have no header, and contain three (tab separated) fields; chr, start and end. As is explained above. Conversion of the txt file can be done in many different ways. `cut` and `tail` commands in unix could be one of those.

**Comment by Sogand65** [comment]
> Your bed file should have no header, and contain three (tab separated) fields; chr, start and end. As is explained above. Conversion of the txt file can be done in many different ways. `cut` and `tail` commands in unix could be one of those.

@WardDeb Thanks for replying. I wanted to keep all columns if possible in the .BED file, but I could not find specific instructions about the ordering of some of my columns (Focus Ratio/Region Size | Annotation | Detailed Annotation | Distance to TSS | Nearest PromoterID | Entrez ID | Nearest Unigene | Nearest Refseq | Nearest Ensembl | Gene Name | Gene Alias | Gene Description | Gene Type) as the others are explained in [bed](https://genome.ucsc.edu/FAQ/FAQformat.html#format1). 

Thanks,
Sogand
