### ISSUE TITLE
ATACseq CPM normalized bigWig for mono-nucleosome fragments

### ISSUE THREAD

**Issue by radio1988** [deeptools/deepTools#841]
Dear developers, 

I'm using deeptools to visualize mono-nucleosome fragment coverage for ATACseq data, by only visualizing fragments with length between 100-200bp. I'm using the attached command. My question is, how is the CPM normalization performed in deepTools. Is the library size before fragment size selection (all fragments), or after size selection (100-200bp fragments)? My guess from seeing the results is the latter, which I prefer. But I'm not sure. Thanks! 

```
       bamCoverage --bam {input} \
        -o  {output} \
        --numberOfProcessors {threads} \
        --outFileFormat bigwig \
        --normalizeUsing CPM \
        --minFragmentLength {config[minFragmentLength]} \
        --maxFragmentLength {config[maxFragmentLength]} \
        --binSize 10 \
        -e 150 &> {log}
```

**Comment by dpryan79** [comment]
As you correctly surmised, scaling factors are computed after filtering for fragment size (or MAPQ or anything else you might want to tack on regarding filtering), so thankfully you're getting what you had wanted :)

**Comment by radio1988** [comment]
Thank you!
