### ISSUE TITLE
ImportError: No module named deeptoolsintervals

### ISSUE THREAD

**Issue by semacu** [deeptools/deepTools#842]
Hi there,

To attempt to make use of the `bamCoverage` functionality `--normalizeUsing` (Possible choices: RPKM, CPM, BPM, RPGC, None), I have upgraded deeptools from 2.4.2-5-f439d22 to 3.3.0:

```bash
pip install --upgrade deeptools
```

Unfortunately, when I now run `bamCoverage` or any other deeptools command, I get the following error, e.g.:

```bash
bamCoverage

Traceback (most recent call last):
  File "/Users/martin03/sw/python/Python-2.7.12/bin/bamCoverage", line 5, in <module>
    from deeptools.bamCoverage import main
  File "/home/martin03/sw/python/Python-2.7.12/lib/python2.7/site-packages/deeptools/bamCoverage.py", line 8, in <module>
    from deeptools import writeBedGraph  # This should be made directly into a bigWig
  File "/home/martin03/sw/python/Python-2.7.12/lib/python2.7/site-packages/deeptools/writeBedGraph.py", line 8, in <module>
    from deeptools import mapReduce
  File "/home/martin03/sw/python/Python-2.7.12/lib/python2.7/site-packages/deeptools/mapReduce.py", line 2, in <module>
    from deeptoolsintervals import GTF
ImportError: No module named deeptoolsintervals
```

`deeptoolsintervals` is in fact installed however I do not understand why the deeptools commands and python are not able to import it.

```bash
pip install deeptoolsintervals

Requirement already satisfied: deeptoolsintervals in ./sw/python/Python-2.7.12/lib/python2.7/site-packages (0.1.8)
```

```python
>>> import deeptoolsintervals
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named deeptoolsintervals
```

Among other libs, in the directory `~/sw/python/Python-2.7.12/lib/python2.7/site-packages` I have the following:

```
drwxr-xr-x  2 martin03 sblab 4.0K Jun  6 17:38 deeptools
drwxr-xr-x  2 martin03 sblab 4.0K Jun  6 17:38 deepTools-3.3.0.dist-info
drwxr-xr-x  2 martin03 sblab  156 Jun  6 17:38 deeptoolsintervals-0.1.8.dist-info
```

My python version is 2.7.12

Any ideas?

**Comment by dpryan79** [comment]
Hmm, the `deeptoolsintervals` directory is missing. Please delete `deeptoolsintervals-0.1.8.dist-info` and `pip install deeptoolsintervals`. That module used to be packaged with deepTools back when 2.4 was released, but it's now its own package and I suspect `pip` got that wrong somehow.

**Comment by semacu** [comment]
Thanks @dpryan79 , now it works!
