### ISSUE TITLE
[Question] bamCoverage for scRNA-seq? 

### ISSUE THREAD

**Issue by ivanov-v-v** [deeptools/deepTools#847]
Hello! I am new to **deeptools**, so I apologize in advance if a similar question has already been asked and answered (I didn't find one). I have a BAM-file coming from singe-cell RNA-seq [10x dataset](https://support.10xgenomics.com/single-cell-gene-expression/datasets/3.0.2/5k_pbmc_v3) and I would like to split the genome into bins and get read coverage statistics **for each cell separately**.  I ran **bamCoverage** and it worked just fine but added up the counts of reads coming from different cells. So, my question is: **can _bamCoverage_ (or some other tool) output the read coverage statistics for individual cells?** Of course, I can split the BAM-file on cell barcodes, but that would create thousands of files. I would like to avoid that if possible.

**Comment by dpryan79** [comment]
I'm not aware of anything that will do that, mostly because you'd end up with thousands of bigWig files and it's unlikely that anyone would really want to try looking at that many.

**Comment by ivanov-v-v** [comment]
To be more precise, I am trying to get a matrix with cells as rows and bins as columns. 
This matrix is supposed to store read coverage for our samples, and we need it this way to meet the needs of our project. If that helps, we would like to get something like a feature matrix that CellRanger (10x software) outputs (but in case of CellRanger, the matrix entries are UMI counts while we need read counts). Of course, I can produce and merge those thousands of files (one per cell), but **that's** what I am trying to avoid by using devtools. :) Thanks for the prompt reply, by the way!

**Comment by dpryan79** [comment]
One could probably hack something together, but I wonder if there's instead a way of getting umitools to do that.

**Comment by ivanov-v-v** [comment]
Thanks, didn't think about UMI-tools, I'll check that. It doesn't do quite what we need (read counts, not UMI counts — those are already computed by CellRanger), but there may be adapt that tool to our needs
