### ISSUE TITLE
multiBamSummary: Is there a way to obtain BED names (column 4)?

### ISSUE THREAD

**Issue by jenzopr** [deeptools/deepTools#848]
Hi all,

in `multiBamSummary BED-file`, is there a way to keep column 4 from the supplied BED file(s) in the output? 

Best and thanks,
Jens

**Comment by dpryan79** [comment]
No (we only output the fields we know must be there), but the output should be in the same order as the input file, so if you need to add them in after the fact it should be straight forward.

**Comment by jenzopr** [comment]
Thanks a lot! When using multiple cores, the output is unfortunately not in the same order. I will implement a left-join afterwards, to join the fourth column.
