### ISSUE TITLE
computeGCBias : local variable 'F_gc' referenced before assignment

### ISSUE THREAD

**Issue by akshaya4r** [deeptools/deepTools#849]
It seems that there's a small error in running computeGCBias

computeGCBias -b merged.bam --effectiveGenomeSize 2701495761 --genome hg38.2bit -p 8 -freq cGCfreq.txt --biasPlot gc.png

Traceback (most recent call last):
  File "anaconda3/envs/realbase/bin/computeGCBias", line 12, in <module>
    main(args)
  File "anaconda3/envs/realbase/lib/python3.7/site-packages/deeptools/computeGCBias.py", line 712, in main
    region=args.region)
  File "anaconda3/envs/realbase/lib/python3.7/site-packages/deeptools/computeGCBias.py", line 443, in tabulateGCcontent
    if sum(F_gc) == 0:
UnboundLocalError: local variable 'F_gc' referenced before assignment

**Comment by dpryan79** [comment]
What does `samtools idxstats merged.bam` produce? The error you're seeing should only happen if there are almost no alignments or if they just happen to not be in the sampled intervals.

**Comment by akshaya4r** [comment]
Hi dpryan79,
Thanks! That makes sense. It's RRBS data with very little reads. Do you have any suggestions to compute GC bias in this case?
Here's my samtools idxstats.
10	133797422	33118	0
11	135086622	33182	0
12	133275309	32616	0
13	114364328	17210	0
14	107043718	22130	0
15	101991189	21672	0
16	90338345	32666	0
17	83257441	39370	0
18	80373285	14020	0
19	58617616	42042	0
1	248956422	61350	0
20	64444167	20938	0
21	46709983	10068	0
22	50818468	19916	0
2	242193529	49060	0
3	198295559	37486	0
4	190214555	30872	0
5	181538259	33540	0
6	170805979	32080	0
7	159345973	38854	0
8	145138636	30038	0
9	138394717	32196	0
MT	16569	70	0
X	156040895	20866	0
Y	57227415	1594	0
*	0	0	0

**Comment by dpryan79** [comment]
One very much expects GC bias with RRBS, so whatever you do don't correct for that.

Anyway, try increasing `--sampleSize` so larger and larger values (start with 100 million).

**Comment by akshaya4r** [comment]
I'm only trying to compute and visualize it.
Thanks! I'll try that.

**Comment by verne91** [comment]
Hello @dpryan79 ,

I am using computGCBias on a single cell sequencing sample, which has very low sequencing coverage (~0.01X). I got the same error and I tried to increase `sampleSize`, but it didn't work. I even tried to add that number to 3000 million.

The error message is as below:

> filter_out: None
> extra_sampling_file: None
> genome_size: 3234851260
> total_reads: 1999307
> reads_per_bp: 0.0006978907130776108
> max_reads: 11.0
> min_reads: 0.0
> computing frequencies
> stepSize: 1
> Traceback (most recent call last):
>   File "/bin/computeGCBias", line 12, in <module>
>     main(args)
>   File "/lib/python3.9/site-packages/deeptools/computeGCBias.py", line 707, in main
>     data = tabulateGCcontent(fragment_len_dict,
>   File "/lib/python3.9/site-packages/deeptools/computeGCBias.py", line 443, in tabulateGCcontent
>     if sum(F_gc) == 0:
> UnboundLocalError: local variable 'F_gc' referenced before assignment
>
