### ISSUE TITLE
computeGCBias underrepresented region assumption

### ISSUE THREAD

**Issue by ZainulArifin1** [deeptools/deepTools#850]
From what I read in the tools description, DNA polymerase highly prefer GC-rich region which causes dependency of reads amount with base percentage. The tools can fix this bias according to [Benjamini & Speed (2012)] method. Direct quotation from tool description: "It will remove reads from regions with too high coverage compared to the expected values (typically GC-rich regions) and will add reads to regions where too few reads are seen (typically AT-rich regions)."

However, from the abstract of [Benjamini & Speed (2012)], they said that both GC-rich fragments and AT-rich fragments are underrepresented in the results. This means both GC-rich and AT-rich regions are considered as regions with low reads count. This conflicts with the computeGCBias assumption which assumes GC-rich region should contain more reads due to the bias. Which of these assumptions are correct?

**Comment by dpryan79** [comment]
An AT bias is just the flip side of GC bias. DeepTools can handle both.
