### ISSUE TITLE
Readthedocs pages do not contain default settings

### ISSUE THREAD

**Issue by Haskan** [deeptools/deepTools#851]
Hi there, enjoying using the software so far but a small suggestion:

It would make using the docs much easier if the default setting for each flag were stated clearly on the readthedocs web page. I notice they are available by calling each tool in the command line, but many users find web-based docs easier, particularly for searching. At the moment there are a few default settings mentioned within the descriptions but this is not easy to find by scanning and it is not consistent.

Simply adding (default: x) to the end of the descriptions (as in command line) would be a perfect solution.

With many thanks!

**Comment by dpryan79** [comment]
Thanks for pointing this out, I definitely need to fix it!

**Comment by dpryan79** [comment]
I've fixed this just now in the `develop` version of the docs so it'll be fixed for the next release. Thanks for pointing this out, it'll help a lot of people!
