### ISSUE TITLE
alignmentSieve `--BED` didn't output bedPE format for paired-end bam file.

### ISSUE THREAD

**Issue by YichaoOU** [deeptools/deepTools#852]
I want to get bedPE file from bam file. I tried `bamtobed -bedpe`, however, in my dataset, R1 reads overlap with R2 reads, so `-bedpe` won't give me anything. Then I tried deeptools, `alignmentSieve`, it just gave me a bed file. Tried `--ATACshift`, still it was a bed file, 3 columns.

Any solutions?

Thanks,
Yichao

**Comment by dpryan79** [comment]
The BEDPE version that alignmentSieve produces is what MACS2 wants, which I understand is confusing since there are multiple BEDPE formats.

**Comment by dpryan79** [comment]
I'm not sure what actually produces the BEDPE format that you want. Do you actually need that for something? Usually BAM is more convenient.
