### ISSUE TITLE
can't computeMatrix using GTF 

### ISSUE THREAD

**Issue by freedog8** [deeptools/deepTools#854]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [x] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.
**Searched by didn't see.**

 - [x] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.
**Python 3.7.3**

 - [x] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).
computeMatrix scale-regions --regionsFileName genes.gtf --scoreFileName /usr/local/data/tagDirectory/CS_HS_MDAMB231_PolII_*/*bigWig --outFileName CS_HS_MDAMB231_PolII.matrix.gz -m 10000 -b 5000 -a 5000 -bs 50 --skipZeros --smartLabels -p 20

 - [x] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).
The following chromosome names did not match between the the bigwig files
chromosome      length
 chrUn_gl000242      43523
chr8_gl000197_random         37175
 chrUn_gl000213     164239
chr8_gl000196_random         38914
 chrUn_gl000244      39929
Traceback (most recent call last):
  File "/home/ding/.local/bin/computeMatrix", line 14, in <module>
    main(args)
  File "/home/ding/.local/lib/python2.7/site-packages/deeptools/computeMatrix.py", line 421, in main
    hm.computeMatrix(scores_file_list, args.regionsFileName, parameters, blackListFileName=args.blackListFileName, verbose=args.verbose, allArgs=args)
  File "/home/ding/.local/lib/python2.7/site-packages/deeptools/heatmapper.py", line 264, in computeMatrix
    verbose=verbose)
  File "/home/ding/.local/lib/python2.7/site-packages/deeptools/mapReduce.py", line 85, in mapReduce
    bed_interval_tree = GTF(bedFile, defaultGroup=defaultGroup, transcriptID=transcriptID, exonID=exonID, transcript_id_designator=transcript_id_designator, keepExons=keepExons)
  File "/home/ding/.local/lib/python2.7/site-packages/deeptoolsintervals/parse.py", line 593, in __init__
    self.parseGTF(fp, line)
  File "/home/ding/.local/lib/python2.7/site-packages/deeptoolsintervals/parse.py", line 508, in parseGTF
    self.parseGTFexon(cols)
  File "/home/ding/.local/lib/python2.7/site-packages/deeptoolsintervals/parse.py", line 444, in parseGTFexon
    if name not in self.exons[self.labelIdx]:
IndexError: list index out of range

here is the gtf file [genes.GTF.txt](https://github.com/deeptools/deepTools/files/3435830/genes.GTF.txt)

**Comment by dpryan79** [comment]
There don't appear to be any transcript or gene entries in the file, making it an invalid GTF file.

**Comment by freedog8** [comment]
The GTF is part of hg19 refGene gtf download form UCSC. Is there any suggestion to convert it?

**Comment by dpryan79** [comment]
I'd recommend downloading one from Gencode instead. DeepTools will mostly handle the chromosome naming differences and that will (A) be better quality than anything you'd get from UCSC and (B) have an actual version attached to it (it's unlikely that there was ever just a single hg19 annotation from UCSC).
