### ISSUE TITLE
Same height at TSS and TES

### ISSUE THREAD

**Issue by xpan1** [deeptools/deepTools#857]
Hi, I have been using deeptools for different histone chip-seq data, and found out all of the    
  chip-seq data have the similar distribution in TSS and TES (similar y-axis), I feel like weird, it    
  shouldn't happen in my understanding. I attached my output below. Could anybody tell me what I 
  did wrong? Thanks a lot!  
- [ ] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.
   deeptools 3.2.1; python 3.6.5
 - [ ] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).
   bamCompare -b1 rep1_sorted.bam -b2 rep1_input_sorted.bam -o rep1.bw
   computeMatrix scale-regions -p max -S rep1_.bw -R genome.bed --beforeRegionStartLength 
   1000 --afterRegionStartLength 1000 --regionBodyLength 2000 --skipZeros -bs 1 -o 
   rep1_gene_updown1k.mat.gz
   plotProfile -m rep1_gene_updown1k.mat.gz -out rep1_gene_updown1k_profile.png
 - [ ] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).
![image](https://user-images.githubusercontent.com/31250663/62585076-f69ce680-b86b-11e9-94f5-1198fd68be89.png)

**Comment by dpryan79** [comment]
My guess is that `genome.bed` doesn't have a strand column, so deepTools has to assign everything to the + strand since it can't know otherwise.

**Comment by xpan1** [comment]
okay, thanks a lot! I added the strand information, and produced different results!!
