### ISSUE TITLE
Length of time for computeMatrix to finish:

### ISSUE THREAD

**Issue by rm1238** [deeptools/deepTools#861]
Hello there,

I am trying to plot ATAC-seq signals  around the TSS (+/- 100kb) using computeMatrix and subsequently plotHeatmap. My reference file is Homo_sapiens.GRCh37.75.gtf and the code I used is this:

computeMatrix reference-point --referencePoint TSS -b 100000 -a 100000 -R Homo_sapiens.GRCh37.75.gtf -S RAS_D23_MERGE.bw --skipZeros -o matrix_RAS_D23_MERGE.gz --outFileSortedRegions regions_RAS_D23_MERGE.bed

The computer has been working nonstop for 100 hours, and I cannot see any of the output files generated yet. 

Previously I had done a test with a single bam file to plot the heatmap for signal at -3kb and + 10kb from TSS, which took about 16 hours to complete.

Is the amount of time currently being used by deeptools for this task reasonable?

Thanks,

Ricardo

**Comment by dpryan79** [comment]
That seems like excessively long, though since you're using only a single core I'm not surprised that it takes a while. Can you see (e.g., using `top`) whether it's actually running and using CPU?

**Comment by rm1238** [comment]
I did and it is using cpu and ram. Cpu at 75% and ram fluctuating between 25 to 50gb.

I am using a mac pro 6 core and 64gb.

Is there a way to speed it up or indicate how many cores to use? I have a total of 9 bw files that i would like to process.

Is using the gtf file as a reference not a good idea?

________________________________

**Comment by dpryan79** [comment]
Normally a GTF is fine, but I wonder if there's something wrong with yours. Where did you get it?

You can use the `-p` option to tell it how many cores to use.

**Comment by rm1238** [comment]
I got it from http://ftp.ensembl.org/pub/release-75/gtf/homo_sapiens/Homo_sapiens.GRCh37.75.gtf.gz

Do you think it is better to start over modifying the code to indicate how many cores or leave and see it what happens?

I tried last week on my lap top, which is of course less powerful. In the test looking at -3/+10 kb it took it about 16 hours. Then I tried basically what I wrote on the thread, except I used multiple bw, and followed the code suggested in the pertinent page of the deeptools website. The computer worked for about a week straight and then killed the process.

Any advice here would be helpful.

Thanks a lot for your time,

Ricardo



El 12 ago 2019, a las 18:50, Devon Ryan <notifications@github.com<mailto:notifications@github.com>> escribió:


Normally a GTF is fine, but I wonder if there's something wrong with yours. Where did you get it?

You can use the -p option to tell it how many cores to use.

**Comment by rm1238** [comment]
The computer killed the process. Maybe my range relative to the reference is too long

On Aug 12, 2019, at 7:02 PM, Ricardo Martinez Zamudio <rm1238@njms.rutgers.edu<mailto:rm1238@njms.rutgers.edu>> wrote:

I got it from http://ftp.ensembl.org/pub/release-75/gtf/homo_sapiens/Homo_sapiens.GRCh37.75.gtf.gz

Do you think it is better to start over modifying the code to indicate how many cores or leave and see it what happens?

I tried last week on my lap top, which is of course less powerful. In the test looking at -3/+10 kb it took it about 16 hours. Then I tried basically what I wrote on the thread, except I used multiple bw, and followed the code suggested in the pertinent page of the deeptools website. The computer worked for about a week straight and then killed the process.

Any advice here would be helpful.

Thanks a lot for your time,

Ricardo



El 12 ago 2019, a las 18:50, Devon Ryan <notifications@github.com<mailto:notifications@github.com>> escribió:


Normally a GTF is fine, but I wonder if there's something wrong with yours. Where did you get it?

You can use the -p option to tell it how many cores to use.
