### ISSUE TITLE
How are cross-bin reads assigned?

### ISSUE THREAD

**Issue by brianpenghe** [deeptools/deepTools#862]
I'm using bamCoverage to calculate the number of reads falling into each 1kb bin over a genomic region.
The output is a .bg4 file of integers. But I'm wondering if a read happens to sit at the border between two bins, how is it assigned? It has to make a decision about where to go right?

**Comment by dpryan79** [comment]
There's coverage of the read in both bins, so both receive a count from it.

**Comment by brianpenghe** [comment]
Thanks Devan
--- your loyal Deeptools fan

**Comment by brianpenghe** [comment]
> There's coverage of the read in both bins, so both receive a count from it.

By the way by coverage, you consider the full length of the read but not just the 5 prime right?
