### ISSUE TITLE
computeMatrix accept bed files with track header

### ISSUE THREAD

**Issue by auberginekenobi** [deeptools/deepTools#866]
Issue report: computeMatrix accepts BED files with the -R option. BED files may optionally come with a "track name" header; see the specification at [https://genome.ucsc.edu/FAQ/FAQformat.html](https://genome.ucsc.edu/FAQ/FAQformat.html). If I manually remove the header line of the input BED file then computeMatrix completes as expected.

 - [x] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

 - [x] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.
deeptools 3.3.0
Python 3.7.3

 - [x] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).
computeMatrix reference-point\
 --referencePoint center\
 -a 4000 -b 4000\
 -R MB095_peaks_wgs_control.bed\
 -S MB095_filterdup.pileup.bw\
 -o MB095_atac_mat.gz

 - [x] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).
Traceback (most recent call last):
  File "/home/unix/ochapman/miniconda3/envs/deeptools/bin/computeMatrix", line 14, in <module>
    main(args)
  File "/home/unix/ochapman/miniconda3/envs/deeptools/lib/python3.7/site-packages/deeptools/computeMatrix.py", line 436, in main
    cmo.sortMatrix(hm, args.regionsFileName, args.transcriptID, args.transcript_id_designator, verbose=not args.quiet)
  File "/home/unix/ochapman/miniconda3/envs/deeptools/lib/python3.7/site-packages/deeptools/computeMatrixOperations.py", line 691, in sortMatrix
    raise RuntimeError('{0} does not seem to be a recognized file type!'.format(fname))
RuntimeError: MB095_peaks_wgs_control.bed does not seem to be a recognized file type!

**Comment by dpryan79** [comment]
Ah, I thought I had handled that, but apparently not! Thanks for pointing it out.

**Comment by dpryan79** [comment]
This should be fixed in version 3.3.1, which I expect to push out today or tomorrow.
