### ISSUE TITLE
Adding the silhouette evaluation in the kmean part of hmcluster

### ISSUE THREAD

**Issue by lldelisle** [deeptools/deepTools#875]
Hi,
I was wondering if you thought about adding the silhouette evaluation, for example here:
https://github.com/deeptools/deepTools/blob/3be5af839f17393a72b10cadd8187d337812a581/deeptools/heatmapper.py#L1236-L1242

If nobody is working on it and you are interested. I would do a PR.

Lucille

**Comment by dpryan79** [comment]
This will be in the next release, which I'd like to push out this week.
