### ISSUE TITLE
bamCoverage output negative values

### ISSUE THREAD

**Issue by benxiahu** [deeptools/deepTools#878]

**Comment by dpryan79** [comment]
Hmm, I'm not sure how that's possible. Would you be able to privately make the BAM file available (you can email me at ryan@ie-freiburg.mpg.de)? I can more easily debug this then. Also, what version of deepTools are you using?

**Comment by benxiahu** [comment]
deeptools-3.2.1

**Comment by benxiahu** [comment]
oh, sorry. I can not send you the bam files.
I used the following command to extract reads counts:
peak_bw = pyBigWig.open(bigwigfile)
np.sum(peak_bw.values(cols[0], int(cols[1]), int(cols[2])))/float(n)

**Comment by dpryan79** [comment]
Sorry, but without a reproducible example I can't help you further.

**Comment by benxiahu** [comment]
the bam files were downloaded from here (https://www.synapse.org/#!Synapse:syn5691267)

**Comment by dpryan79** [comment]
In your python code for determining average signal, how is `n` set? Do the values you compute match what you see if you simply load files in IGV?

**Comment by benxiahu** [comment]
as I merged multiple bam files.  the n is the number of bam files.  I have not loaded bam files into IGV.
