### ISSUE TITLE
Add seaborn colormaps

### ISSUE THREAD

**Issue by okartal** [deeptools/deepTools#879]
Is it possible for deeptools to provide the perceptually uniform colormaps that have been added to seaborn in v0.8.0 (July 2017)? See [here](https://seaborn.pydata.org/whatsnew.html#v0-8-0-july-2017):

> Added four new colormaps, created using viscm for perceptual uniformity. The new colormaps include two sequential colormaps (“rocket” and “mako”) and two diverging colormaps (“icefire” and “vlag”). These colormaps are registered with matplotlib on seaborn import and the colormap objects can be accessed in the seaborn.cm namespace.

**Comment by dpryan79** [comment]
We use matplotlib for plotting, I don't think seaborn existed yet when deepTools was first created.

**Comment by okartal** [comment]
Yes, I am aware of that but I thought it is maybe straightforward to add something similar to the code at https://github.com/mwaskom/seaborn/blob/master/seaborn/cm.py in order to register the colormaps with matplotlib.

**Comment by dpryan79** [comment]
Ah, gotcha, I'll look into that. Thanks!

**Comment by dpryan79** [comment]
This is now implemented in the develop branch for the next release, thanks for the suggestion!
