### ISSUE TITLE
bamPEFragmentSize gives fragment sizes of 0

### ISSUE THREAD

**Issue by margeti** [deeptools/deepTools#880]
Hi,
using bamPEFragmentSize I get fragment sizes of 0. First I thought this might be due to unmapped reads so I filtered my bam files for only mapped reads, but the 0 length fragments are still there. What could this be?

I'm using deeptools version 3.3.1 with Python 3.7.3. 
My command looks like this:

bamPEFragmentSize -b sample1_capture_unass_mapped.bam sample2_capture_unass_mapped.bam sample3_capture_unass_mapped.bam sample4_capture_unass_mapped.bam -hist capture_unassembled_mapped_hist.png -p 5 --samplesLabel "sample 1" "sample 2" "sample 3" "sample 4" -T "Fragment length distribution capture unsassembled"  --maxFragmentLength 300 --distanceBetweenBins 1000  --verbose --outRawFragmentLengths raw_length.txt

When I look into the outRawFragmentLengths table it looks like this:
#bamPEFragmentSize
Size    Occurrences     Sample
0       118     sample 1
23      14      sample 1
26      2       sample 1
27      8       sample 1

**Comment by dpryan79** [comment]
Are you sure you have paired-end data?
