### ISSUE TITLE
The XXX file does not have BAM or CRAM format.

### ISSUE THREAD

**Issue by rm1238** [deeptools/deepTools#882]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

Hello,

I am having issues generating normalised bw tracks from bam files. Alignment was performed using bowtie2, and sorted and indexed with samtools. The .bam files can be opened on IGV and alignments seem fine. However, when trying to generate normalised tracks using bamCoverage I obtain the error below. The same error comes up when I use other bam files from which I have successfully generated normalised bw tracks in the past (about 3 months ago).

I work on a MacPro Late 2013 3.5Ghz 6-core with 64GB RAM.

I recently updated to macOS Catalina, wondering if the problem could come from that.

Any help would be highly appreciated.

Thanks,

 - [x] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

https://github.com/deeptools/deepTools/issues/665

 - [x] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.

deeptools 3.30. Python 2.7.16

 - [x] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).

bamCoverage -b CD8-Y-Lo_21_II_19.bam -o CD8-Y-Lo_21_II_19.bw

 - [x] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).

The file 'CD8-Y-Lo_21_II_19.bam' does not have BAM or CRAM format

**Comment by egenomics** [comment]
I have the same issue 
deeptools 3.3.0
Python 2.7.15
[pip install pysam] Requirement already satisfied: pysam in /home/jl/anaconda2/lib/python2.7/site-packages (0.15.2)

bamPEFragmentSize -hist fragmentSize.png -T "Fragment size of PE RNA-seq data" --maxFragmentLength 1000 -b 85842035e_d2c0ef975_rnaseq.Aligned.sortedByCoord.out.bam 
The file '85842035e_d2c0ef975_rnaseq.Aligned.sortedByCoord.out.bam' does not have BAM or CRAM format
