### ISSUE TITLE
Does getFragmentAndReadSize consider gap junction size?

### ISSUE THREAD

**Issue by foehnair** [deeptools/deepTools#884]
Dear developers, I have a question about `getFragmentAndReadSize`. When reporting the fragment size, does it subtract the gap junction size? For example, if a read has CIGAR `50M5000N50M` and TLEN 5500, is the fragment size 5500 or 500? Thanks.

**Comment by dpryan79** [comment]
It will report the TLEN field from the BAM/CRAM file, which will include the splicing. So 5100 in your example, rather than the 100 you likely want.
