### ISSUE TITLE
question about blacklistfile in CountReadsPerBin 

### ISSUE THREAD

**Issue by xikanfeng2** [deeptools/deepTools#885]
My code is below:
```python
import deeptools.countReadsPerBin as crpb
cr = crpb.CountReadsPerBin(["AAAGCAATCTGACGCG.sorted.rg.dedup.bam"], binLength=500000, stepSize=500000,
     ...:                            minMappingQuality=40,
     ...:                            samFlag_include=64,
     ...:                            ignoreDuplicates=True,
     ...:                            blackListFileName='test.bed'
     ...:                            )
c = cr.count_reads_in_region('chr1', 0, 249250621)
```
and the coverage in c is all zeros.
The test.bed file just contains one line "chr1 1 100" to test the blacklist function.
I am wondering whether the coverage for all bins in chr1 is zero. Based on the documentation, just the reads which are overlapped with the regions in bed file are excluded when calculating coverage.

**Comment by dpryan79** [comment]
To start debugging this I would remove the `minMappingQuality=40, samFlag_include=64, ignoreDuplicates=True` options, since it's likely that one of those is filtering everything out (I'm guessing that the minimum MAPQ is too high).

**Comment by xikanfeng2** [comment]
> To start debugging this I would remove the `minMappingQuality=40, samFlag_include=64, ignoreDuplicates=True` options, since it's likely that one of those is filtering everything out (I'm guessing that the minimum MAPQ is too high).

Thanks for your reply. When I remove the blacklistfilename paramater and keep others, the result is correct. Just add this paramater, all coverage in chr1 became zeros. Also I have tried remove other params just keep blacklistfilename, the result is same(all coverage in chr1 are zeros).

**Comment by dpryan79** [comment]
Can you send me the BED file and a small subset of the BAM file? That will make it easier to debug this.

**Comment by xikanfeng2** [comment]
The coverage for other chromosomes is correct when the bed file just have one line 
```python
chr1   10      20      region1Duplicate
```
When I added another line to bed file, like this
```python
chr1    10      20      region1Duplicate
chr2    10      30      region2Duplicate
```
The coverage for chr1 and chr2 is all-zeros and correct for other chromosomes.
I am wondering Depptools just filters all reads of whole chromosome in bed file.

**Comment by xikanfeng2** [comment]
The test bam can be found at https://github.com/rujinwang/WGSmapp/tree/master/inst/extdata with the name as AAAGCAATCTGACGCG.sorted.rg.dedup.bam. The content for test.bed is
```python
chr1    10      20      region1Duplicate
chr2    10      30      region2Duplicate
````

**Comment by xikanfeng2** [comment]
Looking forward to your further updates.

**Comment by dpryan79** [comment]
Ah, I see the issue. I suggest not using `cr.count_reads_in_region()` directly, since if the coordinates overlap a blacklisted interval they'll get ignored. What you want is to instead use `cr.run()`. The region can be specified in the initial `crpb.CountReadsPerBin` call:

```
import deeptools.countReadsPerBin as crpb
cr = crpb.CountReadsPerBin(["AAAGCAATCTGACGCG.sorted.rg.dedup.bam"],
                           binLength=500000, stepSize=500000, minMappingQuality=40,
                           region="chr1",
                           samFlag_include=64, ignoreDuplicates=True, blackListFileName='bl.bed')
c = cr.run()
```

**Comment by xikanfeng2** [comment]
Thanks for your response. So the cr.count_reads_in_region() will ignore the bins which have overlap with the regions in blacklist bed file, rather than ignoring the reads in input bams that have overlap with the regions in blacklist bed file?

**Comment by dpryan79** [comment]
Correct, it's called internally by `cr.run()` after segmenting things to exclude blacklisted regions.
