### ISSUE TITLE
Misplaced reference-point or scale-regions labels in plotHeatmap when using large binSize

### ISSUE THREAD

**Issue by benplm** [deeptools/deepTools#888]
Hi all,

I want to achieve a matrix with 500bp-long bins 1kb up- and 1kb downstram the TSS (so, 4 large bins around the TSS).

When using computeMatrix reference-point with `-a 1000 -b 1000 -bs 500` followed by plotHeatmap, the reference-point is always moved to the left (i.e. in the middle of the 2nd bin).
When using scale-regions given a bed file of 2kb windows centered on TSSs and the options `-a 0 -b 0 -m 2000 -bs 500`, the label at the 5' end is always moved to the right (in the middle of the first bin).
Also, while the 3' label is placed correctly (at the very end of the x-axis) in the profile, it is placed in the middle of the last bin in the heatmap.

Is it intended that the reference-point is placed **within** a bin, rather than **between**?
If not, is it a bug of plotHeatmap (i.e., the bins are done properly but the labels are misplaced) or is it a problem with computeMatrix (the bins aren't calculated as intended by the user)?

I'm using deeptools 3.3.0 with python 3.7.3 (bioconda/conda-forge distribution).

EDIT: I attach two examples, using 50bp or 500bp bins:
https://user-images.githubusercontent.com/34317613/69233541-61f59480-0b8d-11ea-980f-44aec3401815.png
https://user-images.githubusercontent.com/34317613/69233542-61f59480-0b8d-11ea-91a6-caa39bda115e.png

**Comment by dpryan79** [comment]
This is something that changes every matplotlib release that we always need to hack around. It looks like I need to play again with where the ticks are placed. Thanks for letting me know about this.

**Comment by benplm** [comment]
I updated deeptools and matplotlib to 3.3.1 and 3.1.2 (it was 3.1.1), and now it works properly on reference-point.
When using scale-regions, all the ticks are properly placed in the heatmap, but they are not aligned in the profile on top of it (still a big improvement).

Thank you!

**Comment by dpryan79** [comment]
This is now fixed for the next release
