### ISSUE TITLE
parameter --yAxisLabel of plotProfile doesn't work

### ISSUE THREAD

**Issue by yushengak47** [deeptools/deepTools#889]
Hello,

I tried --yAxisLabel of plotProfile to add a y axis label, but the label wasn't shown in the figure. I found it just works fine in plotHeatmap. Has anybody experience a similar issue? Thanks

The command I used:

plotProfile --matrixFile ABA.vs.EtOH.genebody.mat.gz --outFileName ABA.vs.EtOH.genebody.lineplot.png --perGroup --yAxisLabel 'Avg. counts per million reads'

Versions:

Python 3.7.3
deeptools 3.3.1
matplotlib 3.1.2

**Comment by dpryan79** [comment]
I may have forgotten to fix this in plotProfile when I fixed it in plotHeatmap. Thanks for reporting the bug.

**Comment by dpryan79** [comment]
This will be fixed in the upcoming release.
