### ISSUE TITLE
merging data for plotProfile

### ISSUE THREAD

**Issue by hy081212** [deeptools/deepTools#895]
I have a question similar to the one previously asked : 
https://github.com/deeptools/deepTools/issues/831#issue-438481772

Basically I would like to create a single profile plot for two mat.gz files generated from computeMatrix scale-regions. For two .gz files, I used two bed files and one bw file. 

computeMatrix scale-regions -R a.bed -S same.bw -o a.mat.gz
computeMatrix scale-regions -R b.bed -S same.bw -o b.mat.gz

Then I followed the suggestion. I did relabel and rebind, and plotProlfile like this : 

computeMatrixOperations relabel -m a.mat.gz -o a2.mat.gz --groupLabels newgroup
computeMatrixOperations rbind -m a2.mat.gz b.mat.gz -o output.mat.gz
plotProfile -m output.mat.gz -out out.png --perGroup  

But I get this error message when I ran plotProflie :
ValueError: Length New Label! = Original label of length

I would really appreciate if you could give any tips or comments on this. Thank you.

**Comment by dpryan79** [comment]
Can you post the output of the following?

    zcat output.mat.gz | head -n 1

That'll help me debug this.

**Comment by hy081212** [comment]
Of course. Here it's the output. 

@{"upstream":[0],"downstream":[0],"body":[1000],"bin size":[10],"ref point":[null],"verbose":false,"bin avg type":"mean","missing data as zero":false,"min threshold":null,"max threshold":null,"scale":1,"skip zeros":true,"nan after end":false,"proc number":6,"sort regions":"keep","sort using":"mean","unscaled 5 prime":[0],"unscaled 3 prime":[0],"group_labels":["newgroup","genes"],"group_boundaries":[0,32012,35766],"sample_labels":["samebw"],"sample_boundaries":[0,100]}

**Comment by dpryan79** [comment]
Hmm, what happens if you don't use `--perGroup`? Can you make the whole matrix available?

**Comment by dpryan79** [comment]
I'm perplexed by this, since the normal cause is specifying custom group labels, which you're not doing. Can you send me the matrix by email?

**Comment by hy081212** [comment]
I sent an email to your Gmail. Please let me know if you haven't received it.
