### ISSUE TITLE
Plot differential clusters between groups

### ISSUE THREAD

**Issue by vanottee** [deeptools/deepTools#896]
Very nice resource - thank you!

It seems every time I run 'plotHeatmap' it is fitting the data so that all groups (i.e. all supplied bigwig files) form identical clusters. Possibly my bigwig files are identical at every genomic coordinate tested, but it seems to do this even if I supply two opposing histone marks (H3K27ac vs H3K27me3). Is there a way to force the k-means clustering to also consider clusters where the signal intensity is high for one mark, while low for another mark (e.g. coordinates where H3K27ac is high, while H3K27me3 is absent)? 

For example, this is taken from Figure 4 of an old SeqMiner manuscript that shows an example of this differential clustering.

Thanks!!

![seqminer](https://user-images.githubusercontent.com/49768200/70482571-7a314300-1aab-11ea-9689-e01cd8a2b98f.PNG)

**Comment by dpryan79** [comment]
You'll want to use the `--kmeans` option to perform clustering of your data.

**Comment by vanottee** [comment]
Sorry, I did not make this clear - I have been using the --kmeans option. However, it seems to be making identical clusters between each of the bigwig files. I've attached my output. In contrast, the image above shows 'bivalent' loci, where it is identifying a cluster that is high for two signals (H3K4me3 & H3K27me3) but devoid of the middle signal (H3K36me3). I thought maybe if I gave the kmeans option a higher cluster number this would help, but again, all bigwig heatmaps look identical. It seems the kmeans algorithm is just clustering the first bigwig file and the others are 'following suit', rather than clustering each bigwig file independently, and then combining them into a heatmap.
![multiOrganATACatCtrlATACH3K4me3NegsitesHeatmapK10](https://user-images.githubusercontent.com/49768200/70542785-f28d1800-1b2e-11ea-8be0-1e37f46749ba.png)

**Comment by dpryan79** [comment]
You don't have any samples that show obviously different signals at any regions, so there's won't be any clusters like you want.

**Comment by sagarutturkar** [comment]
My question is related to figure above - specifically legends for kmeans clusters.

Since the cluster labels are overlapping with profile plot lines- is there any way to move those outside the box or somehow make them not overlapping?

**Comment by xubeisi** [comment]
@sagarutturkar check my pull request at https://github.com/deeptools/deepTools/pull/1078 I think that's what you asked.
