### ISSUE TITLE
heatmap looks very different when there are less regions

### ISSUE THREAD

**Issue by shokohirosue** [deeptools/deepTools#897]
Thank you for developing and maintaining a great tool.

I realized that when there are less reads, the heatmap looks much more coarse.
The heatmap on the left is made up of 24,339 regions (top: 1,601, middle: 813, bottom: 21,925) and the right one is made up of 13,204 regions (top: 932, middle: 1,125, bottom: 11,147).
I did not use clustering (I submitted three separate regions in `computeMatrix`).

![heatmap](https://user-images.githubusercontent.com/39588560/70924650-cb987f80-2021-11ea-9b49-1d3a77f4f19c.png)

Are there any ways to make them look more similar?

Thank you so much for your help.

**Comment by dpryan79** [comment]
I suspect if you either increase the DPI setting or make the image larger that they'll be more similar. What's happening is that when the image is made there are more data points than pixels, so the graphics library has to interpolate points to make the image. That often results in smoothing out the signals a bit.

You can try playing with the `--interpolationMethod` option too, sometime the `auto` setting doesn't produce the best results.

**Comment by shokohirosue** [comment]
Super! Playing with `--interpolationMethod` gave me the image I was looking for. 

Thank you so much for your help.
