### ISSUE TITLE
Extension of the region ignores feature annotation

### ISSUE THREAD

**Issue by lundlab-kaltinel** [deeptools/deepTools#898]
Hi,

I am trying to use deeptools version 3.3.1, and having some problems with extension of the regions.
I am trying to extend my genomic regions in the GTF file, specifically for start codons. Therefore I am choosing the `start_codon `(column 3) of my original GTF file and using it as a region file. As it did not accept the GTF file with start_codon features, I had to convert start_codon to 'CDS' and it accepted the region file as input ( `sed 's/start_codon/CDS/g'`)
The rest of the parameters are as follows:
`--metagene -o TSS-ref-point-A-3030.gz --upstream 30 --downstream 30  --binSize 1 --referencePoint TSS --exonID CDS --smartLabels --numberOfProcessors 10 --verbose`

The problem is, when the reference point extends from the start codons, sometimes this extension goes into introns as some UTRs are spliced and have introns in between. Therefore I am gathering counts from the introns instead of the real spliced region of the UTR.
How can I keep extending into the same annotation, not the others in case of splicing?

Thank you!

**Comment by dpryan79** [comment]
If you tell deepTools to use CDS as exons then it can't know about UTRs, so it's either or. BTW, you don't need to modify the GTF file, since the start_codon is already included in the first CDS entry.

**Comment by lundlab-kaltinel** [comment]
Thank you for your reply, I did the analysis by stating `exonID` as `exons` to include UTRs.
However, now, when my UTR is split by an intron, it seems like deeptools just extend to the intron and count the coverage from that region ( which is zero ) instead of the split part of the same UTR.
Such as : `(UTR <--intron---> UTR) `
So even though I see coverage in my `bigwig` files for two parts of my split UTR, in the `computematrix `output, I see all `0`s.
Which parameters should I use to not count the coverage from introns in between my features that I actually want to see counts from?

**Comment by dpryan79** [comment]
`--metagene` is all that's needed to skip over introns. If you have a section of a bigWig and GTF that aren't behaving like that then send them to me and I can have a look at what's going on.

**Comment by lundlab-kaltinel** [comment]
I will subset the files and send it, thank you.
However, mistakenly, I forgot to ask another major problem that I am trying to make it work and it seems like not possible.
I want to see the coverage around my `start codons` only, and if I can do `--exonID exon --metagene` , sure I will use the start of each exon as TSS, but then I will not be focusing on my start codons only. 
Do you have a suggestion for` start codon` only analysis?
(I thought of making customized GTF files but in all options I could think of, then I would need to extract the specific columns from the output of `computematrix` to get the counts specific for my start codons.)
I would be happy to hear your advice.

**Comment by dpryan79** [comment]
There's no good way currently to do the start codon analysis you want and take into account UTR splicing. This is because I only wrote the interval tree code that deepTools uses to handle a single set of exons (or equivalent) at a time, where as that would need two sets of them. Modifying the code to support that would be a considerable undertaking.

**Comment by dpryan79** [comment]
If your UTRs are long enough you can sort of hack around this limitation by creating a custom BED12 or GTF file where you pre-cut the up/downstream regions such that the first codon is in the middle of the resulting spliced fragment. Then you can use `--referencePoint center`. I imagine you have at least a few transcripts with shorter 5' UTRs though, so that may not work.

**Comment by lundlab-kaltinel** [comment]
Thank you!
