### ISSUE TITLE
bamCoverage: larger bin sizes than expected

### ISSUE THREAD

**Issue by ktroule** [deeptools/deepTools#907]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [ ] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

 - [deeptools 3.3.1 ] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.

 - [bamCoverage --bam accepted_hits.bam -o accepted_hits_binned.bed --binSize 100 --normalizeUsing None --effectiveGenomeSize 2913022398 --outFileFormat bedgraph -p 20 ] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).

 - [ ] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).

Hi, I'm using bamCoverage to bin counts from RIP-Seq, but after running a file I see that bin sizes can be larger than the bin size I've selected (--binSize 100). I've not selected the parameters smoothlength or extend. What I'm I doing wrong?

Thanks

Example:
```
chr1    0       11200   0
chr1    11200   11400   1
chr1    11400   12000   0
chr1    12000   12200   1
chr1    12200   12600   0
chr1    12600   13000   2
chr1    13000   13100   0
chr1    13100   13300   1
chr1    13300   13800   0
chr1    13800   13900   2
chr1    13900   14400   0
chr1    14400   14500   4
chr1    14500   14600   1
chr1    14600   15500   0
chr1    15500   15600   1
chr1    15600   16700   0
chr1    16700   16800   1
chr1    16800   16900   3
chr1    16900   17000   11
chr1    17000   17100   14
```

**Comment by dpryan79** [comment]
You're not doing anything wrong, deepTools will merge neighboring bins with the same value to save space.

**Comment by ktroule** [comment]
Thanks for the response!

Is there any way to have equally sized bins?

Thanks

**Comment by dpryan79** [comment]
There's not an option for it, no, since I consider tools requiring that to be broken. You can, however, just uncomment these lines in the code: https://github.com/deeptools/deepTools/blob/develop/deeptools/writeBedGraph.py#L250-L258

**Comment by ktroule** [comment]
Thanks

**Comment by mcsimenc** [comment]
@dpryan79, why do you consider tools that use tools that use bedGraphs with uniform bin widths broken?

Also, commenting out what I think are the lines you linked to in version 5.5.5-0 (current version from conda) didn't work:

Lines 124-131 of writeBedGraph_bam_and_bw.py:
```
            #elif previousValue != value:                                          
            #    if not np.isnan(previousValue):                                   
            #        _file.write(                                                  
            #            toBytes("{0}\t{1}\t{2}\t{3:g}\n".format(chrom, writeStart,
            #                                                    writeEnd, previousValue)))
            #    previousValue = value                                             
            #    writeStart = writeEnd                                             
            #    writeEnd = min(writeStart + tileSize, end) 
```

Is there another way to get `bamCoverage` to output bedGraph files with 1bp bins?
