### ISSUE TITLE
Missing license information in source code - "or later"?

### ISSUE THREAD

**Issue by smoe** [deeptools/deepTools#910]
Hello,
the GPL license document suggests to have a short paragraph in all files of the source tree to expicitly tell that each file falls under the GPL and, important for the GPL, to also render crystal clear if the file falls under GPL version 3 (as one would assume now) or if the "or any later version" applies.
Cheers,
Steffen

**Comment by smoe** [comment]
You have galaxy/wrappers as MIT (see https://github.com/deeptools/deepTools/blob/master/galaxy/wrapper/readme.rst) while the toplevel https://github.com/deeptools/deepTools/blob/master/LICENSE.txt  is GPLv3. Debian's FTPmasters kindly spotted that, your regular user (or Debian package maintainer) likely misses that.

**Comment by dpryan79** [comment]
I've switched to an MIT license in the develop branch and plan to push out a new release tomorrow. I meant to change the top-level license a while back, but I guess I never got around to it, so good on you and the Debian FTP masters for noticing it :)
