### ISSUE TITLE
visualize the enhancer regions in RRBS data from mm10 using deeptools

### ISSUE THREAD

**Issue by Rahel14350** [deeptools/deepTools#917]
Dear all,
I am using the deeptools to visualize the enhancer regions in RRBS data obtained from mm10 samples. Would you please let me know if I need to add mm10.genes.bed to my command (-R) or it is correct what I am doing? 
At the moment the bed file is the raw RRBS bed file (or should I add the bed file from sig. D.M. CpG sites?). I am very grateful for your answer.
Here is the code I am using:
`computeMatrix reference-point --referencePoint TSS -R bed/RRBS_cpgMethylation_B057.bed -S wgEncodeLicrHistoneThymusH3k04me1MAdult8wksC57bl6StdSig.bigWig --skipZeros -o matrix1_H3K4me3_B057_TSS.gz --outFileSortedRegions regions1_H3K4me3_B057_RRBS.bed
`
Kind Regards,
Rahel

**Comment by dpryan79** [comment]
I'd suggest calling DMRs and using those regions instead, but otherwise the command looks fine.
