### ISSUE TITLE
matplotlib version requirements incorrect

### ISSUE THREAD

**Issue by Temperche** [deeptools/deepTools#918]
Hello everyone, 

today I wanted to install deeptools as outlined in the manual with 

`pip install deeptools`

After a few dependencies that are correctly installed, the output says:
`Collecting matplotlib>=3.1.0 (from deeptools)
  Could not find a version that satisfies the requirement matplotlib>=3.1.0 (from deeptools) (from versions: 0.86, 0.86.1, 0.86.2, 0.91.0, 0.91.1, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1rc1, 1.4.1, 1.4.2, 1.4.3, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.1.0rc1, 2.1.0, 2.1.1, 2.1.2, 2.2.0rc1, 2.2.0, 2.2.2, 2.2.3, 2.2.4, 2.2.5)
No matching distribution found for matplotlib>=3.1.0 (from deeptools)`

I assume this has been an oversight. Could you please fix this?

Cheers
Temperche

**Comment by dpryan79** [comment]
The version is correct, you seem to be using python 2.7 which is no longer supported by most python packages.
