### ISSUE TITLE
rbind -> plotprofile using "un-thresholded matrix"

### ISSUE THREAD

**Issue by cpstgermain** [deeptools/deepTools#919]
Hi!

I am trying to put two plots together using rbind and it seems to be using the matrix that was created without the "max/minThreshold" command in computeMatrix. It seems that it's recalculating the matrix without the Threshold option? Thanks for any help you can provide!

Python 3.6.8 / Python 2.7.15+
computeMatrix 3.1.3
plotProfile 3.1.3

```
#GROseq_aB

computeMatrix reference-point \
-S ~/otherdata/bgfiles/mm10/GSM2184329_aB_wt_GROseq.plus.mm10.bw \
-R 20200119_dIP12_3reps_BRBvsORB_padj0.1_posl2fc.bed.sort \
--referencePoint center \
-o test_plus_matrix \
--averageTypeBins median -a 5000 -b 5000 -p 8 --maxThreshold 10

plotProfile \
--matrixFile test_plus_matrix \
--outFileName test_plus_matrix.png

computeMatrix reference-point \
-S ~/otherdata/bgfiles/mm10/GSM2184329_aB_wt_GROseq.minus.mm10.bw \
-R 20200119_dIP12_3reps_BRBvsORB_padj0.1_posl2fc.bed.sort \
--referencePoint center \
-o test_minus_matrix \
--averageTypeBins median -a 5000 -b 5000 -p 8 --minThreshold -10

plotProfile \
--matrixFile test_minus_matrix \
--outFileName test_minus_matrix.png
                                   
computeMatrixOperations relabel -m test_plus_matrix -o test_plus_matrix_label --groupLabels plus                                           

computeMatrixOperations relabel -m test_minus_matrix -o test_minus_matrix_label --groupLabels minus

computeMatrixOperations rbind -m test_plus_matrix_label test_minus_matrix_label -o test.rbind                                                                  

plotProfile -m test.rbind -o test.png
```

Minus Before Threshold
![MinusNoThreshold](https://user-images.githubusercontent.com/19979411/75621646-bbd20700-5b4b-11ea-8fd1-80089b9da7e8.PNG)

Minus After Threshold
![MinusAfterThreshold](https://user-images.githubusercontent.com/19979411/75621651-beccf780-5b4b-11ea-9b2b-161e6486fb2f.PNG)

Plus Before Threshold
![PlusBeforeThreshold](https://user-images.githubusercontent.com/19979411/75621648-bd9bca80-5b4b-11ea-9428-c019e1124fbe.PNG)

Plus After Threshold
![PlusAfterThreshold](https://user-images.githubusercontent.com/19979411/75621647-bd033400-5b4b-11ea-90a0-de882e52b69d.PNG)

After RBind -> plotProfile - seems to be before threshold
![AfterRBindPlotProfile](https://user-images.githubusercontent.com/19979411/75621650-beccf780-5b4b-11ea-86b7-4fd70941fff2.PNG)

**Comment by dpryan79** [comment]
What happens if you create both of the original matrices with `--minThreshold "-10" --maxThreshold 10`?

**Comment by cpstgermain** [comment]
You are da bomb.com. It seemed like I tried everything... Except that obviously! Thanks!!

**Comment by dpryan79** [comment]
Trying that wouldn't have been very obvious, so I'm not surprised you didn't try it. I'm not really sure if there's an optimal way to handle this sort of scenario automatically, so I'll close this for now.
