### ISSUE TITLE
plot Profile no y axis break label 

### ISSUE THREAD

**Issue by mkmwong** [deeptools/deepTools#920]
It seems to be exactly the same issue as issue #844. I have installed update to the newest deeptools. My python version is 3.7.3 and matplotlib is 3.1.0. Any advice on solving this issue would be great. Thanks!

**Comment by dpryan79** [comment]
@mkmwong Do you have a matrix that you can send to me that I can use to reproduce this?

**Comment by mkmwong** [comment]
@dpryan79 I used the attached matrix to produce the plot. Thank you for your help!
[Satellite.gz](https://github.com/deeptools/deepTools/files/4294599/Satellite.gz)
![Satellite](https://user-images.githubusercontent.com/32213452/76015624-49a54d80-5ed0-11ea-95fb-86b8ee4766c5.png)

**Comment by dpryan79** [comment]
I unfortunately can't reproduce this with deepTools 3.4.0 and matplotlib 3.1.0 or 3.2.0 under python 3.7.

**Comment by mkmwong** [comment]
I am not sure what it is, but when I do a git clone and re-installed deeptools, I have the updates on the change file about version 3.3.1, 3.3.2, 3.4.0, but when I do deeptools --version it was displaying deeptools 3.3.0

**Comment by dpryan79** [comment]
You likely have an old installation hanging around somewhere then.

**Comment by mkmwong** [comment]
found the solution - there's a deeptools in anaconda that was being used. thank you for all your help!
