### ISSUE TITLE
--lineAtTickMarks

### ISSUE THREAD

**Issue by dpryan79** [deeptools/deepTools#924]
For plotHeatmap it was just requested to add a `--lineAtTickMarks` option to also draw dashed lines at TSS/TES and unscaled regions. This need to be tested of course.

 - [x] Tested reference point
   - [x] TSS
   - [x] TES
   - [x] center
 - [x] scale regions
   - [x] unscaled region
 - [x] plotly
 - [x] galaxy wrapper

**Comment by Adnanhashim** [comment]
Hi . I wish to sort regions by their length without drawing a dashed line. Is it possible ?
