### ISSUE TITLE
bamPEFragmentSize - Incompatibility issue with Matplotlib 3.2.0

### ISSUE THREAD

**Issue by Kevin-Brockers** [deeptools/deepTools#928]
Dear all,
I experienced an attribute error when running deeptools bamPEFragmentSize.
- matplotlib _update_property attribute error: 'normed'

I ran Deeptools 3.3.2 in a conda enviroment with Matplotlib 3.2.0

Versions:
- Deeptools 3.3.2
- Matplotlib 3.2.0
- Python 3.7.6

I resolved it by downgrading Matplotlib to 3.0.2

And got the following message:
/anaconda3/envs/ChIP_Seq_Snakemake/lib/python3.7/site-packages/matplotlib/axes/_axes.py:6521:

 MatplotlibDeprecationWarning:
The 'normed' kwarg was deprecated in Matplotlib 2.1 and will be removed in 3.1. Use 'density' instead.

I ran bamPEFragmentSize in a Snakemake workflow with the following shell command:
        "bamPEFragmentSize --bamfiles {input} "
        "--histogram {output.frag_size_plot} "
        "--plotFileFormat png "
        "--numberOfProcessors 7 "
        "--samplesLabel {Samples} "
        "--plotTitle All_H1s_Inputs "
        "--maxFragmentLength 1000 "
        "--binSize 1000 "
        "--distanceBetweenBins 100000 "
        "--table {output.frag_size_summary_table} "
        "--outRawFragmentLengths {output.raw_frag_size} "
        "--verbose > {log}"

**Comment by dpryan79** [comment]
Ugh, I hate matplotlib :(

Thanks for letting me know, I'll try to track this down and release a bugfix release in the morning.

**Comment by Kevin-Brockers** [comment]
Thanks a lot!

**Comment by dpryan79** [comment]
This will be fixed in version 3.4.1, which will be released shortly.
