### ISSUE TITLE
computeMatrix -> plotProfile is offset when binSize is large

### ISSUE THREAD

**Issue by cpstgermain** [deeptools/deepTools#932]
Python 3.6.8 / Python 2.7.15+
computeMatrix 3.1.3
plotProfile 3.1.3

Hi! 

The more I use this the more I realize how great this program is, thanks! So it looks when my bin size is close to the distance from the center, the x-axis gets a little wonky. Can you think of a way I could change things in my input? It is below. The other picture is from where I use 100 as the bin size. Thanks!

Commodore

-S bigwig \
-R bedfile \
--referencePoint center \
-o outfile \
--averageTypeBins median -a 4000 -b 4000 -p 8 --blackListFileName blacklist --maxThreshold 0 --minThreshold 2 --binSize 1000

100 bin size
![rbind20200317-blmax2-min0-bin100-dist4000-END_seq_aB24h_NT](https://user-images.githubusercontent.com/19979411/77260094-04f51280-6c43-11ea-8884-b6a24d0419be.png)

1000 bin size
![rbind20200317-blmax2-min0-bin1000-dist4000-END_seq_aB24h_NT](https://user-images.githubusercontent.com/19979411/77260095-058da900-6c43-11ea-8d52-911ac409bbdb.png)

**Comment by dpryan79** [comment]
The issue is that the tick marks are offset a bit incorrectly and that the amount of incorrect offset is 0.5 times the bin size. It looks like I fixed this in the 3.3.2 release, please try rerunning plotProfile in that or a newer release.

**Comment by cpstgermain** [comment]
I'll try that once our helpdesk updates the software. Thanks!
