### ISSUE TITLE
multiBamSummary report no bam index while it has. 

### ISSUE THREAD

**Issue by chenatf** [deeptools/deepTools#933]
- [x] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

 - [x] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.
deeptools 3.4.1
Python 3.7.6

 - [x] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).
    multiBamSummary bins -b ${metadata}/*_nm_rmdup_sort.bam --smartLabels -p 20 \
    --scalingFactors ${metadata}/scalingFactors.txt -o ${metadata}/readCounts.npz \
    --outRawCounts ${metadata}/readCounts.tab

 - [x] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).
'../metadata/scatac-seq/HW3-252_S1020_L007_nm_rmdup_sort.bam' does not appear to have an index. You MUST index the file first!

The multiBamSummary bins reports error while I use it to handle 2306 indexed bam files. I have check all this bam files is ok and have been indexed by samtools index. However, multiBamSummary still report the bam file does not have an index. And the reported file is not the first bam file.

Thanks for your help!

**Comment by dpryan79** [comment]
Are you simultaneously processing 2000+ BAM files? My guess is that you're hitting the maximum number of open files allowed on your system if that's the case.

**Comment by chenatf** [comment]
Thanks for your advide. After I change the soft maximum number of open files from 1024 to 10000, the problem was sloved.
