### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by GerardoZA** [deeptools/deepTools#934]
(base) PS C:\Users\gerar> conda install -c bioconda deeptools
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
 below (ignore if you simply spotted the issue in the code/documentation).

I have this issue to install deeptools. 
I have the latest version of Anaconda. 
Don't know what the issue is or how to fix it. 
Any help is greatly appreciated

**Comment by dpryan79** [comment]
You're missing the conda-forge channel, which is always required by bioconda: `conda install -c conda-forge -c bioconda deeptools`. Note that I can't guarantee that you can install deepTools on windows unless you're using WSL.

**Comment by GerardoZA** [comment]
I got the same error. 
I also didn't know it would not be compatible with windows. 
I'm simply trying to convert from BigWig to CSV or .xlsx. 
Will just try with another software. 

Thank you brother

**Comment by dpryan79** [comment]
Very few bioinformatics programs can be installed on Windows, including essentially nothing from bioconda that isn't pure python. DeepTools has dependencies written in C that cannot be easily compiled on Windows.

**Comment by gimnec** [comment]
> You're missing the conda-forge channel, which is always required by bioconda: `conda install -c conda-forge -c bioconda deeptools`. Note that I can't guarantee that you can install deepTools on windows unless you're using WSL.

This worked for my different problems too, thanks.

**Comment by millerh1** [comment]
I am currently seeing this error on conda 4.9.2 on Ubuntu 20.04 LTS even though I use the correct channels:

```
(RSeq) millerh1@BioLinx:~/Projects/RSeq$ conda install -c conda-forge -c bioconda deeptools
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.                                                                              failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

The strange thing is that it doesn't tell me what the conflict actually was...

**Comment by LeilyR** [comment]
could please try it on an empty fresh env.?

**Comment by millerh1** [comment]
To solve it, I had to entirely remove miniconda3 and reinstall it. Seems like a problem with `conda` rather than with `deepTools`.
