### ISSUE TITLE
Issue with bamCoverage --exactScaling

### ISSUE THREAD

**Issue by zsun89** [deeptools/deepTools#935]
Hi Deeptools developers,

I used bamCoverage with or without --exactScaling to see whether it would make any difference to the pileup file, but got exactly same reported 'final scaling factor'. Duplicate removal was activated by --ignoreDuplicates during the run. Shouldn't I see a more or less different 'final scaling factor', since without --exactScaling it is calculated from a sampling process (in my case to estimate duplication rate from sampled bins)? Additionally, both run took very similar amount of time to finish, whereas the manual suggested that exactScaling would take significantly longer. Is the exactScaling not working? Please see the required info regarding my run below.

Besides, I was wondering how is the 'final scaling factor' calculated. Say I have 25 million mapped reads (after all the filtering processes with bamCoverage such as deduplication or fragment size filtering) in my bam file and I want to generate pileup file with RPKM normalization using 10 bp bins. Should the final scaling factor be roughly 1/(25*0.01) = 4, which would be multiplied by counts of each bin? [ RPKM (per bin) = number of reads per bin / (number of mapped reads (in millions) * bin length (kb))]. Could you advise as to why I got a final scaling factor of ~1.36. 

Thanks,
Zhen

deeptools version 3.2.1
python version 2.7.5

- Command:
1) with --exactScaling
bamCoverage -b sorted.bam -o rmdup_RPKM_exact.bigwig -of bigwig -bs 10 --extendReads --ignoreDuplicates --normalizeUsing RPKM --exactScaling --skipNonCoveredRegions -p max/2 --verbose

2) without --exactScaling
bamCoverage -b sorted.bam -o rmdup_RPKM_regular.bigwig -of bigwig -bs 10 --extendReads --ignoreDuplicates --normalizeUsing RPKM --skipNonCoveredRegions -p max/2 --verbose 

- Output:
1) with --exactScaling :
Final scaling factor: 1.3635921708537353
genome partition size for multiprocessing: 1050000
using 36 processors for 2652 number of tasks
Specified --scaleFactor: 1.0
normalization: RPKM
Fragment length based on paired en data estimated to be 194.0
bamFilesList: ['sorted.bam']
binLength: 10
numberOfSamples: None
blackListFileName: None
skipZeroOverZero: False
defaultFragmentLength: 194
numberOfProcessors: 36
verbose: True
region: None
bedFile: None
minMappingQuality: None
ignoreDuplicates: True
chrsToSkip: []
stepSize: 10
center_read: False
samFlag_include: None
samFlag_exclude: None
minFragmentLength: 0
maxFragmentLength: 0
zerosToNans: True
smoothLength: None
save_data: False
out_file_for_raw_data: None
maxPairedFragmentLength: 776

2) without --exactScaling :
Final scaling factor: 1.3635921708537353
genome partition size for multiprocessing: 1050000
using 24 processors for 2652 number of tasks
Specified --scaleFactor: 1.0
normalization: RPKM
Fragment length based on paired en data estimated to be 194.0
bamFilesList: ['sorted.bam']
binLength: 10
numberOfSamples: None
blackListFileName: None
skipZeroOverZero: False
defaultFragmentLength: 194
numberOfProcessors: 24
verbose: True
region: None
bedFile: None
minMappingQuality: None
ignoreDuplicates: True
chrsToSkip: []
stepSize: 10
center_read: False
samFlag_include: None
samFlag_exclude: None
minFragmentLength: 0
maxFragmentLength: 0
zerosToNans: True
smoothLength: None
save_data: False
out_file_for_raw_data: None
maxPairedFragmentLength: 776

**Comment by dpryan79** [comment]
If there are relatively few alignments in the file (< 1 million) then you'll get the same value either way. Otherwise bamCoverage will try to sample at least 10% of the reads.

The scale factor for RPKM is calculated as:

    scale_factor = 1.0
    million_reads_mapped = number of mapped reads / 1e6
    tile_len_in_kb = bin size / 1000
    scale_factor *= 1.0 / (million_reads_mapped * tile_len_in_kb)

**Comment by zsun89** [comment]
Thank you for the quick reply. I have about 40 million reads in this particular file, so there should have been sampling? Then it seemed --exactScaling was not working? 'estimateReadFiltering' estimated a very high duplication rate (~50%) for this particular file, which was why I tried to test if scaling factor calculation was accurate for it with or without --exactScaling.

It seems my understanding for RPKM scale factor is correct. In my case:
scale_factor = 1.0 (default value)
million_reads_mapped = ~40,000,000 / 1e6 = ~40 (after deduplication: ~ 25)
tile_len_in_kb = 10 / 1000 = 0.01
scale_factor *= 1.0 / (million_reads_mapped * tile_len_in_kb) = 1.0 / (25 * 0.01) = 4
Why did I get a final scaling factor of ~1.36?

Thanks,
Zhen

**Comment by dpryan79** [comment]
If the reads are rather clumpy (likely if the duplication is high) then you'll end up sampling all of them, simply due to how I wrote that algorithm (it samples more and more of the genome until it hits its target number of reads, which can certainly be 100%). Regarding the scaling factor, apparently you have more reads than you thought, what I posted is the exact code that's used.

**Comment by zsun89** [comment]
Thanks. I have pair-end data, and would that contribute to the smaller-than-expected scaling factor? 'million_reads_mapped' for scale factor calculation is actual number of reads instead of fragments, right? 
Thanks,
Zhen

**Comment by zsun89** [comment]
BTW, the number of 'reads' I mentioned before was actually number of 'fragments'.

**Comment by zsun89** [comment]
I confirmed that using the actual number of paired reads instead of fragment, the scaling factor looked exactly right as you suggested!
However, it appeared that the final scaling factor was calculated using the total number of mapped reads without removing duplicate reads even though I activated that flag. How could I know if --ignoreDuplicates worked? I don't see a ''Due to filtering, x% of the aforementioned alignments will be used y" message reported after the run.
Thanks!
Zhen

**Comment by zsun89** [comment]
To get a control where duplicate reads are actually removed, I used alignmentSieve to first remove duplicate reads and then used bamCoverage to generate a pileup. The 'final scaling factor' is significantly bigger than using bamCoverage --ignoreDuplicates, suggesting that the --ignoreDuplicates flag was not working. In other words, it still used the total original number of reads with duplicates to generate the scaling factor. Could you help figure out how to activate duplicate removal on the flight with bamCoverage? 
Thanks!
Zhen
