### ISSUE TITLE
Compute Matrix clustering over gene regions separates clusters with bias towards specific strand

### ISSUE THREAD

**Issue by das2000sidd** [deeptools/deepTools#936]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [ ] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

 - [ ] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.

 - [ ] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).

 - [ ] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).

Hi

I am using k means clustering within deeptools to cluster by log fold change of H3K4me3 signal using scale regions for all protein coding genes. When I look at the heatmap generated, I found one cluster with loss of H3K4me3 around TES as labelled by plotHeatmap and another around TSS. Guessing that is because the genes are on different strands, I looked number of genes per strand within the clusters and noticed that the ones with loss of H3K4me3 around TSS are majorly on positive strand (~88%) and the ones with loss around TES are on negative strand(~88%). So it seems like the strand of the gene is proving to be crucial in clustering when I prefer the clustering to be log fold change. Can someone give some insight as to how to deal with this?
I am using deeptools version 3.1.1

Thank you again!

**Comment by LeilyR** [comment]
Hi , I am not sure if I understood what you actually want to achieve. But if you are interested in signal only around TSS , why don't you try the reference-point mode for compute matrix and and set the reference point to TSS. Let us know if it answered your question.

**Comment by dpryan79** [comment]
The strand is taken into account when the matrix is generated, so the TES is indeed the TES and not the TSS of a gene on the - strand (unless you input BED/GTF file omitted strand information).
