### ISSUE TITLE
How does bamCoverage with --Offset deal with paired-end reads?

### ISSUE THREAD

**Issue by AlexBlais74** [deeptools/deepTools#937]
Hello
I am using bamCoverage to analyze ATAC-seq data (paired-end reads). I want to record the density of Tn5 insertion at each genomic position rather than the density of genomic fragments in the library (which is what most people do, I think). In ATAC-seq, the 5' ends of EACH read in a pair represent Tn5 insertion sites and I want to record both. 

To adjust the insertion positions, I first run alignmentSieve with the --ATACshift option, and then in bamCoverage I use the --Offset option set to "1". Then I plan to use bamCoverage with "--Offset 1" to look at just the 5' end of the reads.

My question is: does bamCoverage with "--Offset 1" count the 5' ends of each mate, or the 5' end of the fragment?

If only one end is recorded, I do have a workaround: I could split my paired-end BAM file into the first and second mates (alignmentSieve with --samFlagInclude and --filteredOutReads), then merge, sort, index, and finally perform bamCoverage.

Another option is using Genrich ( https://github.com/jsh58/Genrich ) in ATAC-seq mode and work with the bedgraph output that it can generate. But I don't like this option as much since it is slower and much less flexible compared to deepTools.

Thanks in advance for your help.

Alex

**Comment by dpryan79** [comment]
`--Offset 1` handles each mate separately, which is what you want. Please note that the tn5 insertion site is more than just the first base, but rather than first 6-7 base, with an additional 10 necessarily being accessible for insertion to occur (you have to dig into the tn5 literature to find this).
