### ISSUE TITLE
Deeptools slow in parallel (High IO usage)

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [deeptools/deepTools#938]
I noticed that when I run multiple `bamCoverage` or `alignmentSieve` in parallel the program barely executes anymore. The cpu usage of the processes are really low, and it is mainly waiting for IO and can confirm this when I check with `iotop`. The disks on our server are highly fragmented and somehow do not want to play together with deeptools. I am hoping there is some magic setting that solves all these problems :angel:. I am aware that just running less in parallel would also help :).

*version*
deeptools=3.3.1
python=3.7.6

*example command*
`alignmentSieve.py -b sample1.bam -o sample1.filtered.bam --minMappingQuality 30 --blackListFileName myblacklist.bed -p 4`

**Comment by dpryan79** [comment]
There's nothing we can do if the disks can't keep up, sorry :(

**Comment by Maarten-vd-Sande** [comment]
Okay too bad, thanks for the answer. ☺️
