### ISSUE TITLE
How to zoom at a specific x and y-axis coordinates in plotCorrelation module?

### ISSUE THREAD

**Issue by biobug16** [deeptools/deepTools#946]
I used deeptools 3.4.2 and its plotCorrelation module and generated following figure:
![scatterplot_all_C4_w_label_MapQ30_bl](https://user-images.githubusercontent.com/47798557/80571414-971ed200-89ca-11ea-8803-433089c20e69.png)
Referring the given figure, most of my data points are gathered between 0 to 25000 on x axis and between 0 to 80000 on y axis. Thus I specifically want to zoom the x-axis coordinates from 0 to 25000 and y axis from 0 to 80000. I am not sure if it is possible with deeptools and looking for suggestions.

I tried following command but didn't get what I needed, can you please guide how can I zoom to the said coordinates?

`plotCorrelation -in all_C4_results_w_label_MapQ30_bl.npz --corMethod spearman --skipZeros --removeOutliers --whatToPlot scatterplot -o scatterplot_1.png --xRange 0 25000 --yRange 0 80000`

I will appreciate any help towards this.
Thanks

**Comment by dpryan79** [comment]
I'm surprised the `--xRange` option isn't working, I suspect this is a new matplotlib bug. Can you try the `--log1p` option? It won't do exactly what you want but it will at least allow you to see the data better.

**Comment by biobug16** [comment]
@dpryan79 Thanks for your prompt reply.
I tried it with --log1p it has magnified the blue regions but again has not solved my problem. I am interested to show the positive and negative slops here between the active and repressive marks and that is missing here.
![scatterplot_SpearsonCorr_bigwigScores_all_C4_w_label_MapQ30_bl_again](https://user-images.githubusercontent.com/47798557/80573976-f7b00e00-89ce-11ea-941a-6bbaaa1f1164.png)
Can you please suggest something to make it visually better?

**Comment by dpryan79** [comment]
You'll need to filter out a lot of the lower coverage points if you want to clearly be able to see the slopes.

**Comment by biobug16** [comment]
Sorry, for asking another question here. How does multiBamSummary and plotCoordinates work? Are these just the ranks ( because you quoted "correlation in ranks really")? I am a bit confused now and thought these are the read depth for each coordinates, may be I am missing something.

**Comment by dpryan79** [comment]
plotCorrelation can use either pearson or spearman's correlation, so it's either value or rank based, respectively. If you make the input file with multiBamSummary only spearman's correlation makes sense.

mutliBamSummary iterates through BAM files and counts the number of reads in the same random genomic ranges in each. It makes a matrix out of that for plotCorrelation. This matrix has raw read numbers in it, so things like pearson's correlation may not be appropriate (unless the BAM files have similar coverages).

**Comment by biobug16** [comment]
Thanks much for the great explanation, it makes sense.
I used multiBamSummary and spearman's correlation only for the above two plots, but not sure how to emphasize on the direction of correlation between the active and repressive marks.

**Comment by dpryan79** [comment]
Plot the heatmap of it rather than the scatter plot. There are just too many points for the scatter plots to be useful.

**Comment by leotiwei** [comment]
I meet the same problem and solved it now. Maybe you can try to download an old 3.1.2 version deeptools in a new conda environment, it's works for me.
