### ISSUE TITLE
Extracting data from computeMatrix or plotProfile

### ISSUE THREAD

**Issue by cpstgermain** [deeptools/deepTools#948]
Hi!

Great program again BTW. Hope you are well. I was using computeMatrix -> plotProfile to investigate something and I found that there is this repeating pattern in my data that I wasn't expecting. Is there some way to extract that data and see which bed regions those were? I want to make sure I didn't accidentally copy something I shouldn't have or maybe its something else cool to look at. Thanks!

Commodore
![Capturedeeptools](https://user-images.githubusercontent.com/19979411/81017225-d27c2f00-8e16-11ea-8367-04d8686cf648.PNG)

**Comment by dpryan79** [comment]
Ooh, that's a very intriguing pattern. Yes, you can extract the regions using the `--outFileSortedRegions` option.

**Comment by cpstgermain** [comment]
Thanks! I tried that and when I went through the file, it just gave me the same order of the coordinates that was used for the input...

**Comment by cpstgermain** [comment]
So to be more specific, I had 8840 bed positions to analyze, and it gave me back 57 but in the same sorting order...

**Comment by dpryan79** [comment]
Presuming you used that option with plotHeatmap, it's giving you the regions in the order that they're used in the plot.
