### ISSUE TITLE
Request: MNase option in bamCoverage for merged reads

### ISSUE THREAD

**Issue by kingralph80** [deeptools/deepTools#949]
Hi we are using bamCoverage with transcription factor footprinting, We have mostly overlapping reads and merge them to reduce sequencing errors. Would it be possible to have the MNase option for merged reads, using the fragment center? We don't want to use the paired-read since they often overlap.

**Comment by dpryan79** [comment]
There's no reason to merge the reads beforehand, that's done with the `-e` option (you probably want to then add `--samFlagExclude 128` so only one read in the pair is then used to calculate the coverage.
