### ISSUE TITLE
Deal with Batch effects

### ISSUE THREAD

**Issue by AlexWanghaoming** [deeptools/deepTools#950]
Hi deepTools developer,
deepTools version 3.4.3
Python version 3.6.8
commands:
`bamCoverage -b batch1.ba,m --normalizeUsing RPKM -o batch1.bw -p 4
bamCoverage -b batch2.bam, --normalizeUsing RPKM -o batch2.bw -p 4
computeMatrix scale-regions -S batch1.bw batch2.bw -R ${gff} -m 1500 -b 1000 -a 1000 -o two_batch.mat -p 4
plotProfile -m two_batch.mat -o genebody.pdf 
`
I plot the geneBody profile of ATAC-seq data different batches of the same sample. Ordinarily the result should be similar.  But I got the the plot that the one is entirely higher than another one. For bamCoverage normalization, the RPKM is the same as BPM(TPM) result.  I do not know why. Are they comparable or not?
[twobatch.pdf](https://github.com/deeptools/deepTools/files/4648252/twobatch.pdf)
In the attached plot, qde1 and ph1 are the two batches of  same sample
Thanks

**Comment by dpryan79** [comment]
You might play around with the scaling factor such that the graphs have the same background signal level.

**Comment by AlexWanghaoming** [comment]
@dpryan79 Thanks for you reply, you mean I should use bamCompare instead of bamCoverage or  I can indicate use --scaleFactor parameter in bamCoverage. Moreover， how could I calculate scaleFactor of two bam file?
Thanks

**Comment by AlexWanghaoming** [comment]
Hi
I specified bamCoverage --scaleFactor of two bam respectively to the final scale factors( total bam1 reads / total bam2 reads which is in bamCoverage -v stout)
But the result didn't change. The one is higher than another
[sex2.pdf](https://github.com/deeptools/deepTools/files/4649461/sex2.pdf)

**Comment by dpryan79** [comment]
You'll have to eye-ball the scale factor. It looks like 0.85 would work for the sample on the right.
