### ISSUE TITLE
feature: read from compressed .bed files

### ISSUE THREAD

**Issue by malcook** [deeptools/deepTools#957]
Many workflows support or require compressing .bed files.  It would be ideal if deeptools could accept compressed .bed files wherever it accepts .bed files.

**Comment by dpryan79** [comment]
I've never heard of a tool requiring a compressed BED file as input, that seems like an absurd thing to require (bigBed I could at understand). I don't intend to implement this, tools requiring compressed BED input are broken.

**Comment by malcook** [comment]
Understood.

FWIW, and possibly of interest to you, Tabix indexed bgzipped bed files allow them to serve byte-range request  over http to, e.g., the IGV genome browser.

Of course it is possible to keep a copy of the unzipped .bed file around as well for deeptools, which is what I am doing.
