### ISSUE TITLE
Which parameter to use, "scale-region" or "reference-point"?

### ISSUE THREAD

**Issue by Swadha22** [deeptools/deepTools#958]
deeptools 3.1.3
Python 2.7.13

Hi,
I have a few samples of histone ChIP of _C.elegans_ . I want to use the tool "plotProfile" to see the enrichments near TSS, gene-body region and TES using the GTF file. Which parameter of computeMatrix should I use, "scale-region" or "reference-point"?  

Thanks
Swadha

**Comment by LeilyR** [comment]
try ` computeMatrix reference-point ` or ` computeMatrix scale-regions` . You can fine mode here: 
https://deeptools.readthedocs.io/en/develop/content/tools/computeMatrix.html

**Comment by dpryan79** [comment]
You can use either mode, it depends on the whether you want the profiles around a specific position (e.g., the TSS) or around scaled regions (e.g., genes or transcripts). This will be specific to what you want to look at.

**Comment by Swadha22** [comment]
Thanks, Ryan for getting back! 
Got it now. I will generate my plots and get back to you if I have more questions. 

Thanks
Swadha
