### ISSUE TITLE
Bam file mapped to the transcriptome?

### ISSUE THREAD

**Issue by qianxu05172019** [deeptools/deepTools#960]
Hi, I am wondering if I can use deeptools ( for instance the multiBamCoverage tool) to compare the bam files mapped to transcriptomes? Or it is just designed for bam files that is mapped to genomes? 

Thanks for your time!

**Comment by dpryan79** [comment]
DeepTools doesn't really care about the nature of the BAM file, so you can use transcriptome alignments without issue (this may be a bit slower, since deepTools slows down a bit when there are a lot of contigs).

**Comment by qianxu05172019** [comment]
Got you! I guess I just need to set proper bin size. Thanks for this awesome tool!
