### ISSUE TITLE
How can I change the legend font size?

### ISSUE THREAD

**Issue by yirenheihei** [deeptools/deepTools#963]
Hi,I am using plotProfile plot gene body signal from chip seq data.I want change the legend font size very small,but I cannot find corresponding parameter?Can you help me? Thank you very much!!!

**Comment by dpryan79** [comment]
In theory you can change some things by creating a [config file](https://matplotlib.org/tutorials/introductory/customizing.html), though in practice it's probably easier to save images as PDF and then make the final tweaks in Illustrator or a similar program.

**Comment by yirenheihei** [comment]
> In theory you can change some things by creating a [config file](https://matplotlib.org/tutorials/introductory/customizing.html), though in practice it's probably easier to save images as PDF and then make the final tweaks in Illustrator or a similar program.

I try do it ,thanks.
