### ISSUE TITLE
bamCompare error message typo

### ISSUE THREAD

**Issue by alfonsosaera** [deeptools/deepTools#966]
Hi, while running bamCompare as

> `bamCompare --operation mean --effectiveGenomeSize 2913022398 --normalizeUsing BPM --binSize 50 -b1 sample1.bam   -b2 sample2.bam   -o sample-MEAN.bpm.bw`

I got the error

> `'--normalizeUsing BPM' is only valid if you also use '--scaleFactorMethod None'! To prevent erroneous output, I will quit now.`

so I ran it again adding `--scaleFactorMethod None` as follows

> `bamCompare --operation mean --effectiveGenomeSize 2913022398 --normalizeUsing BPM --binSize 50 -b1 sample1.bam   -b2 sample2.bam --scaleFactorMethod None -o sample-MEAN.bpm.bw`

but got the error

> `usage:  bamCompare -b1 treatment.bam -b2 control.bam -o log2ratio.bw`
> `bamCompare: error: unrecognized arguments: --scaleFactorMethod None`

reading the manual of [bamCompare](https://deeptools.readthedocs.io/en/develop/content/tools/bamCompare.html?highlight=bamCompare#Optional%20arguments) I found that the right argument is  `--scaleFactorsMethod` instead of `--scaleFactorMethod`, note the extra `s` in the first one.

Thanks for this great package

**Comment by LeilyR** [comment]
Thanks for reporting it. We will fix it.
