### ISSUE TITLE
Can deeptools cluster by more than one change

### ISSUE THREAD

**Issue by das2000sidd** [deeptools/deepTools#973]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [ ] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

 - [ ] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.

 - [ ] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).

 - [ ] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).

First of all I would like to highly appreciate you guys for the excellent tool that your group has developed. I am a regular user of it and the plots are of top notch quality.
I was wondering that could the kmeans clustering in deeptools be modified to include clustering by more than one type of log fold change? To my best understanding, currently only type of log fold change can be used for the clustering.
If not, can you suggest how could I use the underlying matrix to perform the clustering manually in this case like using kmeans in R?

Thank you again for taking your time for any possible answers.

**Comment by LeilyR** [comment]
How do you mean by `one type of log fold change` ? It clusters whatever values are in the matrix. If you want to cluster using some of the samples only, you can use `--clusterUsingSamples`

**Comment by das2000sidd** [comment]
Hi

Thank you again for your reply. I think this answers my questions. Could you tell me which version of deeptools this is? I don't think this exists for deeptools/3.1.1, isn't it?

**Comment by LeilyR** [comment]
Try our latest version (3.4.3)

**Comment by LeilyR** [comment]
Hi, yes you eight. When using clusterUsingSample only the given samples are used for clustering and the result is applied to all the samples when plotting the heatmap.

**Comment by hcph** [comment]
> Hi, yes you eight. When using clusterUsingSample only the given samples are used for clustering and the result is applied to all the samples when plotting the heatmap.

Thank you for your quick answer! Please allow me to ask one more question, I wonder whether there still correspence when the parameter is not added? Are all samples clustered individually without any connection of each row between samples?

**Comment by LeilyR** [comment]
If not mentioned, then the full matrix including all samples is used for clustering.
