### ISSUE TITLE
how to set bamCompare to write tmp files to a different directory

### ISSUE THREAD

**Issue by jennxyz** [deeptools/deepTools#975]
Hello! Having a problem similar to this previous issue: https://github.com/deeptools/deepTools/issues/512

bamCompare is writing a /tmp file that is too large for the root directory / to handle on the server I'm working off of. I have significantly more disk space under the data/ directory, could you help guide me to what line of code I should edit to make bamCompare write temp files in a different directory of my choosing (ie write to /data/tmp)?  

I'm running deepTools version 3.3.1

Additionally I'm not sure if this is supposed to happen, but when the /tmp dir is full when running bamCompare and I get the 'no space left on device error' the temp files don't seem to delete on their own and generate other errors; "-bash: cannot create temp file for here-document: No space left on device" tab-completion errors for example. I might just be too naive to figure out how to fix this issue without restarting the server.

THANK YOU. Huge fan of deepTools!

**Comment by LeilyR** [comment]
I am not sure if I can help you with this, but are your bam files sorted? Would you mind try using sorted bam files as input for bamCompare and see if that would help.

**Comment by jennxyz** [comment]
Yes, all the bam files are sorted using **samtools sort** prior to inputting to bamCompare

**Comment by katsikora** [comment]
bamCompare doesn't have an option for setting the temporary path, but you can `cd` into your `data` directory, run the command there, and transfer final output afterwards. You can also try setting `TMP` and `TEMP` variables to some path you know you have enough space on before running deepTools, although I can't guarantee this will be respected.

Did you try running it in multithreaded mode to see if the temporary files get smaller then?

**Comment by LeilyR** [comment]
Since we have not heard from your back, we hope that your issue has been already solved . I close this issue but feel free to open it again if there is any problem left.
