### ISSUE TITLE
Docker Image for Each Release (NOT Galaxy-Deeptools)!!!!

### ISSUE THREAD

**Issue by YogiOnBioinformatics** [deeptools/deepTools#978]
This has got to be one of the most useful omics tools I've ever used!!! 
Thanks for making this!

However, I don't understand why there isn't a Docker Image for each specific release available on an Image Registry such as Docker Hub?

I saw that there is a Dockerized version of deepTools for people using Galaxy. 
However, to just get a simple container running deepTools, there are tons of sparsely updated and quite outdated deepTools images [available](https://hub.docker.com/search?q=deeptools%20&type=image). 

Can you please, please create an image repo that includes images for each release?

**Comment by dpryan79** [comment]
There's a docker container made for each release via bioconda/biocontainers: https://quay.io/repository/biocontainers/deeptools?tag=latest&tab=tags

There are vastly more containers available on quay.io than docker hub since we (bioconda) push all produced containers there.

**Comment by YogiOnBioinformatics** [comment]
This is wonderful! 
Thanks so much!

**Comment by YogiOnBioinformatics** [comment]
Suddenly just thought about this but would you mind adding this info on the README?

Would be very useful for all!
