### ISSUE TITLE
bamCoverage signal from paired-end ChIP-seq samples doesn't match number of fragments

### ISSUE THREAD

**Issue by romanhaa** [deeptools/deepTools#979]
Hi there,

I have a question regarding the bamCoverage function. I apologize if this isn't the right place to post a question but my email to the Google Groups bounced back saying that posting via email isn't allowed and on the Google Groups website it said I had no permission to post there either. Anyway, I generated a bigWig track from a paired-end ChIP-seq sample using the command below:

```sh
bamCoverage \
--bam <input>.bam \
--outFileName <output>.bw \
--outFileFormat bigwig \
--binSize 1 \
--numberOfProcessors 4 \
--extendReads
```

I then loaded the bigWig file into the IGV and looked at the signal from the bigWig track and compared it to the input BAM file. I noticed that the signal reported in the bigWig track is exactly twice the number of fragments that I see in the BAM file. Because of that, I added the `--scaleFactor 0.5` option, which fixes this behavior. But I was curious to know whether this is intentional and I’m just missing the reason, if it has to do with my BAM file, or if this is a bug.

I’m using deepTools 3.4.3.

Thank you!

Best,
Roman

**Comment by LeilyR** [comment]
have you considered having reads with overlap?

**Comment by romanhaa** [comment]
That would've been a good explanation but I had checked that before.

Perhaps it helps if I attach a screenshot from IGV that shows both the signal from the BAM file as well as the corresponding bigWig track (that was generated without specifying a `--scaleFactor`).

![Screen Shot 2020-08-03 at 16 34 30](https://user-images.githubusercontent.com/18103560/89194112-372a5f80-d5a7-11ea-9d9a-7f0a8cb1d143.png)

You see that there are 5 steps in the bigWig track, corresponding to 5 overlapping fragments. Yet, from the scale it seems that the signal is `10` instead of the expected `5`.

**Comment by LeilyR** [comment]
I see what you mean. The reason is that it counts every entry in your .bam file not every paired read. check the number of  entries in the bam file, for example with samtools view -c and proper flag, then you see how many they are.

**Comment by romanhaa** [comment]
Hmm, ok. Personally, I find that a little confusing, but adjusting the scale factor is an easy fix. Thank you for the explanation!

**Comment by ZHIDIHUAYUAN** [comment]
Hi,
I have some questions about the counts. I have a a paired-end ATAC-seq library. When I use the bamCoverage, Does it calculate the two reads of the same segment separately based on their respective information, or does it first combine the reads of the same segment into one segment, and then count each region?

**Comment by dpryan79** [comment]
By default it will count both, since they will typically not overlap. If you extend the reads then you should only use read 1 (or 2, your choice).
