### ISSUE TITLE
scale factor from multiBamSummary and used in bamCoverage

### ISSUE THREAD

**Issue by Zhuxitong** [deeptools/deepTools#980]
Hi!

This might be a strange question. I saw many people using --scaleFactor in bamCoverage combined with a --normalizeUsing method like CPM. I am not sure where they got the scaleFactor value but it's avaliable in multiBamSummary. My question would be:
1, why using scaleFactor again in bamCoverage since the normalization method already did this?
2, if not using scaleFactor and only a normalization method used, can we compare the signal strength of one feature(like a gene) in two different samples diectly? 

In RNA-seq data, most people would use TPM to compare one gene expression level in two different samples, with no scale factor if Iremember correctly.

This question has disturbing me a lot and any help would be very grateful!

**Comment by katsikora** [comment]
I'd recommend using `--scaleFactor` and `--normalizeUsing` in a mutually exclusive way.
You can get scale factors from multiBamSummary, or an external tool e.g. DESeq2.

Normalization has the purpose of being able to compare tracks between samples.

TPM are transcript-length normalized values and get one data point per transcript. This is a different view on the gene expression than when comparing coverage tracks for different samples along the gene locus. Coverage tracks are mostly used for visualization, often together with other genomic tracks.

**Comment by Zhuxitong** [comment]
Thanks @katsikora 

I did some tests on my RNA-seq and ATAC-seq data these days, found when I combined **--scaleFactor** and **--normalizeUsing** together in the bamCoverage command, I would get different background signal levels for different samples. So using ethier one of them would be enough:)
