### ISSUE TITLE
Deeptools ValueError: invalid literal for int() with base 10 error

### ISSUE THREAD

**Issue by das2000sidd** [deeptools/deepTools#981]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [ ] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

 - [ ] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.

 - [ ] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).

 - [ ] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).

Hi

I am using deeptools for some heatmap plotting and I am running into an error that have never run into before while using deeptools.

The error says: if int(cols[1]) >= int(cols[2]): ValueError: invalid literal for int() with base 10: '3.2e+07'

As I understand, while checking if the third column is larger than the second one in the bed file, a string value was interpreted when an integer was expected. Note that my bed file is a tab delimited text file with no quotes.

Can you suggest what might be causing the issue here?

Thank you and appreciate the help.

**Comment by LeilyR** [comment]
the start column should be smaller than the end column in a bed file
