### ISSUE TITLE
plotHeatmap choppy plot—sorting error?

### ISSUE THREAD

**Issue by umasstr** [deeptools/deepTools#983]
_Error reproduced in Deeptools versions 3.0.1 and 3.3.1_
Using BWs generated by bamCoverage, I build matricies with:
`computeMatrix reference-point -S 8505c_DHT_AR.cpm.bw 8505c_EtOH_AR.cpm.bw  -R hg38_TSS.bed -b 500 -a 500 -p 15 --referencePoint center -o 8505c_TSS.mat.gz `

Then I make a heatmap:
`plotHeatmap -m  8505c_TSS.mat.gz -out heatmap_8505c_TSS.png`

The resulting heatmap seems to be poorly sorted:
![image](https://user-images.githubusercontent.com/44478133/89717881-9feb5080-d988-11ea-830d-9b204c11abf3.png)

In plotHeatmap, I tried all options of "--sortUsing" without avail. Different plots are generated, all wrong. 

Next, I rebuild the matrix using computeMatrix options --missingDataAsZero and --skipZeros (separately). Same result. Interestingly, there are still several 0.00 values despite --skipZeros, and the map looks worse skipping zeros.

> $ zcat 8505c_TSS.mat.gz | head
@{"sample_boundaries":[0,100,200],"downstream":[500,500],"skip zeros":true,"missing data as zero":false,"unscaled 3 prime":[0,0],"verbose":true,"ref point":["center","center"],"bin avg type":"mean","nan after end":false,"max threshold":null,"group_boundaries":[0,14896],"sort regions":"keep","body":[0,0],"sample_labels":["8505c_DHT_AR.cpm","8505c_EtOH_AR.cpm"],"unscaled 5 prime":[0,0],"bin size":[10,10],"proc number":15,"upstream":[500,500],"group_labels":["genes"],"sort using":"mean","min threshold":null,"scale":1}
chr1    17426   17446   chr1:17426-17446        .       .       0.000000        0.000000        0.000000      0.000000        0.000000        0.000000        0.000000        0.000000        0.000000     0

![image](https://user-images.githubusercontent.com/44478133/89718142-b397b680-d98a-11ea-8032-24f39b548caf.png)

Finally, `computeMatrix ... --minThreshold 1` yields a nonsense heatmap.
![image](https://user-images.githubusercontent.com/44478133/89718565-92849500-d98d-11ea-92cf-ba104b7b1eba.png)

This is a CUT&TAG sequencing dataset. It has been my experience that deeptools may have issue with particularly low-background data. I seldom observe a plot without considerable dead space (dark red). 

I hope that I am doing something wrong and that this can be easily remedied. Thanks for the help!

**Comment by LeilyR** [comment]
Do you have different groups in the bed file you use? 
Also, how much background you see is dependent to how you make your .bw files , I suppose in your case they are not corrected for background signal (input)

**Comment by umasstr** [comment]
Thank you for your reply. I eliminated all but columns 1-3 from my bed:

> $ head hg38_TSS.cut.bed
> 
> chr1    11863   11883
> chr1    17426   17446
> chr1    29360   29380
> chr1    30355   30375
> chr1    36071   36091
> chr1    69080   69100
> chr1    140556  140576
> chr1    182377  182397
> chr1    187948  187968
> chr1    206587  206607

Then computeMatrix:

> computeMatrix reference-point -S 8505c_DHT_AR.cpm.bw 8505c_EtOH_AR.cpm.bw  -R hg38_TSS.cut.bed -b 500 -a 500 -p 15 --referencePoint center -o 8505c_TSS.mat.gz  --scale 10

And finally plot:

> plotHeatmap -m 8505c_TSS.mat.gz -out heatmap_8505c_TSS.png --refPointLabel "TSS" --plotTitle "8505c_TSS"

![image](https://user-images.githubusercontent.com/44478133/89907786-17a0c180-dbbb-11ea-9542-f6fd53a08882.png)

Unfortunately, there doesn't seem to be any change in the output.

**Comment by LeilyR** [comment]
This looks strange, have you tried to set `--sortRegions descend --sortUsing mean --sortUsingSamples 1 2` to your plotHeatmap? It should not matter because they are the defaults, but just in case. I cannot reproduce this issue, so it is really difficult to see what went wrong.  By the way, would you please update your deeptools and use the latest one (3.4.3). If these did not help, you could share with me your bigwigs and bed file and I can try it here to see if I can reproduce this.

**Comment by umasstr** [comment]
Thanks for the suggestions. I updated to 3.3.1 and plotted using the additional sort flags. No change in the plot. 
The bigwigs created by deeptools bamCoverage (CPM) look identical to bigwigs created by other software (RAW):
![image](https://user-images.githubusercontent.com/44478133/90154314-f7f2d000-dd57-11ea-9991-2f00adf63a89.png)

I would be happy to share these files with you. Please let me know where I should send a dropbox link. Thanks again!

**Comment by Drosophilid** [comment]
Hi @LeilyR,
I'm working on Drosophila ChIP-seq data and I also have sort of same issue while plotting "plotHeatmap". My profile plot looks normal, but the heatmap does not refer the same answer.

![sample1 heatmap](https://user-images.githubusercontent.com/64106867/90238355-1aebb580-de26-11ea-8bf3-9b0407a54a8c.png)

deepTools version: 3.4.3
Python version: 3.8.5 

Any kind of help or suggestions will be highly appreciated.
Thanks

**Comment by LeilyR** [comment]
Hey, This one actually does not look any strange to me. It seems properly sorted to me. The default for sorting is mean of a row of matrix , and I would say by eye it really seems like it descends. What did you find strange about it?

**Comment by LeilyR** [comment]
@umasstr would you mind sharing a downloadable link with me here. (e.g. wetransfer)

**Comment by umasstr** [comment]
Hi @LeilyR, please find a sample bigwig here: https://www.dropbox.com/s/q6qtlx771fnf26k/8505c_DHT_AR.dup.bw?dl=0

Thanks again.

**Comment by LeilyR** [comment]
Hi @umasstr I have made a matrix and plotted it using deeptools 3.4.3 and it seems that I cannot reproduce your issue. I have made a bed file of 300 hg38 genes and used the following command lines: 
`computeMatrix reference-point -S 8505c_DHT_AR.dup.bw -R test.bed -b 500 -a 500 -p 15 --referencePoint TSS -o 8505c_TSS.mat.gz --scale 10 --missingDataAsZero`
`plotHeatmap -m 8505c_TSS.mat.gz -o 8505c_TSS.mat.png --refPointLabel "TSS" --plotTitle "8505c_TSS"`
Here is the figure:
![8505c_TSS mat](https://user-images.githubusercontent.com/25766687/90399239-f0eef900-e09a-11ea-8e08-3cb04226cb0a.png)
and the bed file I have generated:

[test.bed.gz](https://github.com/deeptools/deepTools/files/5084355/test.bed.gz)

**Comment by umasstr** [comment]
Thanks for giving that a try! I'll update deeptools to 3.4.3 and start from scratch.

**Comment by LeilyR** [comment]
> Thanks for giving that a try! I'll update deeptools to 3.4.3 and start from scratch.

Let us know if there was still any confusion.
