### ISSUE TITLE
Error in finding bam index of temporary files

### ISSUE THREAD

**Issue by BioInf2305** [deeptools/deepTools#984]
Hello, 

I am using "deeptools version 3.4.3" in python version 3.7.0. I ran the following command 

`
correctGCBias -b HF1_rh.rmDupliIndelRealigned.bam --effectiveGenomeSize 2715825630 --genome ~/tools/kentUtils/bosTauARS-UCD1.2.bit --GCbiasFrequenciesFile HF1_Frq.txt -o gc_corrected.bam --numberOfProcessors 6
`
Although the job completed successfully, and it generated the "gc corrected" bam file, it also generated these messages:

[E::idx_find_and_load] Could not retrieve index file for '/tmp/_deeptools_0z0832z4.bam
[E::idx_find_and_load] Could not retrieve index file for '/tmp/_deeptools_0z0832z4.bam'
.
.
[E::idx_find_and_load] Could not retrieve index file for '/tmp/_deeptools_k32lfwv5.bam'

Altogether there were about 2700 such messages. Now my question is should I trust the output (GC corrected bam) file?

**Comment by LeilyR** [comment]
This message is from pysam. What is your pysam version? 
Apparently, this is already an open issue in pysam. According to the developer, it is only diagnostic message and can be ignored. Check this:
`https://github.com/pysam-developers/pysam/issues/939`

**Comment by BioInf2305** [comment]
Thanks for the quick response, I am also using the same version of pysam (pysam==0.16.0.1). But as mentioned in the thread (https://github.com/pysam-developers/pysam/issues/939#issuecomment-666616951), I will downgrade pysam to "0.15.3" and see that if this issue can be resolved.

**Comment by LeilyR** [comment]
I wonder if using pysam==0.15.3 solved this problem. Could you please let us know if your issue is solved with downgrading the version?

**Comment by szeplakib** [comment]
I know it was not my issue, but I also had pysam==0.16.0.1 installed, and deeptools gave me the same errors.
I found this issue, and downgrading did the trick.

Thanks for the advice!

**Comment by LeilyR** [comment]
Thanks @szeplakib , I will restrict its version in the setup.
