### ISSUE TITLE
deepTools installation

### ISSUE THREAD

**Issue by niallghowlett** [deeptools/deepTools#986]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [ ] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

 - [ ] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.

 - [ ] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).

 - [ ] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).

**Comment by niallghowlett** [comment]
Hi I'm trying to install deepTools on a server to use computeMatrix and get the following error:

~$ pip install deepTools
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting deepTools
  Using cached https://files.pythonhosted.org/packages/51/72/c6b2fdf1ab026ff827e7b8dce72643046ae8744499eb209844aa2cbd3d75/deepTools-3.4.3.tar.gz
Requirement already satisfied: numpy>=1.9.0 in /opt/anaconda/anaconda3/lib/python2.7/site-packages (from deepTools) (1.15.4)
Requirement already satisfied: scipy>=0.17.0 in /opt/anaconda/anaconda3/lib/python2.7/site-packages (from deepTools) (1.0.0)
ERROR: Could not find a version that satisfies the requirement matplotlib>=3.1.0 (from deepTools) (from versions: 0.86, 0.86.1, 0.86.2, 0.91.0, 0.91.1, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1rc1, 1.4.1, 1.4.2, 1.4.3, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.1.0rc1, 2.1.0, 2.1.1, 2.1.2, 2.2.0rc1, 2.2.0, 2.2.2, 2.2.3, 2.2.4, 2.2.5)
ERROR: No matching distribution found for matplotlib>=3.1.0 (from deepTools)
WARNING: You are using pip version 19.3.1; however, version 20.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
~$ computeMatrix
Traceback (most recent call last):
  File "/usr/local/bin/computeMatrix", line 4, in <module>
    import deeptools.misc
ImportError: No module named deeptools.misc

**Comment by bgruening** [comment]
@niallghowlett if you can please use python3. Also we recommend to use conda packages.

**Comment by LeilyR** [comment]
@niallghowlett I hope installing python3 already solved your issue. I close this issue but please reopen it if there is still any remaining issue.
