### ISSUE TITLE
alignmentSieve elongates alignments

### ISSUE THREAD

**Issue by Zhuxitong** [deeptools/deepTools#987]
Hi!

I am using alignmentSieve to shift the coordinate in my bam file. I found that when the Cigar field in bam file only cotain **M**, the length of shifted bam is correct but when here are **D** or  **I** or so in Cigar field, the length of shifted bam would be a litte big. See the commands I used:
```
deeptools 3.4.3
Python 3.7.0

# first doing shift
alignmentSieve -b ${pre}_merged_rmDup.bam -o ${pre}_atacShift.bam -p 1 --ATACshift

# for reads *ST-E00243:491:HMV2NCCXY:2:2205:21927:5757* before shift (partial, ignore sequence and quality)
ST-E00243:491:HMV2NCCXY:2:2205:21927:5757       163     Chr01   554     60      8S45M6I49M1I37M =
ST-E00243:491:HMV2NCCXY:2:2205:21927:5757       83      Chr01   554     60      8S45M6I49M1I37M =
## the total match part for this reads would be 45+49+37=131

# for reads *ST-E00243:491:HMV2NCCXY:2:2205:21927:5757* after shift
ST-E00243:491:HMV2NCCXY:2:2205:21927:5757       83      Chr01   554     60      141M    =       558     -122    *       *
ST-E00243:491:HMV2NCCXY:2:2205:21927:5757       163     Chr01   558     60      142M    =       554     122     *       *
## However after shift, the match part of this reads become 141
```

We can also have a look at IGV, the reads first become longer, and then the shift is performed on the elongate reads:

The first track is make through bamToBed in bedtools;
The second track is the original bam track;
The third track is the shift track.
![QQ图片20200812180059](https://user-images.githubusercontent.com/23165349/90003071-2031ee80-dcc6-11ea-8209-901bc686747b.png)

So why the alignments with "D" or "I" become longer?

**Comment by LeilyR** [comment]
it takes the entire read and shift it, not only its matched bases. You still get a read with the same length just it got shifted. (`--shift 4 -5 5 -4`)

**Comment by Zhuxitong** [comment]
@LeilyR Really thank you for your quick reply.

I also notice this operation. For alignment with only M this is quite OK, but for these with indels or especial with S(soft clipping in either end) this looks weird.

I am wondering if this operation is intended or not because this produces really different result compared with bamToBed. And for bam file with a small fraction of S it's OK I think.

**Comment by LeilyR** [comment]
I am not sure how you mean by looking weird, in what sense? This is a common process that for ATAC data to shift the reads ends to regenerate the actual cut sites on the genome. All you do with --ATACshift  is shifting the both end of your reads by 4 to 5 bases.
bamToBed is just converting bam files to bed files, it is not shifting their coordinates.  I am not sure if I can follow you there.

**Comment by Zhuxitong** [comment]
@LeilyR Sorry I did make myself clear.

In ATAC-seq, when we align reads to genome, we usually take the two 5end alignment positions of one fragment as the exact cutting position. Like if we have two 150bp reads from a fragment, mate1 is aligned to 1-140 on positive strand of genome and mate2 aligns 300-440 on negative strand. Both with 10bp soft clipped in the end . I will treat position 5(mate1+4) and 434(mate2-6) as the cut position. 

However if using the read length, the cut position from mate1 won't be influenced but the cut position of mate2 would change to 444 as reads are 150 long.  The alignment position for mate2 now is 300-450

**Comment by LeilyR** [comment]
in your approach you will treat position 5 as cut point which is equivalent of shifting 4 bases and treating the first position as cut point (they are having the same genomic coordinate). mate2 is processed similarly. So there is not a difference between them I would say.

**Comment by Zhuxitong** [comment]
I will think about it. Thanks @LeilyR

**Comment by LeilyR** [comment]
@Zhuxitong I close the issue for now, feel free to get back to us at any time if I had any further question.
