### ISSUE TITLE
isoform reduction

### ISSUE THREAD

**Issue by mictadlo** [deeptools/deepTools#991]
Hi,
I used the Scallop results with TransDecoder. Next, I used bamCoverage to create RNA-Seq profile. I noticed that not always the first isoform is the best one compared to the RNA-Seq profile as could be seen below a few examples:

1.
![Screen Shot 2020-08-22 at 4 35 26 PM](https://user-images.githubusercontent.com/588297/90951101-e1a4ec80-e49a-11ea-8d9d-beea34a26d5e.png)

2. 
![Screen Shot 2020-08-22 at 4 38 45 PM](https://user-images.githubusercontent.com/588297/90951106-e9fd2780-e49a-11ea-85ce-6082a39bd110.png)

3.
![Screen Shot 2020-08-22 at 4 51 37 PM](https://user-images.githubusercontent.com/588297/90951109-f41f2600-e49a-11ea-86c4-b61c63a2466d.png)

4. 
![Screen Shot 2020-08-22 at 4 58 42 PM](https://user-images.githubusercontent.com/588297/90951113-000ae800-e49b-11ea-85a4-077c77a9d2e3.png)

5.
![Screen Shot 2020-08-22 at 5 04 34 PM](https://user-images.githubusercontent.com/588297/90951118-07ca8c80-e49b-11ea-80ac-421c3f85ca98.png)

By any chance, is there a way to keep only the best isoform?

Thank you in advance,

Michal

**Comment by LeilyR** [comment]
I am not sure if I can get your point from the figures you have sent, is the isoform in the red box is `the best isoform`? You get indeed the coverage over all isoforms if you have them all in your bam file. Would not filtering your bam file helping you to get the coverage of the only isoform that you are interested in?

**Comment by mictadlo** [comment]
Hi,
Yes, the isoform in the red box is the best isoform for us. Do you have any suggestions on how it would be possible to filter the BAM file?

Thank you in advance,

Michal

**Comment by LeilyR** [comment]
what about bedtools intersect?

**Comment by LeilyR** [comment]
Well my idea was  to just look at the intersect of your bam file with a bed file where you already have the coordinates of your isoform of interest. You might need be careful on how to do it, to only get that specific isoform since your isorforms are overlapped. Check the offered parameters by bedtools and maybe even end up using it twice to exclude the other isoforms, I would say. 
If you really want to know how to make bed file, they are just tsv files and you can check[ this link](https://genome.ucsc.edu/FAQ/FAQformat.html#format1) for more info about it.

**Comment by mictadlo** [comment]
We have around 50.000 expressed genes, therefore I thought to do it automatically rather than manually go through all the genes.

**Comment by LeilyR** [comment]
I see, you sure that the tool you used to detect these genes don't have an output of bed format? Are you having gtf/gff files and want to convert them to bed files? In that case you can check tools that do this conversion for you such as [BEDOPS](https://bedops.readthedocs.io/en/latest/content/reference/file-management/conversion/gtf2bed.html) or [gffutils](https://pythonhosted.org/gffutils/index.html).

**Comment by mictadlo** [comment]
I checked Scallop and TransDecoder and it appears that they don't output BED files. Scallop provides GTF but TransDecoder output a GFF3 file. When I convert GFF3/GTF file to BED then what would be the next step?

Thank you in advance,

Michal

**Comment by LeilyR** [comment]
then you can use bedtools to look for the intersect of the regions of interest and the alignment file

**Comment by LeilyR** [comment]
I hope we could help you answering your question. I close this issue for now but feel free to get back to us if there was any question left.
