### ISSUE TITLE
Any way to arrange figure produced by `plotHeatmap`?

### ISSUE THREAD

**Issue by Sylarair** [deeptools/deepTools#993]
**Welcome to deepTools GitHub repository! Before opening the issue please check
that the following requirements are met :**

 - [x] Search whether this issue (or a similar issue) has been solved before
 using the search tab above. Link the previous issue if appropriate below.

 - [x] Paste your deepTools version (`deeptools --version`) and your python
 version (`python --version`) below.

 - [x] Paste the full deepTools command that produces the issue below
 (ignore if you simply spotted the issue in the code/documentation).

 - [x] Paste the output printed on screen from the command that produces the issue
 below (ignore if you simply spotted the issue in the code/documentation).

Hi,

What I wonder is that whether there is any way to arrange 100 subfigures in a figure produced by `plotHeatmap` into 10 * 10 (rows * cols*)? By default, these 100 subfigures would be in one row, and the figure will have very long width (The code is: `plotHeatmap -m RNASeq_signal.gz -out RNASeq_signal.pdf --averageTypeSummaryPlot mean`). Does anyone have any idea to deal such issue (The attached figure is a simple example)? Many thanks!

<img width="1024" alt="Screen Shot 2020-09-03 at 9 40 34 AM" src="https://user-images.githubusercontent.com/18133362/92061699-85f72f00-edc9-11ea-8374-ffdbe6452563.png">

**Comment by LeilyR** [comment]
Hi, No it does not do that. This may be due to the confusion it could create between having several  score files and one group of regions or several groups of regions and one score file. I think the easiest thing to do now would be making smaller matrices to generate sub-figures of your current figure and align them manually, if that helps.

**Comment by Sylarair** [comment]
Thanks a lot for your advice! I found that `plotHeatmap` cannot do this while `plotProfile` can.
