### ISSUE TITLE
Question re. color breaks?

### ISSUE THREAD

**Issue by PocketChangeJ** [deeptools/deepTools#994]
Hi! Thanks so much for making deeptools available to everyone - i love it.

Have just quick question - I'm wondering if there is an option to adjust color breaks on the heatmaps?
Couldn't find - wonder if I missed that.
Thanks.

**Comment by LeilyR** [comment]
What do you exactly mean by color breaks? zMin and zMax can be used to give a range to the intensity but I don't know if they are what you are looking for. If you men at what number blue turns to red for example, this does not exist as an option.  However you can still approach it by setting the right zmin/zmax I would say.

**Comment by mirax87** [comment]
Additionally, with plotHeatmap --colorList you can use more than two colors per sample. Together with --zMin/--zMax , you can generate your color breaks and align them with e.g. z = 0.

**Comment by PocketChangeJ** [comment]
Ok great, yes I meant the transition between the colors.  And thank you - sounds like  --colorList option could be what I've been looking for. Thanks again! 👍
