### ISSUE TITLE
bamCoverage output bedgraph which does not cover the whole genome 

### ISSUE THREAD

**Issue by brainfo** [deeptools/deepTools#996]
I have used bamCoverage on several bam files. 
The output bedgraphs have different rows:
  

> 34149376 CTCF_RPKM.bedgraph
>   30743657 H3K27me3_RPKM.bedgraph
>   34565941 H3K36me3_RPKM.bedgraph
>   27342822 H3K4me1_RPKM.bedgraph
>   26398206 H3K4me3_RPKM.bedgraph
>   31264478 H3K9me3_RPKM.bedgraph
>   32224427 NANOG_RPKM.bedgraph
>   36013535 POU5F1_RPKM.bedgraph

if I outer join these bedgraphs, I can see lots of NaNs, as in:

> 	chrom	start	end	H3K9me3_RPKM	H3K36me3_RPKM	H3K4me1_RPKM	POU5F1_RPKM	H3K27me3_RPKM	NANOG_RPKM	CTCF_RPKM	H3K4me3_RPKM
> 0	chr1	0	3000100	0.000000	NaN	NaN	NaN	NaN	NaN	NaN	NaN
> 1	chr1	3000100	3000350	0.661595	NaN	NaN	NaN	NaN	NaN	NaN	NaN
> 2	chr1	3000350	3000450	0.330798	NaN	NaN	NaN	NaN	NaN	NaN	NaN
> 3	chr1	3000450	3000550	0.661595	NaN	NaN	NaN	NaN	NaN	NaN	NaN
> 4	chr1	3000550	3000600	0.992393	NaN	NaN	NaN	NaN	NaN	0.588	NaN

The inner join results have gapped genomic coordinates, as in:

> 	chrom	start	end	H3K9me3_RPKM	H3K36me3_RPKM	H3K4me1_RPKM	POU5F1_RPKM	H3K27me3_RPKM	NANOG_RPKM	CTCF_RPKM	H3K4me3_RPKM
> 0	chr1	3030800	3030850	2.97718	0.683506	0.477145	1.475750	1.226970	1.89047	1.470	0.772845
> 1	chr1	3037600	3037650	18.19390	3.189700	0.477145	0.983835	1.226970	1.51238	1.176	2.318540
> 2	chr1	3047700	3047750	5.95436	1.367010	0.238573	1.721710	2.147200	2.64666	1.176	1.932110
> 3	chr1	3063000	3063050	6.61595	0.911342	2.385730	2.213630	0.306743	51.79890	0.882	1.159270
> 4	chr1	3095350	3095400	7.60835	0.911342	0.477145	3.935340	2.760690	3.02475	1.764	0.772845

These files are processed through the same pipeline, as:
sambamba view to exclude unmapped and duplicate;
bedtools intersect -v to exclude encode blacklist region;
and remove chrM from bam files.
Then on these bam files I used bamCoverage --normalizeUsing RPKM -e {d calculated from macs2 predicd};

Should bamCoverage output the same 50bp binned values by default or does it make sense that some histone markers' ChIP-seq cover a limited region of genome and thus got NaN values?

**Comment by LeilyR** [comment]
non covered regions by default considered as zero, unless one sets `skipNonCoveredRegions`. These regions are skipped when writing bedgraph files, as far as I know.

**Comment by vivekbhr** [comment]
@brainfo the non-covered regions are either zeros or skipped from bamCoverage output. if you just need counts on exactly the same bins from all BAM files, you can use `multiBAMSummary bins`
