### ISSUE TITLE
Changing x and y-axes of plotCoverage

### ISSUE THREAD

**Issue by EveTC** [deeptools/deepTools#998]
Hello

Firstly - thank you for this tool it is proving super useful!
I am using `deeptools 3.5.0`

I have successfully run `plotCoverage` on my `.bam` file and it has output the coverage plot.

However, is there a way to change the limits of the x and y-axis? My apologies if there is a simple solution. I am new to these types of tools and could not find a solution online.

Thanks in advance!
Eve

**Comment by LeilyR** [comment]
At the moment it can not be given in the command line and user needs to change it here: 
https://github.com/deeptools/deepTools/blob/master/deeptools/plotCoverage.py#L328
I will add it into the todo list for the next release though.

**Comment by EveTC** [comment]
Fantastic thank you @LeilyR

**Comment by zeynepkurtw** [comment]
Hi,

Can I make the change to the script that I installed through conda? I couldn't find the script in the bin. I've also tried installing it through git clone but then python setup.py didn't work properly. The package was missing all the libraries like numpy, matplotlib etc.

Thanks in advance!

**Comment by dpryan79** [comment]
You can edit the package after installing via conda. It will be under $PREFIX/lib. You'll need to delete __pycache for it to be recognized (within the same directory).

**Comment by zeynepkurtw** [comment]
Okay, thanks. I did manage to install and set up deeptools without conda. I also manipulated the script and now it looks like this:

```if args.plotFile:
        # Don't clip plots
        y_max = max(y_max)
        if args.plotFileFormat == "plotly":
            fig.add_traces(data)
            fig['layout']['yaxis1'].update(range=[0.0, y_max])
            fig['layout']['yaxis2'].update(range=[0.0, 1.0])
            py.plot(fig, filename=args.plotFile, auto_open=False)
        else:
            axs[0].set_ylim(0, y_max)
            axs[0].set_xlim(0, x_max)
            axs[0].set_xlabel('coverage (#reads per bp)')
            axs[0].legend(fancybox=True, framealpha=0.5)
            axs[0].set_ylabel('fraction of bases sampled')
            # plot cumulative coverage
            axs[1].set_xlim(0, x_max)
            axs[1].set_xlabel('coverage (#reads per bp)')
            axs[1].set_ylabel('fraction of bases sampled >= coverage')
            axs[1].legend(fancybox=True, framealpha=0.5)
            plt.savefig(args.plotFile, format=args.plotFileFormat)
            plt.close()
```


however, my plot is still cliped on the y-axis. 
![Masurca_3_coverage](https://user-images.githubusercontent.com/34158306/166205146-e523fb81-b668-4524-bac2-5b964fde6d34.png)
